packages/backend/src/managers/applicationManager.ts, packages/backend/src/registries/RecipeStatusRegistry.ts, packages/backend/src/registries/TaskRegistry.ts, packages/backend/src/studio-api-impl.ts, packages/backend/src/studio.ts, packages/backend/src/utils/recipeStatusUtils.ts, packages/frontend/src/pages/Models.svelte, packages/frontend/src/pages/Recipe.svelte, packages/shared/StudioAPI.ts, packages/shared/models/ITask.ts
- Adding central place to register tasks
- Adding labels to tasks etc.
=> feat: adding TaskRegistry

.github/workflows/build-next.yaml
fixes https://github.com/projectatomic/studio-extension/issues/39
=> chore: use cache and deploy to local GitHub OCI repository

packages/backend/src/studio-api-impl.ts, packages/shared/StudioAPI.ts
Fixes #60
https://github.com/projectatomic/studio-extension/assets/42176370/cae2e860-b9a9-4c40-b949-360dd6aecc7d
=> feat: adding support for opening external urls

packages/frontend/src/pages/Model.svelte, packages/frontend/src/pages/Models.svelte, packages/frontend/src/pages/Recipe.svelte, packages/frontend/src/pages/Recipes.svelte
=> fix: removing search bar as logic not implemented

.eslintrc.json, package.json, packages/backend/package.json, packages/backend/src/managers/applicationManager.ts, packages/backend/src/managers/catalogManager.ts, packages/backend/src/managers/playground.ts, packages/backend/src/models/AIConfig.ts, packages/frontend/package.json, packages/shared/src/messages/MessageProxy.ts, yarn.lock
fixes issues reported by using the same rules
it also fixes https://github.com/projectatomic/studio-extension/issues/97
avoid to see
=> chore: add missing linting rules from Podman Desktop

.gitignore
=> fix: handle JetBrains IDEs in .gitignore

.github/workflows/build-next.yaml, README.md, package.json, packages/backend/package.json, packages/frontend/package.json
OCI image is also renamed and main branch is published as nightly
Fixes #124
=> fix: rename from studio-extension to ai-studio

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts
It fixes an error that prevented from returning the actual model path when it was downloaded during the pull application workflow
=> fix: return correct path when downloading model

.github/workflows/release.yaml
=> fix: add release workflow

packages/backend/src/managers/playground.ts, packages/backend/src/studio-api-impl.spec.ts, packages/backend/src/studio-api-impl.ts, packages/backend/src/studio.ts
Fixes https://github.com/projectatomic/studio-extension/issues/151
=> feat: creating task in task manager

packages/backend/src/studio-api-impl.ts
Based on the discussion from https://github.com/projectatomic/ai-studio/pull/152#discussion_r1469942219 
PR was merged before it was actually fixed
=> fix: remove unnecessary void

packages/backend/src/ai.json
This PR just adds a new model to our catalog. It was suggested by Michael
N/A
this is part of https://github.com/projectatomic/ai-studio/issues/201
N/A
=> chore: add new mistral model

.github/workflows/release.yaml
Fixes #224
Use the tag to build the image when releasing
N/A
#224 
N/A
=> build: use tag to build image in release build

packages/backend/src/managers/applicationManager.ts, packages/frontend/src/lib/NavPage.spec.ts, packages/frontend/src/lib/NavPage.svelte, packages/frontend/src/lib/table/Table.spec.ts, packages/frontend/src/lib/table/Table.svelte, packages/frontend/src/lib/table/TestTable.svelte, packages/frontend/src/pages/Recipe.spec.ts, packages/frontend/src/pages/Recipe.svelte, packages/frontend/src/pages/RecipeModels.svelte
This PR just update the UI of the running application panel so that i can work on the switch model enhancement.
It renames the button, it creates a panel which is visible through all tabs and can be open/closed, and show the model used when running the application. Now it still uses llama as before.
it is part of #201 
it closes #163 
1. go to a recipe page and run the application.
2. everything should work as before, it just have a different UI
=> feat: update design when running application

Containerfile, packages/backend/src/studio.ts, packages/frontend/src/index.html
Fixes #229
Update naming to AI Studio
N/A
#229 
Check tooltip on webview icon
=> fix: rename remaining Studio extension to AI Studio

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/backend/src/managers/modelsManager.spec.ts, packages/backend/src/managers/modelsManager.ts, packages/backend/src/utils/recipeStatusUtils.spec.ts, packages/backend/src/utils/recipeStatusUtils.ts, packages/frontend/src/lib/ExpandableMessage.svelte, packages/frontend/src/lib/progress/TasksProgress.spec.ts, packages/frontend/src/lib/progress/TasksProgress.svelte, packages/frontend/src/pages/Recipe.svelte, packages/shared/src/models/ITask.ts
Adding an error property to Task interface
https://github.com/projectatomic/ai-studio/assets/42176370/0d6cedfd-d413-46fd-90f4-7462570ef6bf
Fixes https://github.com/projectatomic/ai-studio/issues/240
=> feat: adding error to task interface and display it to the user

packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/pages/Recipe.spec.ts, packages/frontend/src/pages/Recipe.svelte
Extract the Application/Recipe details code to a standalone component 
No visual changes
Fixes https://github.com/projectatomic/ai-studio/issues/251
- Tests in `Recipe.spec.ts` ensure no regression
=> refactor: extract RecipeDetails to a component

packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/pages/Recipe.svelte
Transform the flex system to a grid, as it offers better way of enforcing the structure we requires (markdown shrink, and application details **fixed** size)
https://github.com/projectatomic/ai-studio/assets/42176370/d6f88229-c05e-41ae-a258-5859fa494738
Fixes https://github.com/projectatomic/ai-studio/issues/238
Open application and resize windows
=> fix: application details hidden

packages/backend/package.json, packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/shared/src/StudioAPI.ts
Fixes #162
Images generated for a recipe have now a specific icon in the image list
#162 
Run a recipe and go to the image page
=> feat: generated images should have a specific icon

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/shared/src/StudioAPI.ts
For a very weird reason a synthax error was able to be merged in main, and lead to linter issue in some pull request checks.
Seems to have been introduced by https://github.com/projectatomic/ai-studio/pull/248
=> fix: linter issue

packages/frontend/src/pages/Recipe.svelte
This PR just remove unused code. I guess we forgot them during a refactoring
N/A
N/A
1. nothing should change
=> fix: clean Recipe.svelte

packages/backend/src/managers/playground.spec.ts, packages/backend/src/managers/playground.ts, packages/backend/src/studio-api-impl.ts, packages/frontend/src/pages/ModelPlayground.svelte, packages/shared/src/models/IPlaygroundState.ts
Adding error property to PlaygroundState (similar to https://github.com/projectatomic/ai-studio/pull/241)
Fixes https://github.com/projectatomic/ai-studio/issues/268
=> feat: improve playground error management

packages/frontend/src/lib/RecipeDetails.svelte
Remove unwanted space in recipe page
| --- | --- |
| ![image](https://github.com/projectatomic/ai-studio/assets/42176370/602beddd-dbe1-4b85-baea-321d79f09d58) | ![image](https://github.com/projectatomic/ai-studio/assets/42176370/5694aca3-525b-4cb2-ae17-fd930c52e21a) |
Fixes https://github.com/projectatomic/ai-studio/issues/287
- Go to recipe page and resize screen
=> fix: remove unwanted space above application details

docs/proposals/ai-studio.md
Add a new proposal for a change
N/A
N/A
N/A
=> doc: ai-studio.yaml changes proposal

packages/backend/src/managers/applicationManager.ts, packages/backend/src/registries/LocalRepositoryRegistry.spec.ts, packages/backend/src/studio-api-impl.ts, packages/frontend/src/lib/RecipeDetails.spec.ts, packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/lib/images/VSCodeIcon.svelte, packages/frontend/src/pages/Recipe.spec.ts, packages/frontend/src/utils/localRepositoriesUtils.ts, packages/shared/src/StudioAPI.ts, packages/shared/src/models/ILocalRepository.ts
Adding a `VS Code Desktop` button.
> See https://code.visualstudio.com/brand#brand-legal for the name of button used
https://github.com/projectatomic/ai-studio/assets/42176370/7b63d7b8-8167-4d60-bbb3-990f3e05af9c
Fixes https://github.com/projectatomic/ai-studio/issues/27
**manually**
(1) Open a recipe
(2) Start application
(3) See the `Open in VS Code Desktop` button
=> feat: adding vscode button

package.json, packages/backend/package.json, packages/backend/src/extension.spec.ts, packages/frontend/package.json, yarn.lock
The existing tests in `extension.spec.ts` was not compatible with vitest 1.3.0
Fixes https://github.com/projectatomic/ai-studio/issues/364
=> fix: unit tests not compatible with vitest 1.3.0

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/backend/src/registries/ApplicationRegistry.ts, packages/backend/src/registries/RecipeStatusRegistry.spec.ts, packages/backend/src/registries/RecipeStatusRegistry.ts, packages/backend/src/studio-api-impl.spec.ts, packages/backend/src/studio-api-impl.ts, packages/backend/src/utils/recipeStatusUtils.spec.ts, packages/backend/src/utils/recipeStatusUtils.ts, packages/frontend/src/lib/EnvironmentActions.svelte, packages/frontend/src/lib/RecipeDetails.spec.ts, packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/pages/Environments.svelte, packages/frontend/src/pages/Models.spec.ts, packages/frontend/src/pages/Recipe.spec.ts, packages/frontend/src/stores/recipe.ts, packages/shared/src/StudioAPI.ts, packages/shared/src/models/IRecipeModelIndex.ts, packages/shared/src/models/IRecipeStatus.ts
Index the environments (applications) by (recipeId, modelId) instead of recipeId only.
Fixes #281 
Start, stop, restart applications from environments page and recipe page. Should work as before
=> Environments depends on recipe and model

packages/backend/src/ai.json
it adds the code generation application to the catalog
it is part of #262 
1. in the catalog you should see the new code generation app, run it and ask to generate code
=> chore: add code generation ai app to catalog

packages/backend/src/ai.json
This PR updates the version of the summarizer app to the latest using streamlit and model service check
N/A
it is part of #262 
1. delete local cloned summarizer folder, then run summarizer app
=> chore: update summarizer app to use the latest

packages/backend/src/managers/applicationManager.ts
Before
https://github.com/projectatomic/ai-studio/assets/9973512/9d42dbb4-7b0e-4894-8ed2-7c108a4ca022
After
https://github.com/projectatomic/ai-studio/assets/9973512/d80e14cf-1511-49a4-bfb5-912742da9060
Fixes #396 
Stop then start an application
=> fix: remove previous tasks when starting application

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/backend/src/studio-api-impl.ts, packages/frontend/src/App.svelte, packages/frontend/src/lib/EnvironmentActions.svelte, packages/frontend/src/lib/Navigation.svelte, packages/frontend/src/lib/RecipeDetails.spec.ts, packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/pages/Environments.svelte
Replaces the Environments terms with AI Apps (on the frontend, the code-related changes will come with #368 when everyone agrees on this term)
#367 
No "Environment" term should be displayed to the user
=> Rename Environments with AI Apps (user visible)

.github/workflows/build-next.yaml, .github/workflows/pr-check.yaml, .github/workflows/release.yaml, package.json, packages/backend/package.json, yarn.lock
Fixes https://github.com/projectatomic/ai-studio/issues/416
=> chore(deps): bump node 18 to 20

packages/frontend/src/lib/Card.svelte, packages/frontend/src/lib/Checkbox.svelte, packages/frontend/src/lib/ErrorMessage.svelte, packages/frontend/src/lib/NavPage.svelte, packages/frontend/src/lib/Navigation.svelte, packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/pages/ModelPlayground.svelte
it fixes all svelte errors detected in https://github.com/projectatomic/ai-studio/pull/419
N/A
fixes #418 
Everything should work as before
=> fix: fix svelte errors

.github/workflows/pr-check.yaml, package.json, yarn.lock
ensure code written in svelte components compiles
(and it is failing now)
related to https://github.com/projectatomic/ai-studio/issues/418
=> chore: add svelte check when checking PRs

PACKAGING-GUIDE.md
It updates the documentation to mention the ports property
N/A
it resolves #387 
N/A
=> docs: mention ports property into packaging-guide (#387)

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts
Fixes #428
Update the playground image
N/A
#428
Start a playground for a model
=> fix: use CI built playground image

packages/backend/package.json, yarn.lock
With 1.8 coming soon, we should bump to use latest features. (required by https://github.com/projectatomic/ai-studio/pull/444)
=> chore(deps): bump podman desktop version

packages/backend/package.json, yarn.lock
=> chore(dependencies): bump @podman-desktop/api to 1.8.0

package.json, packages/backend/package.json, packages/frontend/package.json
Relates to #460
Bump to 0.2.0 to prevent back updates
N/A
#460 
yarn build
=> chore: Bump version to 0.2.0

packages/backend/src/assets/ai.json, packages/frontend/src/lib/Card.svelte, packages/frontend/src/lib/NavPage.svelte, packages/frontend/src/lib/RecipesCard.svelte, packages/frontend/src/pages/Recipes.svelte, packages/frontend/src/utils/categoriesUtils.ts
this PR updates the font, background color and icons to make it more similar to the mockup -> https://design.penpot.app/#/view/52961d58-0a92-80c2-8003-2a6919ad37d6?page-id=51af7f49-bd09-8090-8003-8c5efc23847f&section=interactions&index=22
it resolves #478 
1. open the recipe catalog ui. Everything should work as before
=> fix: fix font, colors and icon on recipes catalog UI

packages/frontend/src/lib/Card.svelte, packages/frontend/src/lib/table/Table.svelte
I didn't notice that https://github.com/projectatomic/ai-studio/pull/506 made the models table header have a different color compared to the background and also the images background were shrinked. This fixes both
N/A
1. check icons and models table header
=> fix: fix model table header and image size

README.md
Fixes #232
Update README to install extension with a simple click
N/A
#232 
N/A
=> fix: add link to install released version

packages/frontend/src/lib/table/model/ModelColumnName.svelte
Change the font of the first column in the models list, to have the same as in other lists
Part of #479
=> ui: set correct font for name column in models list

packages/backend/src/studio-api-impl.ts, packages/shared/src/StudioAPI.ts
Adding a `getHostFreePort()` api. 
Fixes https://github.com/projectatomic/ai-studio/issues/536
Required for https://github.com/projectatomic/ai-studio/pull/529
=> feat: adding getHostFreePort API

packages/frontend/src/pages/Applications.svelte
(1) Open AI Apps when nothing is running
=> feat: improve message in AI Apps when none is running

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/backend/src/utils/podman.spec.ts, packages/backend/src/utils/podman.ts
it adds a check so that the Z flag is not used when working with qemu machine
N/A
it resolves #538 
1. run a recipe on qemu
=> fix: do not use Z flag on QEMU

README.md
Fixes #567
Update README
N/A
#567 
Open README.md
=> fix: update developer section of README

packages/frontend/src/app.css, packages/frontend/src/pages/Applications.svelte, packages/frontend/src/pages/InferenceServerDetails.svelte, packages/frontend/src/pages/InferenceServers.svelte, packages/frontend/src/pages/Models.svelte, packages/frontend/src/pages/Recipes.svelte
Fix the scrollbar used in AI-Studio to match the one in Podman-Desktop. It mostly remove css class that make it being displayed when it should not.
| --- | --- |
| ![image](https://github.com/projectatomic/ai-studio/assets/42176370/6fa7103e-20c7-4bd1-97da-9e3e10d0090a) | ![image](https://github.com/projectatomic/ai-studio/assets/42176370/2b826b20-2aee-47cd-a284-11aacc0276c4) |
| ![image](https://github.com/projectatomic/ai-studio/assets/42176370/9dfdc824-054b-4916-89dc-60e4c2f4068c) | ![image](https://github.com/projectatomic/ai-studio/assets/42176370/fd9ab3db-013e-443f-be15-f9873df64659) |
| ![image](https://github.com/projectatomic/ai-studio/assets/42176370/a4b5f916-dab5-4ff0-84ad-d4e8e51ea4da) | ![image](https://github.com/projectatomic/ai-studio/assets/42176370/ffcd2 …
=> fix: scrollbar design and overflow

.github/workflows/release.yaml
Fixes #586
Update the release workflow
N/A
#586
N/A
=> build: fix invalid version in released image

packages/frontend/src/pages/Playgrounds.svelte
- adds a message when there is no playground in the list
- removes scrollbar when not necessary
Fixes #595
=> Show a message when there is no playground in the list 

packages/backend/src/managers/playgroundV2Manager.spec.ts, packages/backend/src/managers/playgroundV2Manager.ts, packages/backend/src/registries/conversationRegistry.ts, packages/backend/src/studio-api-impl.ts, packages/frontend/src/lib/table/playground/ConversationColumnAction.spec.ts, packages/frontend/src/lib/table/playground/ConversationColumnAction.svelte, packages/frontend/src/lib/table/service/ConversationColumnAction.svelte, packages/frontend/src/pages/Playgrounds.svelte, packages/shared/src/StudioAPI.ts
Adding a delete button to the conversation lists
Fixes https://github.com/projectatomic/ai-studio/issues/526
=> feat(playground): adding delete conversation capabilities

packages/backend/src/utils/uploader.ts
Adding code comments to the uploader. thanks @lstocchi for helping me ! 
> This PR is also simplifying the filter to find, as we only expect one worker per system.
=> chore(uploader): adding code comments

packages/backend/src/templates/quarkus-langchain4j.mustache
Fixes #633
Fix a typo in the Quarkus Langchain4j
N/A
#633 
Get the Quarkus Langchain4j snippet
=> fix: replace Quarkus Langchain4j ollama extension with OpenAI

packages/frontend/src/pages/InferenceServerDetails.spec.ts, packages/frontend/src/pages/InferenceServerDetails.svelte
This PR is adding the `cURL` snippet as default
https://github.com/projectatomic/ai-studio/assets/42176370/595e64c6-7aa0-470e-837d-6975cafa2bee
Fixes https://github.com/projectatomic/ai-studio/issues/644
=> feat: setting default curl snippet

packages/frontend/src/pages/Model.svelte, packages/shared/Messages.ts
=> fix: remove remains of playground v1

packages/frontend/src/pages/PlaygroundCreate.svelte
Disable the system prompt textarea when loading state
Fixes https://github.com/projectatomic/ai-studio/issues/653
=> fix(playground): disable the system prompt textarea when loading state

.github/workflows/compute-model-sizes.yml, tools/compute-model-sizes.sh
Add a new tool to compute model memory size from the catalog and a workflow to launch it
N/A
Relates to #479
Run the workflow
An example is given here: https://github.com/jeffmaury/ai-studio/actions/runs/8416856694/job/23044231069
=> build: add tool to compute model memory size

packages/frontend/src/lib/Navigation.svelte, packages/frontend/src/pages/InferenceServers.svelte
Fixes: #664
rename "Services" to "Model Services"
#664
=> rename "Services" to "Model Services"

packages/frontend/src/Route.svelte, packages/frontend/src/lib/conversation/ChatMessage.svelte, packages/frontend/src/pages/Playground.svelte
Extracting the ChatMessage of the Playground svelte component to its own.  (no modification has been made)
> This will ease in the future implementing the code generator etc.
Fixes https://github.com/projectatomic/ai-studio/issues/678
=> refactor(playgrond): create ChatMessage component

PACKAGING-GUIDE.md, packages/backend/src/assets/ai.json, packages/backend/src/managers/applicationManager.spec.ts, packages/frontend/src/lib/RecipeDetails.spec.ts, packages/frontend/src/lib/table/application/ColumnModel.spec.ts, packages/frontend/src/lib/table/model/ModelColumnAction.spec.ts, packages/frontend/src/lib/table/model/ModelColumnCreation.spec.ts, packages/frontend/src/lib/table/model/ModelColumnSize.spec.ts, packages/frontend/src/pages/Recipe.spec.ts, packages/shared/src/models/IModelInfo.ts
Adds memory footprint of models, as computed by the worflow `.github/workflows/compute-model-sizes.yaml`
Part of #479
=> add models memory footprint to catalog

packages/frontend/src/lib/table/model/ModelColumnIcon.spec.ts
Seems to be related to https://github.com/projectatomic/ai-studio/pull/650 and https://github.com/projectatomic/ai-studio/pull/674
Fixes https://github.com/projectatomic/ai-studio/issues/693
- CI should be green ✅
=> fix(typecheck): main failing 

packages/backend/src/managers/modelsManager.spec.ts, packages/backend/src/managers/modelsManager.ts
Fixes #649
Fixes the error when deleting a model (seems Windows related)
N/A
#649 
1. Download a model
2. Delete the model
=> fix: deleting a model generates an error

.github/workflows/release.yaml
Fix a typo in release workflow
N/A
N/A
N/A
=> fix: typo in release workflow

.github/workflows/build-next.yaml
change the repository package to publish the OCI image
other PR(s) will follow from @lstocchi 
related to https://github.com/containers/podman-desktop-extension-ai-lab/issues/592
=> chore: update package repository location

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/backend/src/studio.spec.ts, packages/backend/src/studio.ts, packages/shared/src/models/IApplicationState.ts
Check the healthcheck of the AI apps' pods and adds a `health` field to the data sent to the front. 
Part of #265
=> feat: check ai-app pod healthcheck

packages/backend/src/managers/applicationManager.ts, packages/backend/src/managers/podmanConnection.ts
Remove methods check required when release 1.8 was not out yet.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/242
=> fix: remove methods checks

CODEOWNERS
it adds Florent as fixed reviewer
N/A
N/A
N/A
=> chore: update CODEOWNERS with Florent fixed reviewer

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts, packages/shared/src/models/IApplicationState.ts
Provides a more precise value for the pod health ('', healthy, unhealthy, starting which are the same values as for the container health).
Part of #265
=> feat: more details for pod health

packages/backend/src/managers/SnippetManager.ts, packages/backend/src/managers/snippets/python-langchain-snippet.spec.ts, packages/backend/src/managers/snippets/python-langchain-snippet.ts, packages/backend/src/templates/python-langchain.mustache
it adds the snippet for python langchain
it resolves #406 
1. check snippet
=> feat: add python langchain snippet

packages/frontend/src/pages/InferenceServerDetails.spec.ts, packages/frontend/src/pages/InferenceServerDetails.svelte
Thanks @odockal for raising the issue.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/728
=> fix(service-details): port undefined in snippet on mount

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts
check if health is undefined on pod inspect data
Fixes #746
=> fix: undefined health in pod info

packages/frontend/src/lib/RecipeDetails.spec.ts
=> fix failing unit test

packages/backend/tsconfig.json
Enabling some strict typescript strict checks
Related to https://github.com/containers/podman-desktop-extension-ai-lab/issues/754
Pipeline should be ✅
=> chore(bakcend): enabling some strict checks 

packages/backend/src/studio.ts
Introduced by https://github.com/containers/podman-desktop-extension-ai-lab/pull/766
=> fix: remove duplicates createTelemetryLogger

packages/backend/package.json, tests/playwright/package.json, yarn.lock
=> chore(deps): bump Podman Desktop dependency

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/modelsManager.spec.ts, packages/backend/src/utils/downloader.ts, packages/backend/tsconfig.json, packages/shared/src/messages/MessageProxy.ts
Enabling `strictFunctionTypes` for the backend 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/809
=> chore(tsconfig): enabling strictFunctionTypes

packages/frontend/src/pages/InferenceServerDetails.svelte
| --- | --- |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/80fcee1f-9b76-4a9c-abb8-26f9fff37251) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/972e2eff-3468-416e-97e9-771702e9d5eb) |
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/785
=> fix: code snippet font size

packages/backend/src/managers/applicationManager.ts, packages/backend/src/registries/LocalRepositoryRegistry.spec.ts, packages/backend/src/registries/LocalRepositoryRegistry.ts, packages/frontend/src/lib/RecipeDetails.svelte, packages/shared/src/models/ILocalRepository.ts
Fixes #816
Change the recipe Open in VSCode to open in the right folder instead of the root Git repository
N/A
#816
1. Pull a recipe
2. Open the recipe in VSCode
=> fix: open recipe in the right folder

.github/workflows/release.yaml
Fixes #853
Update release workflow 
N/A
#853 
N/A
=> fix: update release workflow for playwright tests

README.md
=> doc: fix typo in README link

packages/backend/src/studio-api-impl.spec.ts, packages/backend/src/studio-api-impl.ts, packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/pages/Recipe.svelte, packages/shared/src/StudioAPI.ts
It adds telemetry for the following actions:
- Switch of models
- Open in VSCode
- Open folder with clone
N/A
it resolves #834 
N/A
=> chore: augment recipe telemetry

packages/frontend/src/pages/Dashboard.svelte
Add dots after the _here_ buttons for consistency with the paragraphs above.
=> dashboard: feedback: add dots

packages/backend/src/assets/ai.json
Fixes #887
Update model descriptions in catalog
#887 
Go to the model list and display details for each
=> fix: update model descriptions in catalog

packages/backend/src/utils/downloader.ts
Fixes #730
Fixes error spawn when deleting a just downloaded model on Windows
N/A
#730 
1. Download a model
2. Once it is downloaded, delete it
=> fix: cannot delete the model with operation not permitted

tests/playwright/src/ai-lab-extension-installation.spec.ts
* Updates DOM references in test
* Fixes test structure for better logging
N/A
#917 
* Build main branch podman-desktop in developer mode using `yarn test:e2e:build`
* export `PODMAN_DESKTOP_ARGS` to podman-desktop repository path
* execute tests in extension-ai-lab using `yarn test:e2e`
=> chore(test): fix broken ai lab extension smoke test

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts
Fixes #927
Pass model properties as environment variables to model service container 
N/A
#927
Start a recipe and check the model service container
=> fix: model properties not being transfered to model service container

packages/frontend/src/pages/Dashboard.svelte
Team sounds a bit corporate, so I propose "community".
=> dashboard: s/team/community/

packages/backend/src/utils/inferenceUtils.ts
See https://github.com/containers/podman-desktop-extension-ai-lab-playground-images/pull/12
=> chore: bump inference image version

packages/backend/src/managers/SnippetManager.ts, packages/backend/src/studio.ts, packages/backend/src/utils/downloader.ts, packages/backend/tsconfig.json
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/957
Pipeline should be ✅
=> chore(linter): enable strict property initialization

packages/backend/src/managers/applicationManager.spec.ts, packages/backend/src/managers/applicationManager.ts
Fixes #923
Report build errors while building recipe
#923
1. Delete images related to recipe
2. Modify one of the Containerfile used in a recipe
3. Verify error is report and not cannot find image
=> fix: report build error early while building recipe

packages/backend/package.json
=> chore: fix displayName / description

README.md
It updates the installation section to use the new extensions page. This needs https://github.com/containers/podman-desktop-media/pull/9
N/A
it resolves #983 
N/A
=> chore: update README for extension catalog

packages/frontend/src/pages/Models.spec.ts
=> fix flaky test

packages/frontend/src/pages/InferenceServers.svelte, packages/frontend/src/pages/Models.svelte
Fixing typos
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/997 https://github.com/containers/podman-desktop-extension-ai-lab/issues/1005
=> fix: typos

packages/backend/src/assets/ai.json
Fix #1033 
Test the following recipes with this model
- chatbot
- summarizer
- codegen
=> upgrade to instruct v0.2

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/enhancement.yml, .github/ISSUE_TEMPLATE/epic.yml, .github/ISSUE_TEMPLATE/feature_request.yml
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/959
=> chore: adding bug issue template

packages/frontend/src/pages/Dashboard.svelte
Update AI Lab to Podman AI Lab as in the latest version of the README
https://github.com/containers/podman-desktop-extension-ai-lab/pull/1029
keep it short in navbar
=> chore: update AI Lab to Podman AI Lab

packages/backend/src/assets/ai.json
Use ai-lab-recipes v1.1.1 to fix bug with some Intel CPUs 
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1031
=> chore update ai-lab-recipes to v1.1.1

packages/backend/src/assets/ai.json
Fixes #1107
Update recipes to 1.1.2
N/A
#1107 
Launch recipes
=> chore: update to v1.1.2 AI Lab Recipes

.github/workflows/ai-lab-e2e-nightly-windows.yaml
Add Windows based E2E test workflow that runs on nightly base and on demand
https://github.com/containers/podman-desktop-e2e/issues/173
On local fork only.
=> Podman Desktop AI Lab E2E nightly windows workflow

packages/frontend/src/pages/CreateService.spec.ts, packages/frontend/src/pages/CreateService.svelte
Update the "Create Service" page to use the dedicated FormPage component instead of NavPage
Also change a few colors to support light mode (except colors in the form itself)
Fixes #1231 
Navigate to Services > New Model Service
=> fix: use FormPage component for Create Service page

packages/frontend/src/pages/InferenceServerDetails.svelte
Use DetailsPage for Inference server details
Fix #1237
=> Use DetailsPage for Inference server details

packages/frontend/src/pages/Recipe.svelte, packages/frontend/src/utils/categoriesUtils.ts
Use DetailsPage for Recipe details page
Fixes #1244
=> Use DetailsPage for Recipe details page

packages/frontend/src/pages/Model.svelte
Use DetailsPage for Model details page
Fixes #1240
=> refactor: use DetailsPage for Model details page

packages/frontend/src/pages/CreateService.spec.ts, packages/frontend/src/pages/CreateService.svelte
Light mode for Create Service page
Fixes #1274
=> Light mode for Create Service page

packages/frontend/src/pages/ImportModel.svelte
Light mode for model import page
select depends on https://github.com/containers/podman-desktop/issues/6199
Fixes #1254
=> Light mode for model import page

packages/frontend/src/pages/Dashboard.svelte
Light mode for Welcome page. Changes the text color.
Needs #1246 to get the good background
Fixes #1249
=> Light mode for Welcome page

CODEOWNERS
Add @jeffmaury to CODEOWNERS
N/A
N/A
N/A
=> build: add @jeffmaury to CODEOWNERS

packages/backend/src/utils/inferenceUtils.ts
Fixes #1007
Check if image is present before pulling it
N/A
#1007
Start an inference server twice and check that second time is faster
=> fix: check if image is present before pulling

packages/frontend/src/lib/ExpandableMessage.svelte, packages/frontend/src/lib/progress/TaskItem.svelte, packages/frontend/src/lib/progress/TasksProgress.svelte
Light mode for TasksProgress
Fixes #1283
=> Light mode for TasksProgress

packages/frontend/package.json, yarn.lock
=> chore: update to the lib migrated to svelte v5

packages/backend/src/assets/ai.json
Fixes #1320
Update recipes to v1.1.3
N/A
#1320
=> chore: update to v1.1.3 AI Lab Recipes

packages/shared/src/models/IPodman.ts
Raised in https://github.com/containers/podman-desktop-extension-ai-lab/pull/1339#discussion_r1668654277
=> fix: hyperv vmtype

packages/frontend/src/lib/ContentDetailsLayout.svelte, packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/lib/notification/ContainerConnectionStatusInfo.svelte, packages/frontend/src/pages/Recipe.svelte
Fixes #1286
Light mode `Recipe details` page
#1286
=> chore: light mode `Recipe details` page

Containerfile
Fixes #1226
Align required Podman Desktop version
N/A
#1226 
N/A
=> fix: align required Podman Desktop version

packages/frontend/package.json, yarn.lock
Update @fortawesome to 6.6.0
Replaces #1382 #1385 #1389
N/A
N/A
N/A
=> chore(deps): switch @fortawesome to 6.6.0

packages/frontend/src/lib/progress/TasksBanner.svelte, packages/frontend/src/pages/StartRecipe.svelte
https://github.com/user-attachments/assets/64fcdc65-88bc-40c5-941d-6058eb9dd4d9
**dark**
**light**
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1372
Go to start recipe page
=> feat: support light theme start recipe

packages/frontend/package.json
Some deps are in the dev dependencies when they should not
=> chore: moving dev deps to dev

packages/frontend/package.json
Seems an issue between depandabot and https://github.com/containers/podman-desktop-extension-ai-lab/pull/1393 which lead to duplicates entries
- PIpeline should be :heavy_check_mark:
=> fix: duplicate package frontend

packages/backend/src/workers/provider/LlamaCppPython.spec.ts, packages/backend/src/workers/provider/LlamaCppPython.ts
Prevent incompatible/unsupported architecture to label the container with gpu.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1449
=> fix: prevent incompatible architecture to have GPU label

RELEASE.md
Fixes #1456
Add a new release process guide
N/A
#1456
Review the new markdown file
=> docs: add release guide

packages/backend/src/managers/catalogManager.spec.ts, packages/backend/src/managers/catalogManager.ts, packages/backend/src/utils/inferenceUtils.ts
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1468
=> fix: missing version on writing catalog after model deletion

packages/backend/package.json, packages/backend/src/workers/provider/InferenceProvider.spec.ts, packages/backend/src/workers/provider/LlamaCppPython.spec.ts, packages/frontend/package.json, tests/playwright/package.json, yarn.lock
=> chore: bump @podman-desktop/* to 1.12.0

packages/frontend/src/pages/CreateService.svelte, packages/frontend/src/pages/ImportModel.svelte, packages/frontend/src/pages/InferenceServerDetails.svelte, packages/frontend/src/pages/Model.svelte, packages/frontend/src/pages/Playground.svelte, packages/frontend/src/pages/PlaygroundCreate.svelte, packages/frontend/src/pages/Recipe.svelte, packages/frontend/src/pages/StartRecipe.svelte
Thanks https://github.com/containers/podman-desktop-extension-bootc/pull/721 for the fix
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1492
Click on breadcrumbs :)
=> fix: breadcrumbs svelte 5

packages/backend/src/workers/provider/LlamaCppPython.ts
Fixes #1548
Set gpuLayers pon MacOS
N/A
#1548 
Create an inference server
=> fix: gpulayers were not set correctly on MacOS

packages/backend/src/workers/provider/LlamaCppPython.ts
Fixes #1548
Set gpuLayers pon MacOS
N/A
#1548
Start a recipe on libkrun
=> fix: gpulayers where not set correctly on MacOS (#1555)

packages/backend/src/assets/inference-images.json
Fixes #1557
Update CUDA and Vulkan images as the ones from ai-lab-recipes are too old
N/A
#1557 
Test with Granite code model
=> fix: update vulkan image to work with Granite code model (#1558)

.eslintignore, api/openapi.yaml, clean.sh, package.json, packages/backend/package.json, packages/backend/src/managers/apiServer.spec.ts, packages/backend/src/managers/apiServer.ts, packages/backend/src/studio.ts, yarn.lock
Add list models operation to the REST server
Let's make @cescoffier happy !
N/A
#1296 
Two ways:
- curl localhost:10434/api/tags
- OLLAMA_HOST=127.0.0.1:10434 ollama ls
=> feat: implement list models in REST server

packages/backend/.gitignore
add generated source to gitignore file
=> fix: add generated source to gitignore file

yarn.lock
avoid potential CVE https://github.com/advisories/GHSA-952p-6rrq-rcjv
=> chore: fix micromatch dependency

packages/backend/src/managers/apiServer.spec.ts, packages/backend/src/managers/apiServer.ts
Fixes #1608
Restrict API server to local address
N/A
#1608 
Verify with a tool like tcpview64 (Windows) or netstat
=> fix: REST server to listen on local address

packages/backend/src/assets/inference-images.json
See https://github.com/containers/podman-desktop-extension-ai-lab/issues/1588#issuecomment-2321339768 for explanation
https://github.com/user-attachments/assets/3d790cb4-5471-4520-b1d8-fd3d733fd5b9
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1588
- assert have an nvidia GPU
- assert have experimental gpu enabled
- start an inference server
- in inference server logs see your gpu
=> fix: gpu acceleration windows

eslint.config.mjs, packages/backend/src/managers/modelsManager.spec.ts, packages/backend/src/utils/downloader.spec.ts, packages/frontend/src/lib/RecipeDetails.spec.ts, packages/frontend/src/lib/RecipeDetails.svelte, packages/frontend/src/lib/markdown/LinkComponent.svelte, packages/frontend/src/lib/notification/ContainerConnectionStatusInfo.spec.ts, packages/frontend/src/lib/notification/ContainerConnectionStatusInfo.svelte, packages/frontend/src/lib/table/model/ModelColumnActions.svelte, packages/frontend/src/lib/table/service/ServiceStatus.spec.ts, packages/frontend/src/lib/table/service/ServiceStatus.svelte, packages/frontend/src/pages/Dashboard.svelte, packages/frontend/src/pages/InferenceServerDetails.spec.ts, packages/frontend/src/pages/InferenceServerDetails.svelte, packages/frontend/src/pages/Playground.svelte, packages/frontend/src/pages/Recipe.spec.ts, packages/frontend/src/pages/Recipe.svelte, packages/frontend/src/stores/application-states.ts, packages/frontend/src/stores/catalog.ts, packages/frontend/src/stores/conversations.ts, packages/frontend/src/stores/extensionConfiguration.ts, packages/frontend/src/stores/modelsInfo.spec.ts, packages/frontend/src/stores/rpcReadable.spec.ts
Restore the ESLint no floating promise rule
N/A
N/A
`yarn lint:check`
=> chore: restore no floating promise rule

.github/workflows/e2e-main.yaml
* fixes linux build
N/A
#1680 
N/A
=> chore(ci): updating linux workflow

.github/workflows/e2e-main.yaml
This PR fixes the workflow for e2e-tests-main
#1692
=> chore: add package manage version to e2e-main.yaml file

eslint.config.mjs, packages/frontend/src/lib/RecipeDetails.spec.ts, packages/frontend/src/lib/RecipesCard.spec.ts, packages/frontend/src/lib/progress/TasksBanner.spec.ts, packages/frontend/src/pages/CreateService.spec.ts, packages/frontend/src/pages/InferenceServerDetails.spec.ts, packages/frontend/src/pages/InferenceServers.spec.ts, packages/frontend/src/pages/Models.spec.ts, packages/frontend/src/pages/Playgrounds.spec.ts, packages/frontend/src/pages/Recipe.spec.ts, packages/frontend/src/pages/Recipes.spec.ts, packages/frontend/src/pages/StartRecipe.spec.ts, packages/frontend/src/stores/modelsInfo.spec.ts, packages/frontend/src/utils/client.ts
Fixes #1700
Update code to comply with @typescript-eslint/no-explicit-any
N/A
#1700 
N/A
=> fix: handle ESLint rule @typescript-eslint/no-explicit-any

packages/frontend/src/lib/select/ContainerProviderConnectionSelect.svelte, packages/frontend/src/pages/StartRecipe.svelte
Fix errors raised during svelte-check update to 4.0.2
N/A
N/A
Check workflows or run `pnpm svelte-check`
=> fix: update svelte-check errors

pnpm-lock.yaml
it was containing invalid entries
PR checks
=> chore: fix pnpm lock file

eslint.config.mjs, packages/backend/src/utils/inferenceUtils.ts, packages/backend/src/workers/provider/LlamaCppPython.ts, packages/frontend/src/lib/table/model/ModelColumnName.svelte, packages/frontend/src/pages/CreateService.svelte, packages/frontend/src/pages/InferenceServerDetails.svelte, packages/frontend/src/pages/Model.svelte, packages/frontend/src/pages/Recipe.svelte, packages/shared/src/messages/MessageProxy.ts
Fixes #1701
Fix code for @typescript-eslint/prefer-nullish-coalescing rule
N/A
#1701 
`npm lint:check`
=> fix: handle ESLint rule @typescript-eslint/prefer-nullish-coalescing

eslint.config.mjs, packages/frontend/src/lib/table/playground/PlaygroundColumnIcon.svelte, packages/frontend/src/pages/Playgrounds.svelte
Fixes #1702
Update code for @typescript-eslint/no-empty-object-type rule
N/A
#1702 
Check workflows or run `pnpm lint:check`
=> fix: handle ESLint rule @typescript-eslint/no-empty-object-type

.github/workflows/ai-lab-e2e-nightly-windows.yaml
Updates link to podman5.json in e2e nightly windows test after podman extension file structure changes
=> fix: update path to podman5.json

packages/backend/src/utils/catalogUtils.spec.ts, packages/backend/src/utils/catalogUtils.ts
Fixes #1749
Update the catalog format detection routine as it did not cover all cases
N/A
#1749 
Have an old user catalog
=> fix: catalog conversion not handling all cases

packages/frontend/src/lib/notification/ContainerConnectionWrapper.svelte
Fixes #1754
Update GPU banner when Podman connection changes
N/A
#1754 
Have 2 Podman machine one Applehv one libkrun and check the GPU banner
=> fix: update GPU banner when Podman connection changes

packages/backend/src/managers/apiServer.ts
Update code for eslint-plugin-sonarjs 2.0.3
N/A
N/A
`npm lint:check`
=> fix:update for eslint-plugin-sonarjs 2.0.3

packages/backend/package.json, packages/backend/src/managers/modelsManager.spec.ts, packages/backend/src/registries/ConfigurationRegistry.spec.ts, packages/backend/src/registries/ConfigurationRegistry.ts, packages/backend/src/studio-api-impl.ts, packages/backend/src/workers/provider/LlamaCppPython.spec.ts, packages/frontend/src/lib/notification/ContainerConnectionWrapper.spec.ts, packages/frontend/src/pages/CreateService.spec.ts, packages/shared/src/StudioAPI.ts, packages/shared/src/models/IExtensionConfiguration.ts, pnpm-lock.yaml
Relates to #1591
Backend updates for GPU promotion banner
N/A
#1591 
`npm test:unit`
=> feat: add new settings for GPU promotion

packages/frontend/src/App.svelte, packages/frontend/src/lib/notification/GPUPromotion.spec.ts, packages/frontend/src/lib/notification/GPUPromotion.svelte
Fixes #1591
Add a new banner to all Podman AI Lab pages 
#1591
1. Make sure the GPU experimental flag is off
2. Navigate to one of the Podman AI Lab pages and check the banner is displayed
3. Verify banner disappear if one of the button is clicked
=> feat: add GPU banner to Podman AI Lab pages

packages/frontend/package.json, pnpm-lock.yaml
Fixes #1893
Switch vite-svelte-plugin to 4
N/A
#1893 
`npm build`
=> chore: update vite-svelte-plugin to 4

.github/workflows/ai-lab-e2e-nightly-windows.yaml
* Updates to new version of pde2e images
N/A
#1858
=> chore(ci): updating pde2e images versions

.github/workflows/ai-lab-e2e-nightly-windows.yaml
Fixes typo in `echo` command in win-workflow.
=> fix(ci): fix typo in ai-lab win workflow

packages/backend/src/assets/inference-images.json
Fixes #1867
Update inference server images reference
N/A
#1867 
Start inference server
=> fix: update inference server images

pnpm-lock.yaml
remove and add back pnpm-lock so we have latest dependencies from the package.json file
=> chore: refresh dependencies

.github/workflows/ai-lab-e2e-nightly-windows.yaml
* fixes destroy instance image
N/A
#1858 
N/A
=> chore(ci): fixing destroy instance image

packages/frontend/src/lib/notification/GPUPromotion.spec.ts, packages/frontend/src/lib/notification/GPUPromotion.svelte
Fixes #1915
Add telemetry to the new GPU promotion banner
N/A
#1915 
Run unit tests
=> fix: add telemetry for GPU promotion banner

packages/backend/src/assets/ai.json
Fixes #1911
Update catalog with latest version of the ai-lab-recipes 
N/A
#1911
Run recipes
=> fix: update catalog with latest ai-lab-recipes

packages/backend/src/assets/ai.json
Fixes #1911
This is a backport from main. Update the catalog
N/A
#1911
Start recipes
=> fix: update catalog with latest ai-lab-recipes (#1912)

.github/ISSUE_TEMPLATE/bug_report.yml
Add missing releases, and next one.
N/A
Fixes #1925.
Open a bug, after merging.
=> chore: update bug template

.husky/commit-msg, .husky/pre-commit, commitlint.config.js, package.json, pnpm-lock.yaml
First in a series of changes to enable Husky, conventional commits and lint staged for the project
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1633
```
touch test
git add test
git commit -m "a commit message that should fail"
git commit -m "chore: some test implementation"
```
=> chore: enable husky pre-commit tasks

.github/workflows/ai-lab-e2e-nightly-windows.yaml
* modifies nightly pipeline to build PD binary with ELECTRON_ENABLE_INSPECT=true
* uses built PD binary to run extension tests
N/A
#1762 
run the pipeline :D
=> chore(ci): modifying nightly workflow to build podman desktop with electron inspect enabled

packages/backend/src/assets/ai.json
backporting https://github.com/containers/podman-desktop-extension-ai-lab/pull/2024 to 1.3.X branch
=> feat: added lmstudio-comunity granite3 gguf model

packages/frontend/src/lib/RecipeCard.spec.ts, packages/frontend/src/lib/RecipeCard.svelte
Fixes #1980
Remove the local path from the recipe list
N/A
#1980 
Open the recipe catalog page
=> fix: remove path from recipe details

packages/frontend/src/lib/Navigation.svelte
Add dashboard menu entry
Fixes #2012
=> feat: add dashboard menu entry

tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-app-details-page.ts, tests/playwright/src/model/ai-lab-start-recipe-page.ts, tests/playwright/tsconfig.json
Disables Model uploading on Windows. It also changes a little recipes tested, RAG is quite heavy to stabilize, will not be tested now. It also includes a stabilization check for UI sync problem when starting the recipe.
#1762
#1870 
Build podman-desktop locally using `pnpm test:e2e:build`
Run the e2e tests from extension using `PODMAN_DESKTOP_ARGS=/path/to/podman/desktop; pnpm test:e2e`
=> chore(test): Stabilization of recipes on Windows CI

packages/backend/src/assets/ai.json
Fixes #2065
Update Granite 3.0 model properties
N/A
#2065 
Run the chatbot recipe against this model
=> fix: update chat format for Granite 3.0 model

package.json, pnpm-lock.yaml
=> chore: fix cve on semver

packages/backend/src/assets/ai.json
Add the `chatbot-java` recipe (created added via https://github.com/containers/ai-lab-recipes/pull/809) to the default recipe catalog
=> feat: Add the chatbot-java recipe

packages/backend/src/managers/application/applicationManager.spec.ts, packages/backend/src/managers/application/applicationManager.ts
Fixes #1899
Prevent double upload of the model into the Podman machine
N/A
#1899 
Run a recipe
=> fix: prevent double upload of model into Podman machine

.github/dependabot.yml
Group `@fortawesome/*` updates
=> chore(deps): group fortawesome

pnpm-lock.yaml
Update mergify conflicts
N/A
N/A
N/A
=> fix: fix merge conflicts

package.json, packages/backend/package.json, packages/frontend/package.json, pnpm-lock.yaml, tests/playwright/package.json
do not know why dependabot is not updating this dep
to update vite, we need this new dep
=> chore: update vitest to v2.1.8

tests/playwright/src/ai-lab-extension.spec.ts
creates e2e test that makes get call to model service to check for availability
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2100
=> chore(test): make get request to check model service availability

packages/backend/src/managers/apiServer.ts
this rule is no longer there in v3. remove its exclusion
related to https://github.com/containers/podman-desktop-extension-ai-lab/pull/2197
Signed-off-by: Florent Benoit <fbenoit@redhat.com>
=> chore: remove sonarjs rule

packages/backend/src/assets/ai.json
Fixes #2217
Update catalog to remove the extra duplicate Quarkus recipe
N/A
#2217
Display the recipe catalog and ensure the Quarkus chatbot recipe is here only once
=> fix: remove extra Quarkus recipe

pnpm-lock.yaml
=> fix: fix lock file

tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-navigation-bar.ts, tests/playwright/src/model/ai-lab-playground-details-page.ts, tests/playwright/src/model/ai-lab-playgrounds-page.ts
Create e2e tests for AI lab playground creation and deletion
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2101
=> chore(test): create playwground e2e test

packages/backend/src/assets/ai.json
Update the description of the recipes to more meaningful summaries.
https://github.com/containers/podman-desktop-extension-ai-lab/issues/919
=> fix: update recipes description

packages/backend/src/managers/gitManager.spec.ts
Refactor gitManager specs, to follow guideline https://github.com/podman-desktop/podman-desktop/blob/main/CODE-GUIDELINES.md#use-vimocked-not-a-generic-myfunctionmock
Tests only 
Run tests
=> refactor: do not use hoisted nor partial in gitManager specs

packages/backend/src/managers/catalogManager.spec.ts
refactor tests for catalogManager to mock node:fs, following guideline https://github.com/podman-desktop/podman-desktop/pull/10541
Tests only
Pre-requisite for #2326
Run tests
=> refactor: tests for catalogManager to mock node:fs

packages/backend/src/managers/catalogManager.spec.ts, packages/backend/src/managers/catalogManager.ts, packages/backend/src/tests/ai-test.json
Backend provides a method to filter recipes
Backend only
Part of #1299
Unit tests included
=> feat: filter recipes

packages/frontend/src/lib/conversation/SystemPromptBanner.svelte, tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-playground-details-page.ts
Adds additional playground e2e test
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2282
=> chore(test): add playground custom prompt e2e test case

packages/frontend/src/pages/StartRecipe.spec.ts
While trying to fix https://github.com/containers/podman-desktop-extension-ai-lab/issues/2363 I migrated the tests as it was hard to mock the stores.
Required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/2363
Pipeline should be green
=> refactor(tests): remove hoist from StartRecipe.spec.ts

packages/frontend/src/pages/CreateService.spec.ts
While trying to fix  https://github.com/containers/podman-desktop-extension-ai-lab/issues/2363 I migrated the tests as it was hard to mock the stores.
Required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/2363
- Pipeline should be green
=> refactor(tests): remove vi.hoisted from CreateService.spec.ts

packages/backend/src/extension.spec.ts
refactor extension specs to follow guideline https://github.com/podman-desktop/podman-desktop/blob/main/CODE-GUIDELINES.md#use-vimocked-not-a-generic-myfunctionmock
Tests only
Run tests
=> refactor: extension specs

tests/playwright/src/ai-lab-extension.spec.ts
Creates e2e test case for RAG Chatbot app deployment.
https://github.com/containers/podman-desktop-extension-ai-lab/issues/1872
=> chore(test): create rag chatbot e2e test case

.github/workflows/ai-lab-e2e-nightly-windows.yaml, .github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml
* Fixes artifacts path for e2e-main job
* removes .gguf and .bin models from uploaded artifacts
N/A
#2242 
N/A
=> Fix ai-lab test pipelines artifacts paths, exclude all models

.github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml
* Fixup of #2443 - incorrect paths
N/A
#2442 
N/A
=> chore(ci): follow-up incorrect model paths in e2e-main and pr-check

.github/workflows/ai-lab-e2e-nightly-windows.yaml
* Fixes issue with too many workflow dispatch arguments
N/A
N/A - adhoc
N/A
=> chore(ci): consolidating extension tests options

.github/workflows/ai-lab-e2e-nightly-windows.yaml, .github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml, tests/playwright/package.json, tests/playwright/src/ai-lab-extension.spec.ts
* Adds nightly linux e2e-main runs
* Enables tests on Linux GH Runner
* Increases viewport size for AI Lab tests
* Modifies and fixes smoke suite configuration
N/A
Closes #1500 
N/A
=> chore(test,ci): enable ai lab tests on GH ubuntu runner

tests/playwright/src/ai-lab-extension.spec.ts
Creates e2e test cases to AI lab suite that query the service model in order to validate functionality
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2410
=> chore(test): add e2e test to check model response

.github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml
* Adds JUnit report step to pipelines
Example of PR-Check report
Closes #2464 
N/A
=> chore(ci): publish junit reports for linux CIs

packages/frontend/src/pages/Playground.svelte
Migrates playground component to svelte5
Required for #2477
Unit tests
=> refactor(svelte5): migrated playground component to svelte5

packages/backend/src/assets/inference-images.json
Updates interference images
Required for https://github.com/containers/podman-desktop-extension-ai-lab/pull/2477
=> chore: updated interference images

pnpm-lock.yaml
remove duplicated entries from pnpm lock file
PR check failing
=> chore: fix package lock duplicated entries

packages/frontend/src/pages/Playground.svelte
Fixes #2544
Fix UI when GPU promotion banner is on and prompt input box after a few prompts
Before:
After:
#2544
1. Make sure GPU promotion banner
2. Create a playground
3. Check the prompt input box to be always available
=> fix: playground barely usable after a few prompts

eslint.config.mjs, packages/frontend/src/lib/markdown/LinkComponent.svelte, packages/frontend/src/lib/select/Select.svelte, packages/frontend/src/pages/CreateService.svelte, packages/frontend/src/pages/PlaygroundCreate.svelte, packages/frontend/src/pages/instructlab/AboutInstructLab.svelte
Fixes #2641
Enable svelte/no-useless-mustaches eslint rule
N/A
#2641
`pnpm lint:check`
=> chore: enable svelte/no-useless-mustaches eslint rule

packages/frontend/src/lib/Badge.svelte
Migrates Badge component to svelte5
Required for #2522
=> chore: migrated badge component to svelte5

packages/frontend/src/lib/Badge.spec.ts, packages/frontend/src/lib/Badge.svelte
Renames props in badge component
Required for #2522
=> chore: updated props in badge component

packages/backend/src/managers/apiServer.spec.ts, packages/backend/src/managers/apiServer.ts
Removes AI Lab listening port from statusbar
Closes #2543 
Run AI lab and see that the statusbar does not contain port item
=> chore: removes ai lab listening port item from statusbar

packages/backend/src/managers/apiServer.ts
Fixes #2678
Fixes API server so that digest for a model is always sent
N/A
#2678 
1. Start AI Lab
2. Download hf.MaziyarPanahi.Mistral-7B-Instruct-v0.3.Q4_K_M
3. run `OLLAMA_HOST=localhost:10434 ollama ps`
=> fix: always sent digest for a model

packages/backend/src/managers/apiServer.ts
fix: use nullish coalescing operator
N/A
N/A
`pnpm lint:check`
=> fix: use nullish coalescing operator 

.github/workflows/build-next.yaml, .github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml, .github/workflows/release.yaml, package.json, packages/backend/package.json, pnpm-lock.yaml, tests/playwright/package.json
electron v35 depends on Node.js v22
https://github.com/containers/podman-desktop-extension-ai-lab/pull/2637
=> chore: update to Node.js v22 and electron v35

eslint.config.mjs
Enable `svelte/infinite-reactive-loop` eslint rule
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2643
Requires rebase after
- https://github.com/containers/podman-desktop-extension-ai-lab/pull/2666
- https://github.com/containers/podman-desktop-extension-ai-lab/pull/2667
=> chore(eslint): enable svelte/infinite-reactive-loop

packages/frontend/src/pages/Recipes.spec.ts, packages/frontend/src/pages/Recipes.svelte
Adds contribution message and a button that links to the page
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2105
=> feat: added contribution message and link to page

packages/frontend/src/stores/rpcReadable.ts
fix: use null coalescing operator
=> fix: use null coalescing operator

packages/backend/package.json, packages/backend/src/models/HuggingFaceModelHandler.spec.ts, packages/backend/src/models/HuggingFaceModelHandler.ts, packages/backend/src/studio.ts, pnpm-lock.yaml
Fixes #2734
Add a new model handler for downloaded models from HuggingFace
#2734 
Add the following snippet in your user catalog:
```
{
"id": "openvino-mistral-7b-instruct-v0.2-int8-ov",
"name": "openvino-mistral-7b-instruct-v0.2-int8-ov",
"description": "OpenVINO/mistral-7b-instruct-v0.2-int8-ov",
"url": "huggingface:/OpenVINO/mistral-7b-instruct-v0.2-int8-ov",
"backend": "openvino"
}
```
- Verify it appears in the model list
- Verify it can be downloaded/deleted
- Verify an inference server cannot be started
=> feat: add HuggingFace model handler

.github/ISSUE_TEMPLATE/UX issue template
This PR is to create a new issue template for UX issues
=> chore: create ux issue template

packages/backend/src/managers/TaskRunner.spec.ts, packages/backend/src/managers/TaskRunner.ts, packages/backend/src/managers/inference/inferenceManager.spec.ts, packages/backend/src/managers/inference/inferenceManager.ts, packages/backend/src/models/TaskRunner.ts
Add failFastSubtasks to TaskRunner and refactor inferenceManager
N/A
Part of #2628 
Start inference services
=> refactor: add failFastSubtasks to TaskRunner and refactor inferenceManager

packages/backend/src/assets/inference-images.json
Use newer sha images
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2868
=> fix: use sha that is available for RamaLama images

packages/frontend/src/lib/ContentDetailsLayout.svelte, packages/frontend/src/lib/ContentDetailsLayoutTest.svelte, packages/frontend/src/pages/Playground.svelte, packages/frontend/src/pages/Recipe.svelte
Adds a hover tooltip for more info when panel is closed
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/841
pnpm watch
=> feat: added tooltip for more info for hidden panel

packages/backend/package.json, packages/backend/src/managers/playground/aiSdk.spec.ts, packages/backend/src/managers/playground/aiSdk.ts, packages/backend/src/managers/playgroundV2Manager.spec.ts, packages/backend/src/managers/playgroundV2Manager.ts, pnpm-lock.yaml
This is a work in progress (WIP)
Initial refactor to support tool/function calling by using [Vercel ai-adk](https://sdk.vercel.ai/docs/introduction) which supports it.
Fixes #2883
1. Run a model
2. Create a playground
3. Send a prompt
4. Model is able to respond with the pompt
5. Create a new playground
6. Set a system prompt (e.g. "You are an AI assistant named Marvin")
7. Send a prompt with a question related to the system prompt (e.g. "Who are you?" "What's your name?")
8. Model responds with the appropriate name
9. Create a new playground
10. Send a prompt
11. Press the stop button before the model completes the chat
12. The chat is stopped, the user is able to send a new prompt to the model
=> feat: replace OpenAI with Vercel AI SDK

tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-local-server-page.ts, tests/playwright/src/model/ai-lab-navigation-bar.ts
Adds e2e tests for API endpoints.
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2558
=> chore(test): api endpoints e2e test

packages/backend/src/assets/llama-stack-images.json
Fixes #2872
Update Podman AI Lab llama-stack distribution
N/A
#2872 
1. Create a libkrun machine
2. Start llama-stack on this machine
=> fix: add ARM64 to Podman AI Lab llama-stack distribution

packages/frontend/src/pages/Playground.spec.ts, packages/frontend/src/pages/Playground.svelte
The tests were not covering the scenario where the server return an error, and this error was provided to the playground.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2960
**Manually**
This problem can be easily reproduced with a NVIDIA GPU.
1. assert you have an NVIDIA card
2. checkout https://github.com/containers/podman-desktop-extension-ai-lab/pull/2949
3. start Podman Desktop & AI Lab
4. assert GPU enabled
5. start playground with `ibm-research/granite-3.2-8b-instruct-GGUF`
6. talk in the chat
7. assert error from the screenshot above
=> fix(ui): playground `state_unsafe_mutation`

pnpm-lock.yaml
Update broken lock file 
N/A
N/A
Check workflows
=> chore: fix broken lockfile

packages/frontend/src/lib/conversation/ChatMessage.svelte, tests/playwright/package.json, tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-playground-details-page.ts
Extends the playground E2E test
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2560
=> chore(test): Extend playground test

packages/frontend/src/lib/table/playground/PlaygroundColumnRuntime.spec.ts, packages/frontend/src/lib/table/playground/PlaygroundColumnRuntime.svelte, packages/frontend/src/pages/Playground.spec.ts, packages/frontend/src/pages/Playgrounds.svelte, packages/frontend/src/stores/conversations.ts, packages/shared/src/models/IInference.spec.ts, packages/shared/src/models/IInference.ts
Display runtime for playgrounds
Part of #2614
Start playground and check that the runtime is correctly displayed
=> feat: display runtime for playgrounds

packages/frontend/src/pages/NewInstructLabSession.svelte
fix: use $derived instead of writable state
N/A
N/A
=> build(deps-dev): bump eslint-plugin-svelte from 3.5.1 to 3.6.0

packages/backend/src/assets/ai.json
Adds the new agent recipe to the catalog
fixes https://github.com/containers/ai-lab-recipes/issues/807
install ai lab extension
go to recipe catalog and start new ReAct Agent Application
(You will need a Spotify client API key and secret to test this!!) But it works!
=> feat: add ReAct agent recipe to the catalog

packages/backend/src/managers/apiServer.ts
Fixes #3026
Update api server to be compatible with OpenVINO models
N/A
#3026
Use an OpenVINO model from the llama-stack playground or using the ollama client
=> fix: api server not compatible with OpenVINO models

tests/playwright/playwright.config.ts, tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-catalog-page.ts, tests/playwright/src/model/ai-lab-dashboard-page.ts, tests/playwright/src/model/ai-lab-model-service-page.ts, tests/playwright/src/model/ai-lab-navigation-bar.ts, tests/playwright/src/model/ai-lab-playground-details-page.ts, tests/playwright/src/model/ai-lab-playgrounds-page.ts, tests/playwright/src/model/ai-lab-running-apps-page.ts, tests/playwright/src/model/ai-lab-service-details-page.ts, tests/playwright/src/model/ai-lab-start-recipe-page.ts, tests/playwright/src/model/podman-extension-ai-lab-details-page.ts, tests/playwright/src/model/preferences-extension-ai-lab-page.ts, tests/playwright/src/utils/aiLabHandler.ts, tests/playwright/src/utils/webviewHandler.ts
* Refactors and simplifies a lot of test logic
N/A
#1932 requirement
N/A
=> chore(test): simplifying and extracting test logic, refactor

tests/playwright/src/model/ai-lab-playground-details-page.ts
Increases a timeout for locator in the playground e2e test
=> chore(test): fix playground e2e test

package.json, pnpm-lock.yaml
Switch to vite 7.0.0
N/A
N/A
Check workflows
=> chore: switch to vite 7.0.0

tests/playwright/src/ai-lab-extension.spec.ts
skips Object Detection app installation on Windows and Linux CI
=> chore(test): skip Object Detection app install on Windows and Linux CI

.github/workflows/llama-stack-playground.yaml
Fixes #3027
Adds a new workflow for creating a new llama-stack playground image
N/A
#3027
N/A
=> chore: add llama-stack-playground

tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-try-instructlab-page.ts
Attempts to fix some flakyness issues with instruct lab e2e tests.
=> chore(test): better handling for race conditions

.github/workflows/e2e-main.yaml, .github/workflows/pr-check.yaml, .github/workflows/ramalama.yaml
Fixed problem with packages installation on ubuntu.
[[#13174 ](https://github.com/podman-desktop/podman-desktop/pull/13175)](https://github.com/podman-desktop/podman-desktop/issues/13174)
=> fix(ci): perform update of ubuntu packages earlier

.github/workflows/ai-lab-e2e-nightly-windows.yaml, .github/workflows/recipe-catalog-change-template.yaml
=> chore(ci): fixup - fix mapt default version in params string

packages/frontend/src/pages/Models.svelte, packages/frontend/src/pages/Recipes.svelte
fix: use SvelteSet and SvelteMap
N/A
#3319
Run unit tests
=> fix: use SvelteSet and SvelteMap

tests/playwright/src/ai-lab-extension.spec.ts
* Updates and extends playground test scope to most frequently used models
#2420
=> chore(test): extend playground test scope and align with Amplitude

tests/playwright/src/ai-lab-extension.spec.ts, tests/playwright/src/model/ai-lab-catalog-page.ts
* Fixes model deletion logic
* Removes Playground-incompatible models that keep breaking out of instruct template
#2420
pr-check
=> Fix playground tests, system out of storage errors

.github/workflows/ai-lab-e2e-nightly-windows.yaml, .github/workflows/recipe-catalog-change-template.yaml
* Fixes excluded regions parsing
* Updated default MAPT to 0.9.7
https://github.com/podman-desktop/e2e/issues/437
=> chore(ci): fix excluded regions parsing, update MAPT defaults to 0.9.7

package.json, packages/backend/package.json, packages/backend/src/managers/playground/aiSdk.spec.ts, packages/backend/src/managers/playground/aiSdk.ts, packages/backend/src/managers/playgroundV2Manager.spec.ts, packages/shared/src/models/McpSettings.ts, pnpm-lock.yaml
This pr aims to migrate ai to 5.0 and update all co dependent packages along with this. A pretty big portion of the api code had to be changed as well and i got a lot of help from cursor with claude-sonnet. 
Fixed tests and tested locally as well
Fixes: https://github.com/containers/podman-desktop-extension-ai-lab/issues/3551
try creating llamastack containers and start a chat
that should go through most of the api calls
start a playground and interact with it too
=> chore: migrate to ai v5 and update relevant code 

.github/workflows/e2e-main.yaml
* Fixes incorrect description and use of the pipeline parameters
https://github.com/containers/podman-desktop-extension-ai-lab/issues/3701
=> chore(ci,hotfix): fixing main pipeline checkout steps and args
