- packages/backend/src/studio.spec.ts
- packages/backend/vitest.config.js
- packages/shared/MessageProxy.spec.ts
- packages/shared/MessageProxy.ts
This PR is adding some basic tests for the MessageProxy 
> Currently the tests in `src/studio.spec.ts` are failing
> tests: adding tests for MessageProxy

- packages/frontend/src/lib/MarkdownRenderer.svelte
- packages/frontend/src/lib/markdown/LinkComponent.svelte
- packages/frontend/src/lib/markdown/MarkdownRenderer.svelte
- packages/frontend/src/pages/Model.svelte
- packages/frontend/src/pages/Recipe.svelte
Related to #36 
Depends on https://github.com/projectatomic/studio-extension/pull/63
The markdown displayed has links, that messes with the webview routing system. Creating custom renderer for Link objects and opening externally the links when clicked.
> fix: markdown broken links

- docs/proposals/state-management.md
This is a proposal on how to manage the different states in AI Studio:
- catalog
- pulled applications
- errors
- etc
(as an example, the management of the state of the kube contexts in Podman Desktop is implemented in a similar way, in PR https://github.com/containers/podman-desktop/pull/5329).
> doc: State management proposal

- package.json
- packages/backend/src/studio.spec.ts
- packages/backend/tsconfig.json
- packages/shared/tsconfig.json
- types/podman-desktop-api.d.ts
- yarn.lock
shared package has an issue.
shared module should not depends on 'web' library
because backend importing these classes is a pure Node.JS module
so some classes of shared should be only on frontend
fix a test returning a string and not a promise
> chore: some workaround for podman-desktop/api

- packages/backend/src/ai-user-test.json
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/shared/src/models/ICatalog.ts
A default catalog is provided with the extension. The user can provide its own catalog (in ~/podman-desktop/ai-studio/catalog.json). If the user's file is valid, it will be used. Otherwise, the default catalog will be used.
For now, changes on the user's file are not detected.
Fixes partially #32
> Load user catalog if file exists or use default one

- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
- packages/frontend/src/lib/RecipesCard.svelte
- packages/frontend/src/pages/Model.spec.ts
- packages/frontend/src/pages/Model.svelte
- packages/frontend/src/pages/Recipe.spec.ts
- packages/frontend/src/pages/Recipe.svelte
- packages/frontend/src/pages/RecipeModels.svelte
- packages/frontend/src/pages/Recipes.svelte
- packages/frontend/src/stores/catalog.ts
- packages/shared/Messages.ts
- packages/shared/src/StudioAPI.ts
This PR replaces the different RPCs to a synchro of the catalog between backend and frontend. 
The frontend now knows the frontend structure and can make requests on it.
If the structure of the catalog becomes complex in the future, we will probably want to provide a Catalog class on the frontend to centralize the logic, or add stores derived from the `catalog` one.
TODO
> push the catalog to the frontend and use a store on frontend

- packages/backend/src/managers/playground.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/Card.svelte
- packages/frontend/src/pages/ModelPlayground.spec.ts
- packages/frontend/src/pages/ModelPlayground.svelte
- packages/frontend/src/stores/playground-queries.ts
- packages/frontend/src/stores/playground-states.ts
- packages/shared/Messages.ts
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/IPlaygroundQueryState.ts
- packages/shared/src/models/IPlaygroundState.ts
Fixes https://github.com/projectatomic/studio-extension/issues/20
> feat: adding support for starting / stopping playground

- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/registries/RecipeStatusRegistry.ts
- packages/backend/src/registries/TaskRegistry.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/pages/Models.svelte
- packages/frontend/src/pages/Recipe.spec.ts
- packages/frontend/src/pages/Recipe.svelte
- packages/frontend/src/stores/recipe.ts
- packages/shared/Messages.ts
- packages/shared/src/StudioAPI.ts
The polling from the frontend of the tasks is replaced by pushing them from the backend.
> send application tasks to frontend when updated

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/vitest.config.js
> Do not download model again

- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
> fix: getLocalModels returns an empty array if the models folder does not exist

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
- packages/frontend/src/stores/local-models.ts
- packages/shared/Messages.ts
This PR makes the extension watch the folder containing the models, and updates the UI accordingly.
Fixes #116
> watch local models

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/models/AIConfig.ts
- packages/backend/src/utils/ports.ts
- packages/frontend/src/lib/table/model/ModelColumnCreation.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnSize.spec.ts
- packages/shared/src/models/ILocalModelInfo.ts
This PR adds an additional step to the pullApplication action - it creates a pod with the 2 containers.
It doesn't get started yet, i'm going to work on it on a follow-up PR but it can be start manually from the pod/container page of desktop.
EVentually you should see the green check on create application
and a new pod similar to
If you start it you would probably see it fail because the modelservice is slow at loading the model and the sample app when trying to connect to the model service it fails.
So what you can do is 
1. start the pod
2. the model service container should appear green
3. check the logs and wait until you see it is completely loaded and running (e.g there should be http://localhost:7860 url message)
4. start the sample app container 
5. now you can open it on the …
> feat: create pod with sample app and model services after build is completed (#90)

- packages/backend/src/managers/playground.ts
> fix: use playground image based on llama-cpp-python

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
this patch allows to delete the container that is outside the pod after the creation + copy into the pod is complete.
it resolves #159
> fix: delete containers outside the pod

- packages/backend/src/ai.json
- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/gitManager.spec.ts
- packages/backend/src/managers/gitManager.ts
- packages/shared/src/models/IRecipe.ts
This PR adds the ref property so that we can checkout the specific branch/commit. 
A valid ref can be a SHA1 tag or a branch name
it resolves #142
> fix: add ref to catalog entries

- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/shared/src/StudioAPI.ts
This PR adds a `getModelsDirectory`, which expose the path where all the models are stored.
In a follow-up PR, the goal is to show this path in the Model lists. Without having to depends on `getLocalModels` which could return `[]`.
> feat: expose models directory in the api

- packages/backend/src/managers/playground.ts
Fixes https://github.com/projectatomic/ai-studio/issues/195
> fix: sendQueriesState not async

- packages/backend/src/managers/playground.ts
- packages/frontend/src/lib/ErrorMessage.svelte
- packages/frontend/src/pages/ModelPlayground.spec.ts
- packages/frontend/src/pages/ModelPlayground.svelte
- packages/shared/src/models/IPlaygroundQueryState.ts
Propagate the http request error to the frontend so the user can have a "sense" of what is happening
https://github.com/projectatomic/ai-studio/assets/42176370/ab3251b1-92bd-422b-99b7-bea50e9a3e2e
> The `inProgress` of the demo has been removed, it is not part of the PR as it was a test.
Fixes https://github.com/projectatomic/ai-studio/issues/186
> feat: playground error propagation

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
This is just a refactor. I moved the functions + tests related to downloading the model from the applicationManager to modelsManager.
It resolves #133
> refactor: move downloadModels function into modelsManager (#133)

- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/managers/playground.spec.ts
> unit tests for playground manager

- packages/backend/src/managers/playground.spec.ts
- packages/backend/src/managers/playground.ts
- packages/backend/src/registries/ContainerRegistry.spec.ts
- packages/backend/src/registries/ContainerRegistry.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
This PR add a `ContainerRegistry`, is purpose is to listen to containers events emitted by the PodmanDesktop core, such as `die | remove | start` etc.
This registry allow the playground to subscribe to the notification of a certain containerId (the one it created) so if something external is deleting the containers, the playgrounds will know it. 
https://github.com/projectatomic/ai-studio/assets/42176370/e7b34f79-7d50-4be7-999d-0cc913f45067
Fixes https://github.com/projectatomic/ai-studio/issues/110
> feat: listen to podman desktop container api events

- packages/frontend/src/lib/button/Button.spec.ts
- packages/frontend/src/lib/button/Button.svelte
Fixe Button svelte component to have proper spinner when progress true
https://github.com/projectatomic/ai-studio/assets/42176370/b3d4adca-bea6-4fa7-a192-70e370b0a4d4
Fixes https://github.com/projectatomic/ai-studio/issues/188
> fix: button must have a spinner when progress true

- packages/backend/package.json
- packages/backend/src/managers/playground.spec.ts
- packages/backend/src/managers/playground.ts
- packages/backend/src/managers/podmanConnection.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
This PR adds a new class `PodmanConnection`, whose instance listens for new/updated 'podman' container providers, so other managers can get informed of new containers and adopt some of them depending on their labels.
It is used as part of this PR for adopting playground containers.
It is expected to be used to detect and adopt recipe pods in a future PR.
Fixes #57
> adopt playground containers

- packages/backend/package.json
- packages/backend/src/managers/playground.ts
- packages/frontend/src/pages/ModelPlayground.svelte
- packages/shared/src/models/IModelResponse.ts
- yarn.lock
Fixes #23
Use streaming when sending requests to the playground
#23
Just play with the playground
> feat: use streaming in playground requests

- packages/backend/src/managers/playground.spec.ts
- packages/backend/src/managers/playground.ts
Fixes #147
Wait until the playground container is properly initialized
N/A
Fixes #147 
Start a playground
> fix: wait until playground is initialized

- packages/shared/src/messages/MessageProxy.spec.ts
- packages/shared/src/messages/MessageProxy.ts
This PR is fixing the error propagation between the front and back. The errors was not properly sent between the processes, and was raison `Received incompatible message.`.
Fixes https://github.com/projectatomic/ai-studio/issues/216
> fix: properly set error status on messages when catching an api error

- packages/backend/src/managers/playground.spec.ts
- packages/backend/src/managers/playground.ts
- packages/backend/src/managers/podmanConnection.spec.ts
- packages/backend/src/managers/podmanConnection.ts
- packages/backend/src/studio.spec.ts
This PR makes AI Studio listen for podman machine stop, so the playground are declared as non running when this happens.
Fixes #215 
Stopping the machine from the CLI (podman machine stop) is not detected by AI Studio, as Podman Desktop does not send event for this (issue https://github.com/containers/podman-desktop/issues/5842).
On Mac, Windows only (not Linux)
- Start a playground container
- Stop the podman machine (from the GUI)
- Check that the playground is marked as not running on the Playground page
> feat: listen podman machine stop to mark playgrounds as stopped

- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/table/model/ModelColumnActions.svelte
- packages/shared/src/StudioAPI.ts
Uses the Podman-Desktop provided modals instead of custom one.
https://github.com/projectatomic/ai-studio/assets/42176370/4e51ed2d-cb17-4ead-a856-76e4c14c7bdc
Fixes https://github.com/projectatomic/ai-studio/issues/203
> feat: using podman-desktop modals instead of custom one

- packages/backend/package.json
- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/environmentManager.spec.ts
- packages/backend/src/managers/environmentManager.ts
- packages/backend/src/managers/podmanConnection.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/lib/table/environment/ColumnName.svelte
- packages/frontend/src/pages/Environments.svelte
- packages/frontend/src/stores/environment-states.ts
- packages/shared/Messages.ts
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/IEnvironmentState.ts
- yarn.lock
Lists the running environments, based on the running pods with appropriate labels.
For now, only the id of the recipe is displayed, more to come...
Only the operations on podman machines from the GUI are detected (see issue https://github.com/containers/podman-desktop/issues/5842)
Fixes #178, #179
- pull an application for a recipe
- check the recipe ID is listed in the Environments page
- Stop or delete the pod created for the app from the GUI or CLI
- check the recipe ID disappears from the environments list
- stop te podman engine from the GUI
- check the recipe ID disappears from the environments list
- restart the podman machine (from GUI) and restart the pod (from GUI or CLI)
- check the recipe ID is listed in the Environments page
- reload the AI studio extension
- check the recipe …
> feat: display environments list based on running pods

- packages/frontend/src/pages/ModelPlayground.spec.ts
- packages/frontend/src/pages/ModelPlayground.svelte
Adding catch block for methods related to playground actions (start/stop)
Fixes https://github.com/projectatomic/ai-studio/issues/255
> fix: uncaught errors in ModelPlayground

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/managers/playground.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/table/model/ModelColumnActions.svelte
- packages/frontend/src/lib/table/model/ModelColumnCreation.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnSize.spec.ts
- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/Models.svelte
- packages/frontend/src/stores/local-models.ts
- packages/frontend/src/stores/modelsInfo.ts
- packages/shared/Messages.ts
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/ILocalModelInfo.ts
Fixes #43
Display all models from the catalog in the models page. If the model is not downloaded, existing actions are disabled. Goal is to allow new actions (download,...) in the future
#43 
Go to the Models page
> feat: display all models in the models page

- packages/frontend/src/lib/RecipeDetails.svelte
- packages/frontend/src/lib/markdown/LinkComponent.svelte
- packages/frontend/src/lib/progress/TasksProgress.svelte
- packages/frontend/src/lib/table/Table.svelte
- packages/frontend/src/pages/Recipe.svelte
- packages/frontend/src/pages/RecipeModels.svelte
Make the recipe page responsive. The Recipe/Application details will be placed on top on the `README.md` when the window size will reach a size of `1024px`. _(Ref https://tailwindcss.com/docs/responsive-design)_.
> The models tabs is a bit weird looking when the size is very small, the table itself is responsible of that behaviour, so we probably want **later** to improve the table component.
https://github.com/projectatomic/ai-studio/assets/42176370/dc2ecb57-7809-434d-83be-08f3fbaf81e4
Fixes https://github.com/projectatomic/ai-studio/issues/258
- (1) Open any recipe
- (2) Make the window size vary
> feat: recipe page responsive design

- packages/frontend/src/stores/local-models.spec.ts
- packages/frontend/src/stores/modelsInfo.spec.ts
- packages/frontend/src/stores/modelsInfo.ts
- packages/frontend/src/stores/rpcReadable.spec.ts
- packages/frontend/src/stores/rpcReadable.ts
This PR adds the event-store class so we can share some common code between stores.
N/A
N/A
1. run tests or start studio and check that everything works as before. Only the recipe store has been updated for the moment
> feat: create custom Readable to share stores logic

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/environmentManager.spec.ts
- packages/backend/src/managers/environmentManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/lib/table/environment/ColumnActions.svelte
- packages/shared/src/StudioAPI.ts
Add a button to restart an environment from the Environments page, using the new source code
https://github.com/projectatomic/ai-studio/assets/9973512/5ab2f616-974a-4bc9-b7e6-aa1d24717271
Fixes #180 
- start an app from the recipe page
- go to Environments page
- click Restart button, the pod should be deleted and recreated
- modify sources of application and/ model service
- click Restart button, the pod should be deleted and recreated, using the new source code
> Restart environment

- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/shared/src/models/ILocalModelInfo.ts
Wrapping the `fs.statSync` in a try catch to avoid the `Error: EPERM: operation not permitted` issue appearing when the models is being used (mounted).
This method was used to check the size and the creation date of the file, those field are made optional by this PR, as we still want to show the modes is on disk, but with less information, as we cannot get those.
Fixes https://github.com/projectatomic/ai-studio/issues/303
> fix: loadLocalModels issue when models being used

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/RecipesCard.svelte
- packages/frontend/src/lib/table/model/ModelColumnName.svelte
Tinro is a bit annoying with certain scenario. When working on https://github.com/projectatomic/ai-studio/issues/332 I had the issue of having multiple route resolved when I was not suppose too.
To avoid certain issue in the future, I renamed the following routes 
- model details from `/models/:id/*` to `/model/:id/*`
- recipe details from `/recipes/:id/*` to `/recipe/:id/*`
- Explore the application, click on tables to ensure no 404
> feat: renaming route paths

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/registries/RecipeStatusRegistry.spec.ts
- packages/backend/src/registries/RecipeStatusRegistry.ts
- packages/backend/src/registries/TaskRegistry.ts
- packages/backend/src/studio.ts
- packages/backend/src/utils/downloader.ts
- packages/frontend/src/stores/recipe.ts
- packages/shared/Messages.ts
Part of https://github.com/projectatomic/ai-studio/issues/339
Fixes https://github.com/projectatomic/ai-studio/issues/336
- Existing tests ensure no regression
> chore: remove the dependency of download task to the RecipeStatusUtils

- packages/backend/src/managers/catalogManager.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/managers/podmanConnection.ts
- packages/backend/src/studio.ts
Making some Managers implements Disposable so they can be registered to call `dispose()` when the extension is disabled
Fixes https://github.com/projectatomic/ai-studio/issues/341
> feat: dispose extension resources on deactivate 

- packages/frontend/src/lib/RecipeDetails.spec.ts
- packages/frontend/src/lib/RecipeDetails.svelte
In https://github.com/projectatomic/ai-studio/pull/333 I forget to rename the path used in the RecipeDetails component.
- (1) Open a recipe page
- (2) click on the list models item
> fix: wrong path used for recipe redirect

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/registries/LocalRepositoryRegistry.spec.ts
- packages/backend/src/registries/LocalRepositoryRegistry.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/stores/localRepositories.ts
- packages/shared/Messages.ts
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/ILocalRepository.ts
Simply add a store containing the information of where are stored the checkout repository. This store will be required to be able to have https://github.com/projectatomic/ai-studio/issues/27
> This store could be used in the future for https://github.com/projectatomic/ai-studio/issues/234
Fixes https://github.com/projectatomic/ai-studio/issues/250
> feat: adding LocalRepositoryRegistry

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/EnvironmentActions.svelte
- packages/frontend/src/lib/RecipeDetails.svelte
- packages/frontend/src/lib/table/environment/ColumnStatus.spec.ts
- packages/frontend/src/lib/table/environment/ColumnStatus.svelte
- application being deployed and extension restarted: because AI Studio manages the restart of the app container, the pod is not ok, it needs to be deleted by user => This deletion is correctly supported and the Play button is enabled again. 
- application deployed and correctly running, and extension restarted => the status "Pod running" is displayed in the Environments page and the pod name is displayed in the "Application Details" block. 
- application being deployed or correctly running, and the pod is deleted manually => tasks cleared and replaced by a single 'Pod deleted manually', visible in "Application Details" (not in Environments, as the line has been deleted)
- replaced delete with stop button
- matching pod is deleted before to start a new one
- handle pod stopped manually
- …
> support extension restart and manual deletion of pod

- packages/frontend/src/pages/ModelPlayground.spec.ts
- packages/frontend/src/pages/ModelPlayground.svelte
Fixes #53
Add elapsed time in the playground UI
#53
Launch the playground for a model and execute a request
> feat: display execution time in the playground

- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/Models.svelte
- packages/frontend/src/stores/recipe.ts
- packages/frontend/src/stores/tasks.ts
- packages/shared/src/StudioAPI.ts
Instead of gettings the tasks from the RecipeState stores, we fetch them directly from a new Tasks store. 
Part of https://github.com/projectatomic/ai-studio/issues/339
> This is necessary as we want to be able to download models outside of a recipe (for the playground, from the tables etc.)
Fixes https://github.com/projectatomic/ai-studio/issues/343
- Previous tests ensure no regression
> feature: adding tasks store for models page

- packages/frontend/src/lib/table/environment/ColumnAge.svelte
- packages/frontend/src/lib/table/environment/ColumnModel.spec.ts
- packages/frontend/src/lib/table/environment/ColumnModel.svelte
- packages/frontend/src/lib/table/environment/ColumnPod.svelte
- packages/frontend/src/lib/table/environment/ColumnRecipe.spec.ts
- packages/frontend/src/lib/table/environment/ColumnRecipe.svelte
- packages/frontend/src/lib/table/environment/ColumnStatus.svelte
- packages/frontend/src/pages/Environments.svelte
Add columns "Recipe", "Model", "Pod", "Age" to the Environments page
Fixes #235
> Design Environments page

- packages/frontend/src/lib/table/model/ModelColumnActions.svelte
- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/Models.svelte
Add tabs to the model page : All - Downloaded - Available 
> This allow to add a clear distinction between the models locally and available to download
This PR also hide completely the actions when the model is not on disk.
https://github.com/projectatomic/ai-studio/assets/42176370/35db5d46-a4a0-4e0a-848a-90b46c04179a
Fixes https://github.com/projectatomic/ai-studio/issues/332
> feat: splitting models page

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
This patch changes how the app is considered running. 
Bc of the proposals made by Jeff, we are moving to cloud native built applications that should restart themself if the model service is not ready https://github.com/redhat-et/locallm/pull/41 and we are goingto use the readiness probe to check if a container is running succesfully.
So, if we do not find any probe in the ai-studio (as it is now, we still have to add the health check), if all containers in a pod are running, the app is considered ready.
N/A
it is part of the catalog update to use the new streamlit apps #262 
1. run the chatbot app, you should see the app is running when both containers are actually running. If you open the browser, you will see the sample app ready. If you ask a question it will fail as the model service …
> fix: consider app running if containers are running

- packages/backend/src/managers/applicationManager.ts
Fixes #394 
Start and stop applications several times by clcking the Start/Stop buttons in Recipe page, the status 'Application stopped manually' should never appear
> fix: do not display stopped manually when stopped by AI Studio

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/playground.ts
- packages/backend/src/models/AIConfig.spec.ts
- packages/backend/src/models/AIConfig.ts
Adds labels to the application's pod giving the ports of the model and app, so the Environments manager can know them.
As part of #61 
Start an application with ai-studio.yaml containing ports information for model and/or app, and check the labels exist in the pod
> feat: add labels with model and app ports

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/frontend/src/lib/table/environment/ColumnModel.spec.ts
- packages/frontend/src/lib/table/environment/ColumnModel.svelte
- packages/frontend/src/lib/table/environment/ColumnRecipe.spec.ts
- packages/frontend/src/lib/table/environment/ColumnRecipe.svelte
- packages/frontend/src/pages/Environments.svelte
- packages/frontend/src/utils/printers.ts
- packages/shared/src/models/IEnvironmentState.ts
Display the port(s) of the model and app, in the Environments page
(the link(s) to the app page will be done in another PR)
Part of #61
Start an application and check that the ports defined in the ai-studio.yaml match the ones displayed in the Environments page
> feat: display model and app ports in Environment page

- packages/frontend/src/lib/table/environment/ColumnRecipe.spec.ts
- packages/frontend/src/lib/table/environment/ColumnRecipe.svelte
Adds buttons (one for each port defined in ai-studio.yaml) to open the application on the browser.
Fixes #61 
Start an application, go to Environements page, and click on the icon near the Recipe name, it should open the app page
> feat: display icon to open AI App on browser

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
Fixes #428
Reset the state if checkout is failing
#294
1. Remove Git repo from $HOME/podman-desktop/ai-studio
2. In the catalog change the git repo or git reference to an invalid value for a recipe
3. Start AI App for that recipe
> fix: report error and reset state if checkout fails

- PACKAGING-GUIDE.md
it updates the doc to mention the `version` property, now used by the ai-studio files -> https://github.com/redhat-et/locallm/pull/59
N/A
it resolves #59 
N/A
> docs: mention version property in ai-studio file (#59)

- packages/backend/src/managers/playground.spec.ts
- packages/backend/src/managers/playground.ts
Send to the telemetry the total duration of a response in the playground.
Fixes #35
> chore: send response total duration to telemetry

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/registries/TaskRegistry.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/utils/downloader.ts
- packages/frontend/src/pages/Models.svelte
When we start a model download in the models Table, we have an issue when starting the application, where it detects the models already being on disk (in reality it is **partially** on disk) and it skip the step, when it should not.
Now, when requesting to download a model, the system will check for existing downloader and tasks. Avoiding potential errors.
https://github.com/projectatomic/ai-studio/assets/42176370/4d068def-8323-40bb-a905-dc52a5d03e3a
Fixes https://github.com/projectatomic/ai-studio/issues/384
(1) Go to models table 
(2) Download a model
(3) Go to any recipe that can use this model
(4) Click on "Start application"
> feat: reuse existing model downloading tasks

- packages/backend/src/utils/downloader.spec.ts
- packages/backend/src/utils/downloader.ts
Download the model to `*.tmp` file in the targeted directory, then renaming when download finish to the name expected.
Fixes https://github.com/projectatomic/ai-studio/issues/389
> feat(models): download to `.tmp` file

- packages/backend/src/managers/playground.spec.ts
- packages/backend/src/managers/playground.ts
- packages/backend/src/utils/utils.ts
Fixes #456
Change options while starting the playground server
N/A
#456
Start the playground for a model on Linux or MacOS applehv
> fix: disable selinux label when mounting the volume for the playground

- packages/backend/src/registries/ContainerRegistry.spec.ts
- packages/backend/src/registries/ContainerRegistry.ts
Adding a startup event for the _future_ InferenceManager (https://github.com/projectatomic/ai-studio/issues/434). Currently when a container is manually stop (and not removed) and start, we do not have access to this event.
> This is because today, in the Playground when creating a container we use `AutoRemove: true`. We need to move out of this option.
Related to https://github.com/projectatomic/ai-studio/issues/434
> feat(ContainerRegistry): start container event listener

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
This PR is a refactor for the application manager to use the newest Publisher class introduced.
> refactor(application): using publisher class to notify webview

- packages/backend/src/registries/LocalRepositoryRegistry.ts
Make the `LocalRepositoryRegistry` extend the existing `Publisher<T>` class to simply its code.
> refactor: make LocalRepositoryRegistry extend Publisher class

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/Navigation.svelte
- packages/frontend/src/pages/Registries.svelte
Fixes #475
Remove the Registry screen
#475
Go to the AI Studio UI
> fix: remove Registries page

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
Fixes #449
Update wording for repo checkout
#449 
1. Select a recipe
2. Start AI app
> fix: use proper wording for repo checkout

- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/stores/inferenceServers.ts
- packages/shared/src/StudioAPI.ts
This PR adds the required methods for the frontend to interact with the `InferenceManager` to the StudioAPI and provide a store to access the InferenceServer available.
Fixes https://github.com/projectatomic/ai-studio/issues/493
> feat: creating inference server store

- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
Propagate https://github.com/projectatomic/ai-studio/pull/457 fix to inference server config
> fix: propagate security option to inference server

- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/utils/ports.ts
We were previously getting the ports from the EXPOSE directive of the Containerfile used to build the model's and recipe's images, which support port ranges.
We are now getting the ports from the ai-studio.yaml file, which is defined as an array of numbers (https://github.com/projectatomic/ai-studio/blob/main/packages/backend/src/managers/applicationManager.ts#L457).
```
imageInfoList.push({
id: image.Id,
modelService: container.modelService,
ports: container.ports?.map(p => `${p}`) ?? [], <-- p is of type number
appName: container.name,
});
```
For this reason, we don't need to support anymore that a port is defined as a range
Part of #451
> remove support for port ranges

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/utils/ports.ts
This PR changes the way the port is selected for the host port of the containers used on a recipe's pod.
Before, the first free port following the internal port were used.
If two recipes were started in a short term, and the detection for the second recipe were done before the first pod was created (and the port effectively used), the same ports were used for both recipes.
With this technique, we are opening/closing a server with a port set to 0, for the kernel to select 'random' free ports for us, and we reuse this free port for the recipe's containers. This reduces the risks of collision.
Later (when https://github.com/containers/podman-desktop/issues/6399 ix fixed), to completely avoid collisions, we will be able to create the pod directly with setting the hostPort to 0 and getting …
> fix: set mapped (random) ports on app labels instead of original ones

- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
this is a quick solution for #517 to not shown a not downloaded model as downloaded.
In future, when we have more time, we could show a resume action
N/A
it resolves #517
1. start to download a model
2. close podman desktop
3. reopen podman desktop
4. the model should not be shown as downloaded
5. you should be able to download it again
> fix: do not show incomplete downloaded models as downloaded

- packages/backend/src/studio-api-impl.ts
- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/InferenceServerConfig.ts
@feloy raise the point that the frontend should not be responsible of providing the default values for creating an InferenceServer.
This PR is simplifying the options for creating the inference servers. Now, only the ModelInfo is required.
Fixes https://github.com/projectatomic/ai-studio/issues/552
> feat: making InferenceServerConfig creation having more optional options

- packages/frontend/src/lib/table/service/ServiceColumnModelName.spec.ts
- packages/frontend/src/lib/table/service/ServiceColumnModelName.svelte
- packages/frontend/src/pages/InferenceServers.svelte
As recommended by @lstocchi adding a model name column to the Services list page
Fixes https://github.com/projectatomic/ai-studio/issues/540
> feat: adding model name column in service page

- README.md
To help users install the extension, add a gif that shows the workflow. Also add a small description of the extension to the top.
I want to add more gifs in the future but at the moment there are many things in motion, so I prefer to wait a couple of days.
> README: add gif to show installation

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/table/model/ModelColumnAction.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnActions.svelte
- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/Models.svelte
Adding a `rocket` icon to the Models action (for models that are downloaded). This action will open the `Creation Service` form allowing to create a service.
Fixes https://github.com/projectatomic/ai-studio/issues/528
**manually**
(1) Go to models page
(2) Click on the rocket icon (need model to be downloaded)
(3) Click on `Create service`
> feat: service creation form

- README.md
When the user wants to clean the environment after testing the tool, or when things are getting updated - it's easy to get out of sync. The information are there to help the user to cleanup the environment.
> Add cleanup information in README.md

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/table/service/ServiceAction.spec.ts
- packages/frontend/src/lib/table/service/ServiceAction.svelte
- packages/frontend/src/pages/InferenceServers.svelte
- packages/shared/src/StudioAPI.ts
This PR is adding the logic to delete an InferenceServer. 
> To enhance the UI we will need https://github.com/projectatomic/ai-studio/issues/547 to store the _transition_ states
https://github.com/projectatomic/ai-studio/assets/42176370/947f142d-6598-4d0d-a216-1b85b8b12421
Fixes https://github.com/projectatomic/ai-studio/issues/546
> feat(inference): adding delete button

- packages/frontend/src/lib/ContentDetailsLayout.spec.ts
- packages/frontend/src/lib/ContentDetailsLayout.svelte
- packages/frontend/src/lib/ContentDetailsLayoutTest.svelte
- packages/frontend/src/lib/RecipeDetails.spec.ts
- packages/frontend/src/lib/RecipeDetails.svelte
- packages/frontend/src/pages/Recipe.svelte
Create a ContentDetailsLayout component, to be reused for Playground page
TODO:
Part of #525 
The Recipe page should be the same
> refacto: create a ContentDetailsLayout from Recipe page

- packages/frontend/.gitignore
- packages/frontend/package.json
- packages/frontend/src/pages/Dashboard.spec.ts
- packages/frontend/src/pages/Dashboard.svelte
- packages/frontend/src/pages/dashboard.md
- packages/frontend/src/pages/dashboard.ts
- types/markdown.d.ts
Fixes #44
Fill the dashboard. Uses the repo README.md but could be a specific markdown file
#44 
Launch Podman Desktop and click on the AI Studio in the nav bar
> fix: Provide a landing page for the studio

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/playground.ts
- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
Fixes #428
Use the inference image built from CI
N/A
#428 
1. Start an inference server
2. Start a playground from a model and start a chat
> fix: use inference image from CI

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/backend/src/utils/randomUtils.ts
- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/shared/src/StudioAPI.ts
The frontend cannot make request longer than 5 seconds to the back. Therefore we need to be smart and use async processes, or notification based processes.
This PR is adding a `requestCreateInferenceServer` returning a `trackingId`. This will be used in the TaskRegistry allowing for the frontend to track the creation without having to wait. The bottleneck was the pulling image, which could take a few seconds to a few minutes.
https://github.com/projectatomic/ai-studio/assets/42176370/2f651596-6910-4255-bae7-89fd4470d4cf
Fixes https://github.com/projectatomic/ai-studio/issues/581 and https://github.com/projectatomic/ai-studio/issues/582
> feat: making inference service creation async

- PACKAGING-GUIDE.md
- packages/backend/src/assets/ai.json
- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/models/AIConfig.ts
It adds support for the new image prop added to ai-studio.yaml file.
N/A
it resolves #161 
1. run any recipe and check that the resulting image have the name defined in its ai-studio. You should delete your local recipe repo as it has to download the new one. If you uses an old repo nothing should change
> fix: use image prop from ai-studio.yaml when defined

- packages/frontend/src/lib/Navigation.svelte
- packages/frontend/src/pages/Dashboard.svelte
Adding padding and link to icon to return to dashboard page 
https://github.com/projectatomic/ai-studio/assets/42176370/d2e60b5e-8fd5-4f74-a21a-f2f3f58b8c6b
Fixes https://github.com/projectatomic/ai-studio/issues/593
- Go to dashboard page
- Leave
- Click on AI Studio icon
> fix: dashboard padding & navigation 

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/pages/Playground.svelte
- packages/shared/src/StudioAPI.ts
- Adds the setting block (the layout as the Recipe details in the recipe page)
- Adds the system prompt
https://github.com/projectatomic/ai-studio/assets/9973512/b6772aea-4ba1-4ba0-bacc-a286b61011e3
Part of #525 
Fixes #543 
Set instructions in the system prompt textarea, and check that it is used for the following prompts (NOTE: for the video above, it happened frequently that the model didn't take in consideration the system prompt for the second and following prompts)
> feat: system prompt for playground page

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/gitManager.spec.ts
- packages/backend/src/managers/gitManager.ts
Empower the user with information on the repository status when starting an application
Scenarios
(1) repository is not cloned
- cloning repository
(2) repository is cloned and behind
- git fetch
- show warning to the user, do you want to update ?
- 'Update' => git pull
- 'Continue' => use as it is
- 'Cancel' => throw error
(3) repository is cloned and detached
- git fetch
- show warning to the user, do you want to reset ?
- 'Reset' => delete folder & git clone & git checkout
- 'Continue' => use as it is
- 'Cancel' => throw error
https://github.com/projectatomic/ai-studio/assets/42176370/415a46df-823f-4cdb-a0c6-580cde86d696
Fixes https://github.com/projectatomic/ai-studio/issues/243
> feat: checkout status check before starting application

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/frontend/src/lib/RangeInput.svelte
- packages/frontend/src/pages/Playground.svelte
- packages/shared/src/models/IModelOptions.ts
Adds options (temperature, max tokens, top-p) to the playground page
Part of #525 
Change parameters before sending prompt, and verify they are effective
> feat: playground options

- packages/frontend/src/pages/Applications.svelte
When there are no apps, the AI Apps page displays a message directing the user to the Recipe Catalog.  The message mentioned an "application catalog" which confused me.  Hence, rephrase the message and point to the "Recipes Catalog" instead.
> AI Apps: rephrase when there are no apps

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/pages/PlaygroundCreate.svelte
- packages/shared/src/StudioAPI.ts
Creates the playground async, and use tasks to display to the user the advancement
Out of scope for this PR:
- A refactoring is possible as the application, inference server and playground creations use the same technique.
Part of #525 
Fixes #615 
Delete inference servers and related image, and create a new playground.
The creation page should display a task 'Creating...'
When the playground is created, a button should be available to go to the Playground page
> feat: async creation of playground

- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/utils/WSLUploader.spec.ts
- packages/backend/src/utils/WSLUploader.ts
- packages/backend/src/utils/modelsUtils.ts
- packages/backend/src/utils/uploader.spec.ts
- packages/backend/src/utils/uploader.ts
To externalize the calculation of the model path on the remote machine we provide the ModelInfo instead of simply the local path.
Fixes https://github.com/projectatomic/ai-studio/issues/636
> feat(models): create utility method to get remote path

- packages/frontend/src/lib/button/Button.svelte
- packages/frontend/src/pages/Dashboard.svelte
Adding a Github button in the dashboard page to open the repository.
> This PR is updating the Button component which has a bug, see https://github.com/containers/podman-desktop/issues/6498 for details
> feat: adding github icon to dashboard

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/pages/Playground.svelte
- packages/frontend/src/pages/PlaygroundCreate.svelte
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/IPlaygroundMessage.ts
This PR moves the system prompt textarea to the creation form of the Playground.
https://github.com/projectatomic/ai-studio/assets/9973512/19cbb519-42c0-4490-a2ec-96a2ea3be1c0
Fixes #617
Create a playground with/without system prompt and check that it is displayed in the playground conversation if set.
> ask the system prompt from the Playground creation form

- packages/frontend/src/pages/dashboard.md
In preparation of the 0.3.0 release, I want to update the dashboard. At the present, it displays the contents of the README with installation instructions which are likely confusing users since the extension has already been installed.
The new text is not perfect and does not fully address #624 but I think it's a step in the right direction.  The descriptions will very likely need polishing in the future.  I did not find a way to create links that allow for opening another menu.  For instance, it would be nice to have clickable links/buttons that navigate users directly into the specific menu such as the Recipes Catalog.
Some graphical elements (e.g., screenshots) may be a nice additions as well.  We can add them later on, if needed, when the UI has settled a bit more.
> update dashboard description

- packages/frontend/src/pages/Models.svelte
Set fixed sizes for most of the columns of the models list.
Before:
With this PR:
Part of #479
> set fixed column sizes in models list

- packages/frontend/src/pages/dashboard.md
Fixes #652
Enhance dashboard with model serving
#652 
Go to the dashboard
> fix: enhance dashboard with model serving

- packages/frontend/src/lib/table/model/ModelColumnName.svelte
Add a tooltip to the model's name in the models list, to be able to see the complete name of the model
Part of #479  (https://github.com/projectatomic/ai-studio/issues/479#issuecomment-2017684480)
> add tooltip to model name

- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
Fixes #658 
Create a playground with a system prompt (you are redirected to the playground page). Go to another page (without sending any prompt), then go back to the playground page. The "semnd prompt" button should be enabled
> enable button when latest message is system prompt

- packages/frontend/src/pages/Playground.svelte
Remove the additional padding on the `<ul>` component, and use the same background color as RecipeDetails
| before | after |
| --- | --- |
| ![image](https://github.com/projectatomic/ai-studio/assets/42176370/084ae088-bd86-4d60-8879-2238aa200353) | ![image](https://github.com/projectatomic/ai-studio/assets/42176370/d4f0ba38-c11c-473a-b19c-fde68976ea04) |
Fixes https://github.com/projectatomic/ai-studio/issues/680
- (1) Open the playground
- (2) create conversation
- (3) make the width window varies
> fix(playground): incorrect padding and background color

- packages/backend/src/assets/ai.json
- packages/frontend/src/pages/Recipes.svelte
- Use latest version of the recipes
- Update prefered models for code generation
- Skip empty categories
Fixes #481
Update the catalog
#481 
Test the 3 AI app from the catalog
> fix: update recipe catalog

- packages/frontend/src/lib/table/model/ModelColumnSize.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnSize.svelte
- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/Models.svelte
This PR adds the memory footprint of models in the models list.
The size is displayed in the Size column, alongside the size of the model on disk.
Part of #479 
Display the models list page, with some models downloaded to see the difference when models are downloaded or not
> feat: display memory footprint for models

- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/utils/downloader.spec.ts
- packages/backend/src/utils/downloader.ts
Ensure errors while downloading are catched and trigger the proper updates of the model store. 
- On error the tmp file is deleted
- On error the stream is destroyed (closing the file properly)
- Completion event is only call after tmp deletion 
Fixes https://github.com/projectatomic/ai-studio/issues/669
**test locally**
- (1) download a model
- (2) run a model
- (3) ensure everything is working properly
> feat(models): downloader handling errors properly

- packages/frontend/tailwind.config.cjs
This PR removes the use of the Montserrat font as a sans serif font.
Fixes #667
Part of https://github.com/projectatomic/ai-studio/issues/479#issuecomment-2017685521
This change can have an impact on many places on the AI Lab app
> fix: do not use Montserrat for sans serif font

- packages/frontend/src/lib/RecipeDetails.spec.ts
- packages/frontend/src/lib/RecipeDetails.svelte
Fixes #450
Display model names instead of mode id on the recipe page
#450
1. Select a recipe
2. Change the model 
3. See the message
> fix: display model name instead of model id on the recipe page

- packages/frontend/src/lib/table/service/ServiceColumnName.svelte
- packages/frontend/src/pages/InferenceServers.svelte
Using table values from [podman-desktop#PodsList.svelte](https://github.com/containers/podman-desktop/blob/0698e4d2fd1f3fcb64bfc8d66a96003545b6ee89/packages/renderer/src/lib/pod/PodsList.svelte#L173)
**before**
**after**
Fixes https://github.com/projectatomic/ai-studio/issues/663
- (1) Go to Model Services page
- (2) See how nice it is
> fix(service): table alignement

- packages/frontend/src/App.svelte
- packages/frontend/src/Route.svelte
- packages/frontend/src/lib/NavPage.svelte
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/InferenceServerDetails.svelte
- packages/frontend/src/pages/Model.spec.ts
- packages/frontend/src/pages/Model.svelte
- packages/frontend/src/pages/Models.svelte
- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
- packages/frontend/src/pages/PlaygroundCreate.svelte
- packages/frontend/src/pages/Playgrounds.svelte
- packages/frontend/src/pages/Recipe.spec.ts
- packages/frontend/src/pages/Recipe.svelte
Adding Breadcrumbs in a similar manner than Podman-Desktop.
> Implementation details: Podman-Desktop use a dedicated store to store the last page, however the webview of AI-Studio can and will be destoryed, re-created many time. making it complicated to save the last page nor relevant with the current UI. In this PR, for each page, we can optionally define a `lastpage` variable, that will display the breadcrumb corresponding.
**Model Service Details**
**Create Model Service**
**Create Playground**
**Playground Details**
**Recipe details**
**model details**
Fixes https://github.com/projectatomic/ai-studio/issues/696
Navigate in the pages of AI-Studio
> feat: adding breadcrumbs

- packages/frontend/src/pages/InferenceServers.spec.ts
- packages/frontend/src/pages/InferenceServers.svelte
Adding `New Model Service` action to services page
Fixes https://github.com/projectatomic/ai-studio/issues/689
> feat: adding create model service button in services page

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/registries/conversationRegistry.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/ContentDetailsLayout.svelte
- packages/frontend/src/lib/conversation/SystemPromptBanner.spec.ts
- packages/frontend/src/lib/conversation/SystemPromptBanner.svelte
- packages/frontend/src/pages/Playground.svelte
- packages/shared/src/StudioAPI.ts
Improving the playground by allowing the user to change the system prompt after the creation.
**Creating a playground without system prompt**
**editing system prompt**
**system prompt edit finish**
**empty input**
> That also means that there should be a way to "edit" the system prompt directly from the playground page.
Related to https://github.com/projectatomic/ai-studio/issues/660 
**manually**
- (1) Create a playground
- (2) set or not a system prompt
- (3) start a conversation or change the system prompt
> feat(playground): introducing system prompt banner

- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/utils/WSLUploader.ts
- packages/backend/src/utils/modelsUtils.spec.ts
- packages/backend/src/utils/modelsUtils.ts
On windows we have a WSL Uploader, which makes the models possibly available on the podman machine.
https://github.com/projectatomic/ai-studio/assets/42176370/6dafb91e-c472-4521-9659-0d010b3fbf28
Fixes https://github.com/projectatomic/ai-studio/issues/635
**windows**
- (1) download a model
- (2) start an inference server to ensure it is uploaded on the Podman Machine
- (3) stop the inference server
- (4) delete the model from the models page
**mac&linux**
- (1) download a model
- (2) delete a model
> feat(models): delete remote model when delete local one

- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/pages/InferenceServers.spec.ts
- packages/frontend/src/pages/InferenceServers.svelte
- packages/shared/src/StudioAPI.ts
- Making the rows in the Model Services page selectable
- Adding delete action for selected items
https://github.com/projectatomic/ai-studio/assets/42176370/776e5183-b2a1-4b65-acaf-68ceef9b7e10
Fixes https://github.com/projectatomic/ai-studio/issues/699
> feat(model-services): making row selectable

- packages/frontend/src/pages/Playgrounds.svelte
There was a useless breadcrumb as shown below 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/711
> fix: remove breadcrumb from playgrounds page

- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
The health status is a nested properties in the `InferenceServer` object, leading to miss-render on properties change. This PR is forcing the re-render using svelte `key`.
Fixes https://github.com/projectatomic/ai-studio/issues/655
> fix(inference-details-ui): forcing refresh on health change

- packages/backend/src/registries/LocalRepositoryRegistry.spec.ts
- packages/backend/src/registries/LocalRepositoryRegistry.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/lib/RecipeDetails.spec.ts
- packages/frontend/src/lib/RecipeDetails.svelte
- packages/shared/src/StudioAPI.ts
This PR adds the local clone and delete local clone buttons.
The first open the local clone repo and the delete button deletes it.
it resolves #402 
1. open a recipe
1.1 if already started previously you should have the local cloned repo buttons already there
1.2 if a new recipe, start it and you should see the local clone buttons when the repo is downloaded
> feat: add local cloned repo link and delete action (#402)

- packages/backend/src/studio-api-impl.ts
Replaces Uri.parse(path) with Uri.file(path) as path does not contain a scheme, which is mandatory with parse
Fixes #726 
Start a recipe and click on 'open in vscode'
> fix: open in vscode

- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/PlaygroundCreate.spec.ts
- packages/frontend/src/pages/PlaygroundCreate.svelte
It shows the error message if the create playground action fails and re-enable the button
it fixes #334 
1. run test or make the `requestCreatePlayground` fails somehow (e.g update code to throw) and see if the error is displayed and you're able to click again the button
> fix: show error if create playground/service actions fail

- packages/backend/package.json
- packages/backend/src/managers/GPUManager.spec.ts
- packages/backend/src/managers/GPUManager.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
- packages/shared/src/models/IGPUInfo.ts
- yarn.lock
This PR is adding an hidden, experimental manager called `GPUManager`. This class is responsible to detect if GPUs are available on the host machine.
We cannot rely on host configuration, and need to create a container, mounting properly the expected devices, especially in WSL, then to detect the gpus a container can access to. 
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/60d48b77-9a16-4052-a76d-4417727617b2
> hint: run `podman pull nvcr.io/nvidia/cuda:12.3.2-devel-ubi8` before, as this can take a looooot of time.
- (1) Open the command palette (F1)
- (2) Select the `AI-Lab: Collect GPU(s)`.
- (3) Wait for the notification popup
> feat: adding hidden utility class to experiment with GPU

- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
- in the playground page, displays the status of the model server. 
-  if the server model is not running/healthy, the 'send prompt' button is disabled and the tooltip indicates the status of the server.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/9973512/307d806a-0021-495a-8063-bf4a0c26a03d
Fixes #646
- Start a playground on a model with no server running and check the model server is marked as not healthy
- stop a model server, and check that is is displayed as not running on a related playground
> feat: disable send prompt when model not served + display status

- .eslintrc.json
- .github/workflows/release.yaml
- .gitignore
- package.json
- tests/playwright/package.json
- tests/playwright/src/ai-lab-extension-installation.spec.ts
- tests/playwright/src/setupFiles/extended-hooks.ts
- tests/playwright/tsconfig.json
- tests/playwright/vitest.config.js
- yarn.lock
* Adds playwright testing framework and folder structure
* Implements basic AI Lab extension installation test
[podman-desktop-ai-lab-extension-installation.webm](https://github.com/containers/podman-desktop-extension-ai-lab/assets/16451875/a5debe24-5855-43cc-b9ec-eb4bef580c92)
containers/podman-desktop-internal/issues/174
* clone podman-desktop repository
* build podman in development mode:
* yarn install --frozen-lockfile
* yarn test:e2e:build
* return back to ai-studio repository
* yarn install --frozen-lockfile
* yarn test:e2e
* Currently the AI Lab extension is rendered inside a `<webview>` element, making it very difficult if not impossible to interact with it through DOM
* Current implementation is as far as I'm able to go with the playwright framework (it's possible I'm unaware of …
> Implement AI Lab extension installation test, add playwright framework and tests structure

- packages/frontend/src/lib/RecipeDetails.spec.ts
- packages/frontend/src/lib/RecipeDetails.svelte
Display the state of an application for a recipe AND a given model, not for the first one found for a recipe.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/9973512/03a6223b-6d4c-468d-99bd-d3b5e85bcf57
fixes #574 
- Start a recipe with a first model
- switch to another model, the button "Start AI App" should appear
- start the recipe with the second model
- navigating to one or other model should display the information of the running app with the selected model (for example the link should point to the good instance - check the port)
> fix: display status of recipe/model

- packages/frontend/src/pages/Models.svelte
Increase slightly the size of the age and labels column
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/739
Go to models page and see if labels and age are not cut in big enough screen
> fix: models column size

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/registries/CancellationTokenRegistry.spec.ts
- packages/backend/src/registries/CancellationTokenRegistry.ts
- packages/backend/src/studio.ts
- packages/frontend/src/lib/progress/TaskItem.spec.ts
- packages/frontend/src/lib/progress/TaskItem.svelte
- packages/frontend/src/lib/progress/TasksProgress.spec.ts
- packages/frontend/src/pages/Models.svelte
- packages/frontend/src/utils/client.ts
- packages/shared/src/models/ITask.ts
This PR is the continuity of https://github.com/containers/podman-desktop-extension-ai-lab/pull/725. It adds the `cancellationToken` to the Task object.
This allow the frontend to call `studioClient.requestCancelToken` on user action.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/0b85edea-946e-4b6c-8eed-af2ba7232861
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/520
> feat: making tasks cancellable

- packages/frontend/src/lib/Navigation.svelte
- packages/frontend/src/pages/Playgrounds.svelte
"Playgrounds environments" needed an apostrophe and capitalization.
Also remove the "for now" to avoid repetition of "now" and rename
the tile in the navigation bar to "Playgrounds" for consistency with
the breadcrumbs etc.
> rename title to "Playground Environments"

- packages/backend/package.json
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
- yarn.lock
This PR is adding a check for the PodmanDesktop version used. If bellow 1.8.0 we throw an error in the extension activate.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/765
**manually**
launch the extension using an old version of PodmanDesktop (E.g. 1.7.0)
> feat: ensuring podman desktop version is >= 1.8.0

- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
The default values for host/port are `0.0.0.0` and `8000`. This PR ensure those value are set manually, to avoid regression if the images change the default values.
Related https://github.com/containers/podman-desktop-extension-ai-lab/issues/767
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/772
> fix(inference): adding missing host and port env

- packages/backend/src/managers/gitManager.spec.ts
- packages/backend/src/managers/gitManager.ts
When starting a recipe, check that no file is modified/created/deleted when the repository is detached
Fixes #773 
Run a recipe from the catalog (the repository should be detached, see `git status`), stop it, then modify, delete or create a file (stage the changes or not), and verify that there is an alert when starting the recipe.
> fix: check modified/created/deleted files when detached repository

- packages/backend/src/utils/uploader.spec.ts
- packages/backend/src/utils/uploader.ts
- packages/backend/src/workers/IWorker.ts
- packages/backend/src/workers/WindowsWorker.ts
- packages/backend/src/workers/uploader/WSLUploader.spec.ts
- packages/backend/src/workers/uploader/WSLUploader.ts
In the future with the GPU, we will have a lot of system specific (win, mac, linux) or hardware specific (NVIDIA, Vulkan) code. @lstocchi introduced the concept of ~workers for the WSL Upload task. This is a pattern we can generify and reuse. 
This PR introduce an interface `IWorker` and an abstract class `WindowsWorker` with basic utilities. The main goals are
- Reducing the quantity of code in the `packages/backend/src/utils` folder, which start to get too big
- Generify the WSL worker and offer reusable component for later usage
> refactor: workers by system

- packages/frontend/src/lib/Navigation.svelte
- packages/frontend/src/lib/SettingsNavItem.spec.ts
- packages/frontend/src/lib/SettingsNavItem.svelte
Enhancing the navigation bar following the discussion in https://github.com/containers/podman-desktop-extension-ai-lab/issues/672
- Fixing the border color resulting in weird left pixels
- Splitting in two section (AI Apps & Models)
- Adding icons
| --- | --- |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/65e27719-341d-4e5f-884f-a194ade40ece) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/3cbaacc5-4ac8-43c3-8704-c6125dcbb322) |
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/672
> feat: enhance navigation bar

- packages/frontend/src/pages/Recipes.svelte
Fixes #779
Remove the recently processed recipes from the recipes catalog pag
#779 
Go the recipes catalog page
> fix: remove the last recipes from recipes page

- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
The special case of nighties are handled with an ignore warning. We are checking if `major` and `minor` are zeroes, if it does, we ignore the version check.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/787
> fix: nighties version are not subject to version verification

- packages/frontend/src/lib/Navigation.svelte
The navigation item have a border of 4px, making them slightly unaligned. This PR is adding this 4px as margin to other items to align item. 
| --- | --- |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/86aadacc-c72e-43fc-a097-4a07f3385cd3) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/d4c2d6c1-f4e4-4e08-a498-e5fbfef31ee9) |
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/795
> fix: navigation alignment

- packages/frontend/src/pages/InferenceServerDetails.svelte
Ensure the container id is centered properly
**Before**
**After**
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/572
> fix(ServiceDetails): items center

- packages/frontend/src/pages/RecipeModels.spec.ts
- packages/frontend/src/pages/RecipeModels.svelte
Fixes #623
Add model icon in the recipe model list
#623 
1. Go to a recipe map
2. Switch to the models list
> feat: add model icon in the list of models for a recipe

- packages/frontend/src/pages/Playgrounds.svelte
fix alignment.
instead of keeping the left alignment and move the action icon a bit more away from the right-end. I think it's nicer to have it centered. Maybe when having more icon we can think about switching back to left
it resolves #786 
1. go to the playgrounds page
> fix: wrong alignment in playground table header

- packages/frontend/src/lib/RecipeDetails.spec.ts
- packages/frontend/src/lib/RecipeDetails.svelte
it disables the delete local clone button when the ai app is building 
it resolves #745 
1. run recipe and check that while it is building the images the button is disabled
> fix: disable delete local clone when building ai app

- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/ApplicationActions.spec.ts
- packages/frontend/src/lib/ApplicationActions.svelte
After discussing with @slemeur about https://github.com/containers/podman-desktop-extension-ai-lab/issues/469 we understood that the delete icon added in https://github.com/containers/podman-desktop-extension-ai-lab/pull/719 was responsible of the cleanup.
To complete the ticket, this PR is changing the misleading stop icon to the trash icon, to reflect the real action of the button, which is deleting the pod.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/469
> feat: better icon for pod deletion

- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
Use `extensionContext.storagePath` instead of `$HOME/podman-desktop/ai-lab`.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/844
> fix: using podman storage path from context

- packages/frontend/src/pages/Models.svelte
This PR improve slightly the catalog models table, by increasing the size of the age column, and adding comparators to sort the column.
**seconds**
** minutes **
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/840
> fix: models table columns

- packages/backend/src/managers/SnippetManager.spec.ts
- packages/backend/src/managers/SnippetManager.ts
- packages/backend/src/studio.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
Fixes #835
Add telemetry events for snippets:
- `snippet.create`: when a snippet is generated
- `snippet.copy`: when code is copied into clipboard
Both have `language` and `variant` as properties
<N/A
#835 
N/A
> fix: add telemetry for snippets

- packages/backend/src/managers/catalogManager.spec.ts
- packages/backend/src/managers/catalogManager.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/backend/src/tests/ai-user-test.json
- packages/frontend/src/App.svelte
- packages/frontend/src/lib/table/model/ModelColumnLabels.svelte
- packages/frontend/src/lib/table/model/ModelColumnName.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnName.svelte
- packages/frontend/src/pages/ImportModels.spec.ts
- packages/frontend/src/pages/ImportModels.svelte
- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/Models.svelte
- packages/shared/src/StudioAPI.ts
- packages/shared/src/messages/MessageProxy.spec.ts
- packages/shared/src/messages/MessageProxy.ts
- packages/shared/src/messages/NoTimeoutChannels.ts
- packages/shared/src/models/ILocalModelInfo.ts
- packages/shared/src/models/IModelInfo.ts
- packages/shared/src/uri/Uri.spec.ts
- packages/shared/src/uri/Uri.ts
It allows to import .gguf models that have already been downloaded by the user and that are on his machine.
After imported, the user can start a service, open its folder and delete it
it resolves #173 
Fixes #814 
1. download a gguf model which is not listed in the catalog (e.g. take the first ones from here https://huggingface.co/TheBloke/Mistral-7B-Instruct-v0.1-GGUF/tree/main 
2. go to models, import, select the gguf file
3. once imported, try to play with it (inference server + playground)
4. then delete it (it will be removed from catalog and disk)
> feat: allow to import local models

- packages/backend/package.json
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/utils/podman.spec.ts
- packages/backend/src/utils/podman.ts
- packages/frontend/src/lib/notification/ContainerConnectionStatusInfo.spec.ts
- packages/frontend/src/lib/notification/ContainerConnectionStatusInfo.svelte
- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/utils/connectionUtils.spec.ts
- packages/frontend/src/utils/connectionUtils.ts
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/IContainerConnectionInfo.ts
- packages/shared/src/models/IModelInfo.ts
- yarn.lock
It shows a warning banner if the running podman machine does not have enough resources for the model selected by the user or if there is no running machine.
This needs https://github.com/containers/podman-desktop/pull/6733 to work
This PR only covers the inference server page to make the review easier. Going to open a new PR for the recipe page once it is merged
This gif shows if you can edit the machine and if there is no running machine
This is the message if the edit action is not enabled for the system (like WSL)
Fixes #873 
1. if you are on WSL you need to hack the result received from the system as it takes the resources from the host so you have to load the machine a lot to see the warning message
2. on MAC by creating a machine with few resources you should see the banner
> feat: show warning if no machine is running or there are not enough resources (#227)

- packages/frontend/src/pages/Dashboard.svelte
- packages/frontend/src/pages/Playgrounds.svelte
Based on user feedback, add the description from the dashboard to the playgrounds page when there is none running.  This way, new users receive more information and guidance and have an easier time navigating AI Lab and its functionality.
Fixes: #877
> playground: add description when there's no playground

- packages/backend/src/managers/modelsManager.ts
Change the upload task name from `Uploading model $modelName` to `Copying model $modelName to Podman Machine`
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/885
Start an inference server
> fix: model upload task name

- packages/backend/src/assets/ai.json
- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/shared/src/models/IModelInfo.ts
This PR is adding the optional `chatformat` to the model object.
Need https://github.com/containers/podman-desktop-extension-ai-lab-playground-images/pull/11 to be merged, and a new version published of the image to be working.
Fixing the playgrounds for the following models
- Merlinite
- Cerebrum
- dragon-mistral
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/825
> fix: adding chatformat to use for inference servers

- packages/frontend/src/lib/table/service/ServiceStatus.svelte
- packages/frontend/src/pages/InferenceServers.svelte
Fixes the refresh issue on the Inference server table. Removing the reactive data in favour of a proper subscribe in the onMount fixed the problem.
Before the item was either not appearing, or was stuck in the same status.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/4463d6a5-6a66-45bb-8c05-799e00d4b71f
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/882
Reproduce the video above
> fix: refresh issue for inference servers

- packages/frontend/src/pages/InferenceServers.spec.ts
- packages/frontend/src/pages/InferenceServers.svelte
Update the message when there is no service running.  We did the same for playgrounds already.
Before:
After:
> service page: update empty message

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
After some investigation, we did not have any logic for external stop events, leading to the server still marked as running for a period of time (until the pull update, which can last up to 10 seconds).
This PR is adding proper management of the `die` container event to improve the reactivity of the updates.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/1f80f7fa-62e6-44b2-a253-7f83c5a10cd1
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/893
> fix: capture die events for inference servers

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/backend/src/utils/modelsUtils.ts
Fixes #903
Allow to pass model properties as environment variables when starting an AI App like it is done for an inference server
N/A
#903
1. Start a recipe with a model with properties
2. Enter the model server container
3. Verify the environment variable is set
> feat: provides model properties to model service while running an AI App

- packages/backend/src/assets/ai.json
Fixes #695
Add 2 recipes to the catalog
Blocked by:
N/A
#695 
Start the 2 new recipes:
-  for the object_detection recipe, you can use this image: http://images.cocodataset.org/val2017/000000039769.jpg
- for the audio_to_text you can use the jfk.wav that is located in the data folder of the recipe repository
> fix: add audio_to_text and object_detection recipes to the catalog

- README.md
- packages/backend/src/managers/catalogManager.spec.ts
- packages/backend/src/managers/catalogManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
See https://github.com/containers/podman-desktop-extension-ai-lab/issues/792#issuecomment-2060792927 for details
When we were importing a model we were copying to existing catalog, and creating a new one with the user's models in it. This lead to the issue that the catalog was not updated.
This PR fixes this issue, by having the user's catalog a complementary catalog, being merged at startup with the one provided by the extension. By this method, the user can define recipes, models or categories in a json file, and they will be added to the existing one if properly formatted.
When importing models, this file is automatically created and filled with the user's models details.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/297da5c2-78e6-48dd-95db-cdf2affb1b99 …
> fix: user catalog

- packages/backend/src/assets/ai.json
Fixes #932
Update the model property from modelName to name (expected by recipe)
N/A
#932 
1. Start the object_detection recipe
2. Go into the model server container
3. Verify that the environment variable MODEl_NAME is set
> fix: modelName should be name

- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
Fixes #847
Add tootips for the parameters on the playground page
#847 
Go to a playground
> fix: add tooltips for the model paramaters in playground

- packages/frontend/src/lib/ContentDetailsLayout.svelte
- packages/frontend/src/pages/Recipe.svelte
| --- | --- |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/589e5373-cc93-4516-a92c-4be5eb422560) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/84d7ce25-345e-4d86-9826-69d199802f16) |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/b757fa40-9f3e-4b97-a9ea-40e8ca839e81) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/36b440f0-b4f6-463b-a5e5-5a036fc75cb8) |
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/947
> fix: weird spacing

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/frontend/src/lib/table/service/ServiceAction.spec.ts
- packages/frontend/src/lib/table/service/ServiceAction.svelte
- packages/frontend/src/lib/table/service/ServiceStatus.spec.ts
- packages/frontend/src/lib/table/service/ServiceStatus.svelte
- packages/shared/src/models/IInference.ts
Adding transition statuses to the Inference Servers. This work has started with https://github.com/containers/podman-desktop-extension-ai-lab/pull/550 but was delayed to other priorities.
This allows to improve the user experience.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/ef72faa4-737f-4aaa-8c5c-7238123e61b2
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/857 https://github.com/containers/podman-desktop-extension-ai-lab/issues/547 https://github.com/containers/podman-desktop-extension-ai-lab/issues/942
You can test it manually by reproducing the videos above.
> feat(inference): adding transition statuses

- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/Models.svelte
Adding an imported tab to models page for imported models.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/f494ff6c-fbc9-4f18-9d2c-127cd883c5eb
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/944
> feat: adding imported tab in models page

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/frontend/src/pages/PlaygroundCreate.svelte
Raise an error when the user creates a playground with a name already used by another playground.
https://github.com/containers/podman-desktop-extension-ai-lab/assets/9973512/1133d8b7-ce81-4e61-a96a-e6752e9a956f
Fix #782 
- Create a first playground
- try to create a second playground with the same name
> fix: forbid creating several playgrounds with the same name

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/pages/PlaygroundCreate.svelte
- packages/shared/src/StudioAPI.ts
Remove the system prompt input from playground creation page. The system prompt is still settable from the playground page.
Fix #660 
Create a playground and check the system prompt can be set after creation time
> Remove system prompt from playground creation page

- README.md
> Update README with proper naming

- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
Fixes #839
Gives focus to the prompt and handle Enter key
#839 
1. Create a playground
2. Enter text + enter => should send the request
> fix: playground improvements for keyboard usage

- packages/backend/src/managers/gitManager.spec.ts
- packages/backend/src/managers/gitManager.ts
When starting a recipe, resolve tag (if a tag) before to compare with current commit
Fix #1038 
- Start a recipe, stop it, and start it again. No error should be raised.
- Change sources, then restart recipe. A message should indicate the repository is not clean
> resolve tag before to compare with current commit

- README.md
> Add mini-roadmap to README.md

- README.md
> Update roadmap in README.md

- packages/backend/src/assets/ai.json
Update to latest v1.1.1 fixing issue on some intel CPUs / Windows
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1031
> chore: udpate to v1.1.1 AI Lab Recipes

- packages/frontend/src/lib/ErrorMessage.svelte
- packages/frontend/src/lib/Tooltip.svelte
- packages/frontend/src/pages/Playground.svelte
This just updates the Tooltip component that will be used in next PRs. It is the exact copy of the ui package https://github.com/containers/podman-desktop/pull/7150 . So i can progress until we have the ui available here
N/A
part of #977 
N/A
> chore: update tooltip to same as ui package

- packages/backend/package.json
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
It allows to set a custom folder where to download models.
Right now, the settings it is just a textbox where the user has to copy/paste the path. It will need the PR https://github.com/containers/podman-desktop/pull/7135 to be merged to switch to a file component
N/A
it resolves #51 
1. update the models dir by using the new setting. Restart the extension and check it uses the new folder
> feat: allows to set a custom folder where to download models

- packages/backend/src/utils/podman.spec.ts
- packages/backend/src/utils/podman.ts
- packages/frontend/src/lib/notification/ContainerConnectionStatusInfo.svelte
- packages/shared/src/models/IContainerConnectionInfo.ts
Fixes #1022 
On Linux, Go to a Recipe page and check that no warning about podman machine is displayed
> Do not check resources on Linux

- packages/backend/src/utils/sha.spec.ts
- packages/backend/src/utils/sha.ts
It avoid reading a huge file all at once, resulting in a failure when trying to calculate sha256
N/A
it resolves #1093 
1. download a big model (> 2GB) like granite
2. start a recipe with the downloaded model (it must already be on disk, otherwise you won't face the issue/fix)
> fix: error when calculating sha256 on big files

- packages/frontend/src/lib/RecipeCard.svelte
- packages/frontend/src/lib/RecipesCard.spec.ts
- packages/frontend/src/lib/RecipesCard.svelte
- packages/frontend/src/pages/Recipes.spec.ts
- packages/frontend/src/pages/Recipes.svelte
- Remove the catalog store dependency of the RecipesCard component 
- Create a dedicated RecipeCard component
- Place all recipes without categories in an `unclassified` section (before they were just not displayed)
This work is required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/1095
https://github.com/containers/podman-desktop-extension-ai-lab/pull/1097 will need to be rebased after this is merged
> feat: improve recipes page

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/utils/imagesUtils.spec.ts
- packages/backend/src/utils/imagesUtils.ts
- packages/backend/src/utils/podsUtils.ts
- packages/backend/src/utils/ports.ts
The `ApplicationManager` is too big, and doing too much stuff. We **need** to simply it. 
This PR move the static functions to dedicated utils file, to remove some noise from the ApplicationManager.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1102
> refactor: cleanup application manager

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/recipes/BuilderManager.spec.ts
- packages/backend/src/managers/recipes/BuilderManager.ts
- packages/backend/src/studio.ts
Simplify the ApplicationManager class by migrating build image logic to a dedicated manager.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1104
You can start some recipes to ensure there is not regression
> refactor(ApplicationManager): extract build image logic

- packages/backend/src/utils/inferenceUtils.ts
Fixes #1103
Bump inference server to 0.3.2
N/A
#1103 
1. Create an inference server
2. Create and use a playground
> fix: bump inference server image to 0.3.2

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/recipes/BuilderManager.spec.ts
- packages/backend/src/managers/recipes/PodManager.spec.ts
- packages/backend/src/managers/recipes/PodManager.ts
- packages/backend/src/studio.ts
Following the work on simplifying the ApplicationManager, this PR extract some methods related to pods. This ease the testing process, as we do not need to mock tons of containerEngine function inside the ApplicationManager.spec.ts file.
Start a recipe, restart ai-lab, check recipe is shown in the running page
> refactor: create PodManager

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/recipes/PodManager.spec.ts
- packages/backend/src/managers/recipes/PodManager.ts
- The custom interface ContainerAttachedInfo is replaced with PodContainerInfo (from api)
- The custom interface ApplicationPodInfo is replaced with PodInfo (from api)
- Renaming `runApplication` to `initApplication` to better match what it is doing (see code comment added)
- createAndAddContainersToPod is renamed to createContainerAndAttachToPod
Work is required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/691
You can check recipes are working as expected
- Start recipe
- Stop recipe
- Restart recipe
> refactor(ApplicationManager): remove unused interfaces 

- packages/frontend/src/lib/table/service/ServiceAction.spec.ts
- packages/frontend/src/lib/table/service/ServiceAction.svelte
- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
Improve the InferenceServerDetails header page
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/d0fbdd9d-600d-4618-ad7d-d8f78151ace1
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/665
> feat: improve inference server details page

- packages/frontend/src/lib/RecipeCard.svelte
It just adds the hover state to recipe card
it fixes #843 
1. go to the recipes page and hover a card
> fix: add hover to recipe card (#843)

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/podmanConnection.ts
- packages/backend/src/managers/recipes/PodManager.spec.ts
- packages/backend/src/managers/recipes/PodManager.ts
- packages/backend/src/studio.ts
This PR moves and cleanup the logic of capturing pod event, previously located in PodmanConnection class, inside the PodManager.
The following changes are included:
- Using `EventEmitter` instead of declaring new types and storing the listeners in arrays
- Adding tests
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1129
> refactor: moving pod events method to PodManager

- packages/backend/src/managers/catalogManager.spec.ts
- packages/backend/src/managers/catalogManager.ts
Fixes the import model issue happening on fresh install 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1132
- Delete the folder `~/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab` (or rename it)
- Start podman desktop with AI Lab
- Import a model (do not do anything else)
> fix: importing model fresh install

- packages/backend/package.json
- packages/backend/src/managers/GPUManager.spec.ts
- packages/backend/src/managers/GPUManager.ts
- packages/backend/src/workers/gpu/WinGPUDetector.spec.ts
- packages/backend/src/workers/gpu/WinGPUDetector.ts
- packages/shared/src/models/IGPUInfo.ts
- yarn.lock
Remove the old GPUManager code detecting the Nvidia GPU using `nvidia-smi` and replace it with a generic worker system.
This PR is adding the `WinGPUDetector` worker.  This worker is responsible of detecting the GPUs available on windows.
We need two information, the name and the VRAM available for each GPU, sadly windows is crap[^1][^2][^3], and they don't fix their code[^1], so we have to read the registry[^4] to access the exact value of the VRAM for each GPU detected.
> Reading the registry could feel scary but we are simply following the official Microsoft documentation here, with long term support values. Therefore not too scary :)
Other solution do not provide accurate value[^3].
Related to https://github.com/containers/podman-desktop-internal/issues/270
Fixes …
> feat(win): better gpu detection

- tests/playwright/src/ai-lab-extension.spec.ts
* Fixes navigation changes in tests
* Synchronizes architecture with BootC extension
N/A
#978 
* compile Podman  Desktop from source in e2e test mode (yarn test:e2e:build)
* export PODMAN_DESKTOP_ARGS=<path_to_podman_desktop_sources>
* change directory to `tests/playwright`
* run `yarn test:e2e`
Example test output:
```
...
✓ src/ai-lab-extension.spec.ts (4) 14894ms
✓ AI Lab extension installation and verification (4) 10796ms
✓ AI Lab extension installation (2) 10665ms
✓ Open Settings -> Extensions page 512ms
✓ Install AI Lab extension 10153ms
✓ AI Lab extension verification (2)
✓ Verify AI Lab is present in notification bar and open it
✓ Verify AI Lab is running
Test Files  1 passed (1)
Tests  4 passed (4)
Start at  09:25:57
Duration  15.91s (transform 129ms, setup 475ms, collect 26ms, …
```
> Fix Podman Desktop Extension navigation and installation

- packages/frontend/package.json
- packages/frontend/tailwind.config.cjs
- yarn.lock
Adding the `@podman-desktop/ui-svelte` library using `1.10.3`.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1165
> feat: adding @podman-desktop/ui-svelte

- .github/workflows/e2e-main.yaml
Add e2e main test workflow running on linux on demand and after push into main.
> chore(ci): add all e2e main linux workflow

- packages/backend/src/studio.ts
https://github.com/containers/podman-desktop-extension-ai-lab/pull/1167 introduced a regression, it removed (by accident) to add the webview panel created to the subscriptions that must be disposed when the extension is stopped.
> fix: dispose webview panel

- packages/backend/package.json
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/registries/InferenceProviderRegistry.ts
- packages/backend/src/studio.ts
- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/backend/src/workers/IWorker.ts
- packages/backend/src/workers/provider/InferenceProvider.spec.ts
- packages/backend/src/workers/provider/InferenceProvider.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/shared/Messages.ts
- packages/shared/src/models/InferenceServerConfig.ts
- yarn.lock
Introducing `InferenceProvider` interface, which is an abstraction class made to create InferenceServers. In todays implementation we do not make distinctions between `backends` (llamacpp, whispercpp etc.)
This is the first step in abstracting the inference providers, to ease the customization of inference server with new provider in the future (whispercpp, llamacpp-cuda, ollama etc.)
[![](https://mermaid.ink/img/pako:eNp1kcFugzAMhl_Fyrl9AQ69bNPEAQnRKxcvMSwaOMxxkKqq774gSqtuXU5O_P3-f8VnY4MjU5hI34nY0qvHXnBsGfJBq0EgRZL1PqGot35CVigrwAgldySLrkLG_ilXNw8g1BJm70igod5HlVPLq2rx2e8Ph7Iqci_HifoihEo37ZFk3jzKamPfOCYhmHHwDmzgzvdJUH3gB7JuCngnvSfZgsQrVjd3d03C_5M362UeMX4M5P7Sv2GLwwATSRdkhMAQaSCrz5Wr1uzMSDKid3lD5-WtNfpJI7WmyKVD-WpNy5fMYdJwPLE1hUqinUmTyz933aYpOhwiXX4AV1unEw?type=png)](https://mermaid.live/edi …
> feat(inference): introducing InferenceProviders

- packages/backend/src/managers/applicationManager.spec.ts
- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/registries/ContainerRegistry.ts
- packages/backend/src/registries/LocalRepositoryRegistry.spec.ts
- packages/backend/src/registries/LocalRepositoryRegistry.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio.ts
- packages/shared/src/messages/MessageProxy.ts
Improve the `studio.ts` file, to improve the way we dispose resources (managers).
Moreover, making more classes implements the disposable, to improve consistency in our designs 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1166
> chore: improve resource disposal

- packages/backend/src/assets/ai.json
- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/registries/InferenceProviderRegistry.ts
- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/backend/src/workers/provider/InferenceProvider.spec.ts
- packages/backend/src/workers/provider/InferenceProvider.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServers.spec.ts
- packages/shared/src/models/IInference.ts
- packages/shared/src/models/IModelInfo.ts
- packages/shared/src/models/IRecipe.ts
Adding the `InferenceType` enum, allowing `InferenceProvider` (see https://github.com/containers/podman-desktop-extension-ai-lab/pull/1161) to precise their _type_, in this context, it could be `llama-cpp`, `whisper-cpp` etc.
- Adding new enum `InferenceType`
- Adding optional `backend` string property to `ModelInfo` interface
- Adding optional `backend` string property to `Recipe` interface
- adding `getByType` method to the `InferenceProviderRegistry`
- InferenceServer will check the `backend` property of models to select the `InferenceProvider`
- Improving `InferenceProvider` constructor
N/A no visual change
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1181
Part of https://github.com/containers/podman-desktop-extension-ai-lab/issues/1111
Now, trying to …
> feat: adding InferenceType enum

- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/shared/src/models/IInference.ts
In the `ai.json` we used `llama-cpp` with a `-` but in the InferenceType we are missing it.
https://github.com/containers/podman-desktop-extension-ai-lab/blob/5ddb5c548173f8b2b29787fb7f1740f12df49f2a/packages/backend/src/assets/ai.json#L28
- Being able to start any model from the catalog
> hotfix: enum inference type wrong string value

- packages/frontend/package.json
- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
- yarn.lock
Bump from `1.10.3` to next as we need more recent version containing more components.
ℹ️ I had to fix the tooltip component has it has been changed by https://github.com/containers/podman-desktop/pull/7436
Required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/974
> chore: bump ui-svelte lib to next version

- packages/shared/src/messages/MessageProxy.spec.ts
- packages/shared/src/messages/MessageProxy.ts
Introduced by https://github.com/containers/podman-desktop-extension-ai-lab/pull/1175, we duplicate proxy events by subscribing two time to the webview messages.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1206
> fix: events duplication

- packages/backend/src/managers/applicationManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/frontend/src/lib/RecipeCard.svelte
- packages/frontend/src/lib/RecipeStatus.spec.ts
- packages/frontend/src/lib/RecipeStatus.svelte
- packages/frontend/src/lib/RecipesCard.spec.ts
- packages/frontend/src/lib/RecipesCard.svelte
- packages/frontend/src/pages/Recipes.spec.ts
- packages/frontend/src/pages/Recipes.svelte
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/ILocalRepository.ts
Following one of the mockup in https://github.com/containers/podman-desktop-extension-ai-lab/issues/1126, improving the recipes card.
- Adding an icon showing the status (cloned or not) similar to the one in extension catalog
- Adding the path in the card 
Fixes partially https://github.com/containers/podman-desktop-extension-ai-lab/issues/1126
> feat: revamp recipes list page

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/studio.ts
To fix the concurrency issue, (Inference Manager getting the containers list before the catalog has loaded the models from the files), I changed the InferenceManager to refresh the inferenceServers when the catalog is updated. Making the InferenceServer event base for its initialization.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1215
> fix: concurrency issue between catalog and inference manager

- packages/backend/src/assets/ai.json
Fixes #1187
Use SHA256 in catalog for facebook/detr-resnet-101 model
N/A
#1187 
Download the model
> fix: invalid SHA256 for facebook/detr-resnet-101 model

- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
Since https://github.com/containers/podman-desktop/pull/7643 the format of the versioning has changed
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1221
> feat: support new podman-desktop version tag

- packages/frontend/src/App.svelte
- packages/frontend/src/pages/ImportModel.svelte
Updtae the "Import Model" page to use the dedicated FormPage component instead of NavPage
Also change a few colors to support light mode (except colors in the form itself)
Fixes #1229  
Navigate to Catalog > Import
> Use FormPage for Import Model page

- packages/frontend/package.json
- packages/frontend/src/lib/table/playground/PlaygroundColumnIcon.svelte
- packages/frontend/src/pages/Playgrounds.svelte
- packages/frontend/src/pages/RecipeModels.svelte
- yarn.lock
Use latest ui-svelte version including DetailsPage
> Use latest ui-svelte version including DetailsPage

- packages/frontend/src/pages/PlaygroundCreate.svelte
Update the "Create Playground" page to use the dedicated FormPage component instead of NavPage
Also change the background color to support light mode
Fixes #1232
Navigate to Playgrounds > Create new playground
> Use FormPage for Create Playground page

- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
Use DetailsPage for Playground page
(light mode is not covered, as colors are specific for this page)
Fixes #1242
> Use DetailsPage for Playground page

- packages/frontend/src/pages/PlaygroundCreate.svelte
Light mode for new playground page
select depends on https://github.com/containers/podman-desktop/issues/6199
Fixes #1259
> Light mode for new playground page

- packages/frontend/src/lib/table/service/ServiceColumnModelName.svelte
- packages/frontend/src/lib/table/service/ServiceColumnName.svelte
- packages/frontend/src/pages/InferenceServers.svelte
Light mode for Services page
~~Needs https://github.com/containers/podman-desktop-extension-ai-lab/pull/1246 to get the good background~~
Actions depend on https://github.com/containers/podman-desktop-extension-ai-lab/issues/964
StatusIcon depend on #1271
Fixes #1270
> Light mode for Services page

- packages/frontend/src/lib/table/application/ColumnAge.svelte
- packages/frontend/src/lib/table/application/ColumnModel.svelte
- packages/frontend/src/lib/table/application/ColumnPod.svelte
- packages/frontend/src/lib/table/application/ColumnRecipe.svelte
- packages/frontend/src/pages/Applications.svelte
Light mode for AI apps list
~~Needs https://github.com/containers/podman-desktop-extension-ai-lab/pull/1246 to get the good background~~
Actions depend on https://github.com/containers/podman-desktop-extension-ai-lab/issues/964
Fixes #1263
> Light mode for AI apps list

- packages/frontend/src/lib/Card.svelte
- packages/frontend/src/lib/RecipeCard.svelte
- packages/frontend/src/lib/RecipeStatus.svelte
Light mode for recipes page
~~Needs https://github.com/containers/podman-desktop-extension-ai-lab/pull/1246 to get the good background~~
Fixes #1261
> Light mode for recipes page

- packages/frontend/src/lib/table/playground/PlaygroundColumnModel.svelte
- packages/frontend/src/lib/table/playground/PlaygroundColumnName.svelte
- packages/frontend/src/pages/Playgrounds.svelte
Light mode for playgrounds page
~~Needs https://github.com/containers/podman-desktop-extension-ai-lab/pull/1246 to get the good background~~
Actions depend on #964
Fixes #1256
> Light mode for playgrounds page

- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
Fixes #1087
Prevent using keyboard while there is a request being processed
N/A
#1087
Use the playground
> fix: prevent using keyboard in plyaground while request is ongoing

- packages/backend/package.json
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/registries/ConfigurationRegistry.spec.ts
- packages/backend/src/registries/ConfigurationRegistry.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
- packages/frontend/src/stores/extensionConfiguration.ts
- packages/shared/src/StudioAPI.ts
- packages/shared/src/models/IExtensionConfiguration.ts
- packages/shared/src/models/InferenceServerConfig.ts
Creating a dedicated registry to hold configuration (preferences) logic.
- ConfigurationRegistry manage the `ai-lab.models.path` previously managed by `ModelsManager`
- Creating frontend store holding the configuration values
> feat: creating extension configuration registry

- packages/frontend/src/pages/InferenceServerDetails.svelte
Light mode for inference service details page
Fixes #1284
> chore: light mode for inference service details page

- packages/frontend/src/lib/icons/ModelWhite.svelte
- packages/frontend/src/lib/table/model/ModelColumnAction.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnActions.svelte
- packages/frontend/src/lib/table/model/ModelColumnIcon.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnIcon.svelte
- packages/frontend/src/lib/table/service/ServiceStatus.spec.ts
- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/RecipeModels.spec.ts
Improve the Models page by changing the StatusIcon depending on the model usage.
When the model is used by an inference server, it is marked as `USED`. A model which is downloaded has a title `DOWNLOADED`.
The delete button is also disabled when model is inUse
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/791
> feat: prevent user from deleting model when inUse

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
Making the InferenceManager initialize by default, and on catalog update.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1333
> fix(InferenceManager): not initializing without user catalog

- packages/frontend/src/lib/ContentDetailsLayout.svelte
- packages/frontend/src/lib/RangeInput.svelte
- packages/frontend/src/lib/conversation/ChatMessage.svelte
- packages/frontend/src/lib/conversation/ConversationActions.svelte
- packages/frontend/src/lib/conversation/SystemPromptBanner.svelte
- packages/frontend/src/pages/Playground.svelte
it enables light mode for Playground details page
light
dark
it resolves #1285 
1. go to the playground details page and check it in light/dark mode
> feat: enable light mode for Playground details page

- packages/frontend/tailwind.config.cjs
We are not using the same markdown component as podman desktop; therefore we need to propagate some of the css variable to the component. We are using the https://github.com/tailwindlabs/tailwindcss-typography, and as mention in their documentation, we can easily define custom value.
| Light | Dark |
| --- | --- |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/b85d9be9-9406-4358-b12b-5cf50ed1093f) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/9282eac5-6132-4f6a-8503-2b91b83431fc) |
| ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/82802349-2432-4c5a-8d83-ca0b9a8bce96) | ![image](https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/2b727a0d-5d5 …
> chore(tailwindcss): uses podman desktop var for markdown

- packages/frontend/src/lib/Card.svelte
- packages/frontend/src/lib/RecipeCard.svelte
* Adds a label to Card.svelte
* Adds a label to RecipeCard.svelte
#978 
* yarn build
* podman build . -t <extension_label>
* push to online repository
* install via OCI image
> Adding labels to Card.svelte

- packages/backend/package.json
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/vite.config.js
- packages/shared/src/StudioAPI.ts
- yarn.lock
This only adds the backend logic to collect a model metadatas. See https://github.com/containers/podman-desktop-extension-ai-lab/pull/1345 for details.
The `@huggingface/gguf` is used.
N/A
Related to https://github.com/containers/podman-desktop-extension-ai-lab/issues/1344
Required for https://github.com/containers/podman-desktop-extension-ai-lab/pull/1280#issuecomment-2196310464
> feat(models): adding backend logic to collect model metadata

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/registries/ConversationRegistry.ts
- packages/frontend/src/pages/Playground.svelte
- packages/shared/src/models/IPlaygroundMessage.ts
This PR adds capabilities to display error messages during a chat. So far we just printed the errors in the console, but they are useful to guide the user. 
I extended the messages that a conversation includes. So far, we just had ChatMessages, but we could also have ErrorMessages. The only thing i'm not sure about is how to display them, so i chose to use what we have now (just show the newest error message if it's the last message of the conversation), but it could be very easy to display them as part of the conversation so when you scroll up you can see the error you received for an old input. Waiting to hear your preference.
it resolves https://github.com/containers/podman-desktop-extension-ai-lab/issues/1083 and https://github.com/containers/podman-desktop-extension-ai-lab/issues/1021 …
> fix: display error message from chat conversation

- PACKAGING-GUIDE.md
- packages/backend/src/assets/ai.json
- packages/backend/src/managers/catalogManager.spec.ts
- packages/backend/src/managers/catalogManager.ts
- packages/backend/src/tests/ai-test.json
- packages/backend/src/tests/ai-user-test.json
- packages/backend/src/utils/catalogUtils.spec.ts
- packages/backend/src/utils/catalogUtils.ts
- packages/shared/src/models/IApplicationCatalog.ts
This PR set a version to the catalog, current `1.0`. When undefined or different, the user-catalog will not be loaded and a warning will be logged.
To ensure the user-catalog respect the format, the `CatalogUtils` file has been created, which will properly check for all the fields.
https://github.com/user-attachments/assets/744cc19d-bbea-4b46-a814-1da62b540684
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/59
Reproduce video above
> feature: adding versioning to the catalog

- packages/backend/vite.config.js
Remove from the rollup external the gguf library: it lead to `@huggingface/gguf` not found when starting the extension in production.
> fix: remove gguf from external rollup

- packages/frontend/src/lib/ApplicationTable.svelte
- packages/frontend/src/lib/progress/TasksBanner.spec.ts
- packages/frontend/src/lib/progress/TasksBanner.svelte
- packages/frontend/src/lib/table/application/ApplicationTable.spec.ts
- packages/frontend/src/lib/table/application/ApplicationTable.svelte
- packages/frontend/src/pages/Applications.svelte
- packages/frontend/src/pages/Recipe.svelte
- packages/frontend/src/pages/StartRecipe.spec.ts
- packages/frontend/src/pages/StartRecipe.svelte
Following https://github.com/containers/podman-desktop-extension-ai-lab/pull/1227. This PR add a `Running` tab in the RecipeDetails. 
This has been made to ease the understanding of the relation between Recipe and Applications. Discussed with @slemeur and @jeffmaury in https://github.com/containers/podman-desktop-extension-ai-lab/issues/1360.
- Creating a `ApplicationTable.svelte` component to avoid duplicating code between `/applications` and `/recipe/{recipeId}/running` page.
- The `StartRecipe.svelte` component redirect to the `/recipe/{recipeId}/running` page on completion (button click)
https://github.com/user-attachments/assets/99b2993d-2f9f-4f0e-944c-89c92464f72b
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1360
Require …
> feat: adding running tab to recipe details

- packages/frontend/src/lib/images/VSCodeIcon.svelte
> fix: reduce vscode icon size

- packages/backend/src/managers/podmanConnection.spec.ts
- packages/backend/src/managers/podmanConnection.ts
On Linux machine, we may not have podman machine configured. The getVMType expect at least one machine, with this fix, we handle the case where we have none, and return UNKNOWN.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1406
**Manually**
Start a recipe
> fix: handle vmtype check on Linux

- packages/backend/src/managers/catalogManager.ts
- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/registries/LocalRepositoryRegistry.spec.ts
- packages/backend/src/registries/LocalRepositoryRegistry.ts
To avoid racing issue, in the `init` function of the `LocalRepositoryRegistry` we will list the recipes. 
FIxes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1408
**manually**
Stop and Start AI-Lab, you should always see the recipes already clone indicated in the recipes page
> fix: racing condition catalog loading

- MIGRATION.md
- packages/backend/src/managers/catalogManager.spec.ts
- packages/backend/src/managers/catalogManager.ts
Adding notification when the catalog is malformed or wrong version is used.
https://github.com/user-attachments/assets/15004af9-0ceb-4d81-99e9-858c95f39013
**using old catalog version**
**malformed catalog**
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1394
> feat: create notification on user catalog issue

- packages/frontend/src/lib/ModelSelect.spec.ts
- packages/frontend/src/lib/ModelSelect.svelte
- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/PlaygroundCreate.spec.ts
- packages/frontend/src/pages/PlaygroundCreate.svelte
- packages/frontend/src/pages/StartRecipe.spec.ts
- packages/frontend/src/pages/StartRecipe.svelte
We are offering a Select form in `CreateInference`, `CreatePlayground` and `Start Recipe` page, let's create a single component, easier to style for light mode.
> :warning: I did not change the styling made to the component that were used for StartRecipe. 
N/A
> feat(ui): create SelectModel component

- packages/frontend/src/pages/Applications.svelte
- packages/frontend/src/pages/InferenceServers.spec.ts
- packages/frontend/src/pages/InferenceServers.svelte
- packages/frontend/src/pages/Playgrounds.spec.ts
- packages/frontend/src/pages/Playgrounds.svelte
Improve the consistency of the the `Applications`, `Models` and `Playgrounds` page when none are available.
| --- | --- |
| ![image](https://github.com/user-attachments/assets/7331ee39-9b26-4238-8eb4-ccd31c04a58d) | ![image](https://github.com/user-attachments/assets/e733d4f4-7a1d-4b41-a8f0-222d852ff2cb) |
| ![image](https://github.com/user-attachments/assets/3e1c0fc8-421e-400c-a6d0-41f95b759fb8) | ![image](https://github.com/user-attachments/assets/4358b712-ea80-4b62-871b-d0ed87f8e4f0) |
| ![image](https://github.com/user-attachments/assets/6deee296-07e5-4295-8bc8-4055bef85bc1) | ![image](https://github.com/user-attachments/assets/2127ea2d-ca37-445a-9d67-0f553355a869) |
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/271
> chore: adopt EmptyScreen component

- packages/backend/package.json
- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/registries/ConfigurationRegistry.ts
- packages/backend/src/studio.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/shared/src/models/IExtensionConfiguration.ts
- packages/shared/src/models/InferenceServerConfig.ts
Add an `experimental GPU` preference. When enabled, it will uses the matching container image for the VMType used
- On WSL and with a NVIDIA GPU 
- On Libkrun => llamacpp mac vulkan 
New option `Experimental GPU` in podman desktop preferences
https://github.com/containers/podman-desktop-extension-ai-lab/assets/42176370/6a8c5308-dc96-40bc-9200-210bd1fe9477
Need https://github.com/containers/podman-desktop-extension-ai-lab/pull/1278 to be merged
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1279
**Require to be on windows with a WSL podman machine and a NVIDIA GPU**
- Turn on the experimental flag in the preference
- Set a value for the gpu offloading (E.g. 20)
- Start the inference server
- Go to playground, notice the speed
> feat(Inference): supporting gpu layers

- packages/backend/src/managers/recipes/RecipeManager.spec.ts
- packages/backend/src/models/AIConfig.spec.ts
- packages/backend/src/models/AIConfig.ts
Similar to what has been done for the catalog (https://github.com/containers/podman-desktop-extension-ai-lab/pull/1381). This PR is adding a version check for the `ai-config.yaml`.
As mention in the linked issue, all recipes in the https://github.com/containers/ai-lab-recipes repository are already using the version field with the value `v1.0` so we will be using this too.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1431
**manually**
Start any recipes
> feat(recipe): adding ai-config versioning

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/registries/CancellationTokenRegistry.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.ts
- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
- packages/shared/src/StudioAPI.ts
Adding a Stop button to the playground when the LLM is responding. 
https://github.com/user-attachments/assets/f833fe0c-c175-4a7b-9df4-8b45a0022de6
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1089
**Manually**
- Create playground
- Submit message
- Stop message
- Again
> feature: adding stop button playground

- packages/frontend/src/pages/Models.spec.ts
- packages/frontend/src/pages/Models.svelte
We display the models randomly on the `Models` page, however when using a lot AI Lab I usually have to scroll down to find the models which are available locally.
This PR adds the default sort on models status column to always display the locally available on top by default.
**before**
**after**
> feat: models table should sort on status by default

- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/workers/provider/InferenceProvider.spec.ts
- packages/backend/src/workers/provider/InferenceProvider.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/frontend/src/lib/table/model/ModelColumnAction.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnIcon.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
- packages/frontend/src/pages/InferenceServers.spec.ts
- packages/shared/src/models/IInference.ts
Following https://github.com/containers/podman-desktop-extension-ai-lab/pull/1433, this PR replace the removed `hardware` indication on the `Inference Server Details` page.
- Adding a `labels: Record<string, string>` property to InferenceServer
- Using the gpu label to change the hardware display
**gpu inference server**
https://github.com/user-attachments/assets/685ae3c6-cd08-4214-ad7a-4ce71d248e8b
**cpu inference server**
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1434
**manually**
- Using libkrun or WSL Nvidia
- Turn on experimental GPU support in Podman-Desktop preference
- Create an inference server
- See the `GPU Inference` on the Inference Server Details page
> I do not have a libkrun machine, please @jeffmaury could you try it out ?
> feat: add visual indication for gpu accelerated inference servers

- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/frontend/src/lib/button/CopyButton.spec.ts
- packages/frontend/src/lib/button/CopyButton.svelte
- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
When the service is running, makes the url link clickable. It will open the default browser 
https://github.com/user-attachments/assets/fc160c27-cbaa-4682-8165-1d21f2d38300
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1213
**manually**
Go to inference service details, click on the link
> feat: makes inference server details link clickable

- packages/backend/src/workers/provider/LlamaCppPython.ts
It looks like that if we set the cgroup to read, the container is limited on how to discover the gpu and it only has visibility on the llvmpipe which is slower than a turtle. 
N/A
it fixes #1479 
1. run an inference server with gpu enabled on a mac MX
> fix: remove cgroup when adding device

- packages/frontend/src/pages/PlaygroundCreate.spec.ts
- packages/frontend/src/pages/PlaygroundCreate.svelte
Incompatible models should not be listed in the playground creation page 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1487
> fix: remove incompatible models from playground creation page

- packages/frontend/src/lib/ContentDetailsLayout.svelte
Fixing color definition + padding
| --- | --- |
| ![image](https://github.com/user-attachments/assets/e6a9d064-f4eb-4f38-85fd-93d811677ce6) | ![image](https://github.com/user-attachments/assets/2f9bc678-98d9-438e-a05d-ed72909b2b52) |
| ![image](https://github.com/user-attachments/assets/c57c366e-8fa2-462e-9b0d-c8c00538ce7b) | ![image](https://github.com/user-attachments/assets/3c385d52-c48d-4cd2-8756-2a203dca856b) |
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1485
> fix: recipe card details

- packages/frontend/src/lib/RecipeStatus.svelte
- packages/frontend/src/lib/table/application/ColumnStatus.svelte
- packages/frontend/src/lib/table/service/ServiceStatus.svelte
Provide the color of the table to the spinner props
| dark | light |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/086d4672-8830-4046-9370-3297717d1fda) | ![image](https://github.com/user-attachments/assets/1c866dc1-7d18-4ede-b1c6-b1dbe591b263) |
| ![image](https://github.com/user-attachments/assets/dc5f1123-edf3-482b-9c4b-0458452066bf) | ![image](https://github.com/user-attachments/assets/815e261a-ed2c-407c-97d7-ad4e03428483) | 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1480
> fix(UI): spinner color in light theme

- package.json
- tests/playwright/src/ai-lab-extension.spec.ts
- tests/playwright/src/model/ai-lab-app-details-page.ts
- tests/playwright/src/model/ai-lab-base-page.ts
- tests/playwright/src/model/ai-lab-navigation-bar.ts
- tests/playwright/src/model/ai-lab-page.ts
- tests/playwright/src/model/ai-lab-recipes-catalog-page.ts
- tests/playwright/src/model/ai-lab-start-recipe-page.ts
* Implements AI Lab Page
* Extends ai-lab-extension.spec.ts test
N/A
#978 
* cd `<podman-desktop-repo>`
* git pull --all
* yarn install
* yarn test:e2e:build
* cd `<podman-desktop-extension-ai-lab-repo>/tests/playwright`
* `yarn add -D @podman-desktop/tests-playwright@next`
* cd ../../
* export PODMAN_DESKTOP_ARGS=<podman-desktop-repo>; yarn test:e2e
> Extending e2e graphical happy path scenario

- packages/frontend/src/lib/select/ModelSelect.spec.ts
- packages/frontend/src/lib/select/ModelSelect.svelte
- packages/frontend/src/lib/select/Select.spec.ts
- packages/frontend/src/lib/select/Select.svelte
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/PlaygroundCreate.svelte
- packages/frontend/src/pages/StartRecipe.svelte
The `SelectModel` component used in the `CreateService`, `PlaygroundCreate`, `StartRecipe` was adding all the css/classes required to style the `svelte-select` component. 
For https://github.com/containers/podman-desktop-extension-ai-lab/issues/1462 we need to expose a new select, allowing the user to select the connection when multiple are available.
Therefore we need to make the Select more generic so the styling can be reused.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1518
**Testing manually**
- Go to AI Lab
- Go to the `CreateService` page
- Select any model from the list 
- Start it
- assert => the selected model has been properly selected
> refactor(UI): generify Select component

- packages/backend/src/managers/snippets/java-okhttp-snippet.spec.ts
- packages/backend/src/managers/snippets/java-okhttp-snippet.ts
- packages/backend/src/managers/snippets/python-langchain-snippet.ts
- packages/backend/src/managers/snippets/quarkus-snippet.spec.ts
- packages/backend/src/managers/snippets/quarkus-snippet.ts
- packages/backend/src/studio.ts
- packages/backend/src/workers/provider/WhisperCpp.spec.ts
- packages/backend/src/workers/provider/WhisperCpp.ts
- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
- packages/shared/src/models/RequestOptions.ts
This PR allow the inference server to serve the WhisperCpp model outside of a recipe.
- Adding a new InferenceProvider
- Generating new snippets for WhisperCpp
- Preventing the hardcoded snippets to generate out of context content
**before**
**after**
https://github.com/user-attachments/assets/994c90d1-eee5-474b-934d-7401e59da9b0
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1451
:warning: you may need to pull manually `ghcr.io/containers/whispercpp:latest` if you already have the image locally.
> feat(InferenceServer): adding whisper-cpp inference provider

- packages/backend/src/managers/application/applicationManager.spec.ts
- packages/backend/src/managers/application/applicationManager.ts
- packages/backend/src/managers/inference/inferenceManager.spec.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/managers/podmanConnection.spec.ts
- packages/backend/src/managers/podmanConnection.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
- packages/shared/Messages.ts
- packages/shared/src/models/IContainerConnectionInfo.ts
Makes the `PodmanConnection` extend the Publisher class to exposes the ContainerProviderConnections.
- Refactoring the `PodmanConnection` to keep track of the Connections available
- Adding onDidUnregisterContainerConnection listener 
- Adding onDidUpdateProvider listener
- Replacing manual type listener by `Event` and `EventEmitter`
https://github.com/user-attachments/assets/c151c8c7-2ac5-4281-9a4b-cbc988088f31
We are still not getting the events when the user is stopping the machine from the terminal.
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1520
> feat(PodmanConnection): makes class extend Publisher

- packages/backend/src/assets/inference-images.json
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/backend/src/workers/provider/WhisperCpp.ts
Centralise the inference images to a single file `inference-images.json` to ease updating and maintenance.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1516
**Manually**
Create an inference server, check the architecture of the image match the architecture of the host.
> chore(Inference): centralise inference images

- packages/backend/src/studio.ts
- packages/backend/src/utils/inferenceUtils.spec.ts
- packages/backend/src/utils/inferenceUtils.ts
- packages/backend/src/workers/provider/InferenceProvider.spec.ts
- packages/backend/src/workers/provider/InferenceProvider.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/backend/src/workers/provider/WhisperCpp.spec.ts
- packages/backend/src/workers/provider/WhisperCpp.ts
- packages/shared/src/models/InferenceServerConfig.ts
Same as https://github.com/containers/podman-desktop-extension-ai-lab/pull/1528 but for Inference Servers 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1529
Required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/1462
> feat(InferenceManager): handle podman connections

- packages/backend/src/assets/inference-images.json
This fixes the Vulcan image tag
Using the old one you faced
```
Trying to pull quay.io/ai-lab/llamacpp-python-vulkan@sha256:7e7d15086ec33d0547125a0afb479d91246a67b6d0681ae17260ea7665c333a0...
Error: initializing source docker://quay.io/ai-lab/llamacpp-python-vulkan@sha256:7e7d15086ec33d0547125a0afb479d91246a67b6d0681ae17260ea7665c333a0: reading manifest sha256:7e7d15086ec33d0547125a0afb479d91246a67b6d0681ae17260ea7665c333a0 in quay.io/ai-lab/llamacpp-python-vulkan: manifest unknown
```
N/A
N/A
1. try to pull the image even using the cli
> fix: fix vulkan image

- packages/backend/src/managers/application/applicationManager.spec.ts
- packages/backend/src/managers/application/applicationManager.ts
- packages/backend/src/managers/inference/inferenceManager.ts
- packages/backend/src/managers/recipes/RecipeManager.spec.ts
- packages/backend/src/managers/recipes/RecipeManager.ts
- packages/backend/src/models/AIConfig.ts
- packages/backend/src/studio.ts
- packages/shared/src/models/IRecipe.ts
This PR is just a POC about using an inference server instead of creating the model service container inside the pod with the recipe app container.
The problem that we may face is that there is no link between the recipe and the inference server in the UI so the user does not know that by stopping the inference server the recipe will not work.
It also misses a new task for the creation/reuse of an inference server
The image id is hardcoded 
The image in the chatbot recipe in ai-lab-recipes is wrong
> use inference server when model service image is equivalent to inference server image

- packages/backend/src/assets/inference-images.json
Fixes #1557
Update CUDA and Vulkan images as the ones from ai-lab-recipes are too old
N/A
#1557 
Use inference servers with GPU
> fix: update vulkan/cuda images to work with Granite code model

- packages/backend/package.json
- packages/backend/src/managers/apiServer.spec.ts
- packages/backend/src/managers/apiServer.ts
- packages/backend/src/registries/ConfigurationRegistry.ts
- packages/backend/src/studio.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/shared/src/models/IExtensionConfiguration.ts
Make tha API port configurable 
Fixes #1426 
- Go to Preferences, change the API port, restart the extension and check the API is listening on this port
- Set a port in use, and check that an error is displayed in the status bar
> feat: make api port configurable

- packages/backend/package.json
- packages/backend/vite.config.js
Build extension as module instead of commonJS. As more and more dependencies are distributed in ESM-only format, let's build the extension in this format to prepare using such ESM-only dependency.
> feat: build extension as module instead of commonJS

- packages/backend/package.json
- packages/backend/src/managers/apiServer.spec.ts
- packages/backend/src/managers/apiServer.ts
- packages/backend/vite.config.js
- yarn.lock
Validate API requests and responses according to the OpenApi spec
Using the `express-openapi-validator` needs to patch the `ono` dependency with  https://github.com/JS-DevTools/ono/pull/20
We use the `@rollup/replace` plugin for this (another solution would be to use `yarn patch` to patch the `node_modules` directly, but the project is currently using yarn v1.22, which does not include this command, available only starting from v3)
Fixes #1578
> feat: validate API requests and responses according to the OpenApi spec

- packages/frontend/src/lib/select/ContainerProviderConnectionSelect.spec.ts
- packages/frontend/src/lib/select/ContainerProviderConnectionSelect.svelte
- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/StartRecipe.spec.ts
- packages/frontend/src/pages/StartRecipe.svelte
- packages/frontend/src/stores/containerProviderConnections.ts
Allowing to select the connection the user want to use (if multiple exists) to deploy the Inference Server or Application.
Design is inspired from the `Pull Image` page of Podman Desktop
| Single connection | Multiple **started** connections |
| --- | ---- |
| ![image](https://github.com/user-attachments/assets/5ef73ef4-612b-417d-a86f-8b5286be07e5) | ![image](https://github.com/user-attachments/assets/cb8124c3-d542-4811-9db6-c25c036810a4) |
| ![image](https://github.com/user-attachments/assets/3735dc26-fae7-4431-ae6f-d149626c6346) | ![image](https://github.com/user-attachments/assets/d0ef26fc-c802-4bd6-98d3-39e09e2cec8e) |
**Demo**
https://github.com/user-attachments/assets/916d0533-7f33-4270-97f6-e6461c742006
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1462 …
> feat: adding container provider connection select

- .eslintrc.json
- packages/frontend/src/pages/Model.spec.ts
Configuring [import/no-restricted-paths](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-restricted-paths.md).
The change are the following
- Inside `packages/backend` you cannot import anything from `packages/frontend`
- Inside `packages/frontend` you cannot import anything from `packages/backend`
N/A
> chore(eslint): prevent forbidden imports

- .eslintignore
- .eslintrc.json
- package.json
- packages/frontend/src/lib/RecipeStatus.svelte
- packages/frontend/src/lib/conversation/ChatMessage.svelte
- packages/frontend/src/lib/table/model/ModelColumnActions.svelte
- packages/frontend/src/pages/InferenceServers.svelte
- packages/frontend/src/pages/Models.svelte
- packages/frontend/src/pages/Playgrounds.svelte
- packages/frontend/src/pages/Recipe.svelte
- yarn.lock
While wanting to update eslint dependency, I noticed that svelte files are not analyzed
so before doing the library update, include svelte files during the linting process
files are not compliant so fix the automatic fixes and exclude files from some rules to be able to continue
https://github.com/containers/podman-desktop-extension-ai-lab/issues/1607
> chore: parse svelte files when doing the linting

- packages/backend/package.json
- packages/backend/src/registries/ConfigurationRegistry.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/frontend/src/App.svelte
- packages/frontend/src/lib/Navigation.svelte
- packages/frontend/src/pages/TuneSessions.svelte
- packages/shared/src/models/IExtensionConfiguration.ts
- tests/playwright/src/model/ai-lab-navigation-bar.ts
implement InstructLab navigation bar and empty InstructLab sessions screen
Fixes #1567 
You need to set an hidden setting, in `~/.local/share/containers/podman-desktop/configuration/settings.json`
(you must completely stop Podman Desktop - not only close the window -, edit the config file, then restart Podman Desktop for the change to be taken into consideration) 
```
"ai-lab.experimentalTuning": true,
```
> feat: instructLab navigation bar and empty InstructLab sessions screen

- api/openapi.yaml
- packages/backend/src/managers/apiServer.spec.ts
- packages/backend/src/managers/apiServer.ts
- packages/backend/src/managers/catalogManager.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/models/baseEvent.ts
- packages/backend/src/studio.ts
- packages/backend/src/utils/downloader.ts
Adds a `/api/pull` endpoint to the API to download models
https://github.com/user-attachments/assets/bcc8fb65-cec6-4c79-b85d-6b55875d9f83
Fixes #1583 
Start AI Lab extension
```
$ OLLAMA_HOST=localhost:10434 ollama pull facebook/detr-resnet-101
// should download model
$ OLLAMA_HOST=localhost:10434 ollama pull facebook/detr-resnet-101
// should indicate success and not reload model
$ OLLAMA_HOST=localhost:10434 ollama pull unknown-model
// should fail with error message
```
> feat: implement pull model for API

- packages/backend/src/utils/downloader.spec.ts
- packages/backend/src/utils/downloader.ts
When redirecting through the location header, website may provide only the path (E.g. `/hello`) when we expect a full url. 
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1651
> fix: redirect url on model download

- packages/backend/package.json
- packages/backend/src/managers/modelsManager.spec.ts
- packages/backend/src/managers/modelsManager.ts
- packages/backend/src/registries/ConfigurationRegistry.ts
- packages/backend/src/studio.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/shared/src/models/IExtensionConfiguration.ts
This PR add an hidden configuration allowing to disable the model upload to the podman machine. 
| Enabled (default) | Disabled |
| --- | --- |
| ![image](https://github.com/user-attachments/assets/c2a94bc4-2d8f-4b7b-9588-cc2b868f6eb5) | ![Screenshot from 2024-09-04 15-19-03](https://github.com/user-attachments/assets/55d5a9bf-d02b-4e1a-9b43-a4b24ec1f63e) |
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1661
**Manually**
Inside the `~/.local/share/containers/podman-desktop/configuration/settings.json` add the following **before starting podman-desktop**
```json
"ai-lab.modelUploadDisabled": true,
```
- start podman-desktop
- start an inference server
- no model upload task
- go to container details
- assert mount path is host machine and not wsl (windows)
> feat: allow disabling model upload

- packages/frontend/src/pages/ImportModel.svelte
Fixes model format typo on the model import page in the AI lab extension. Currently, it shows .guff as a supported format whereas it should be .gguf
After the fix:
Fixes #1634 
Build the AI lab extension and test it by running the following command from the Podman Desktop directory:
`pnpm watch --extension-folder ../podman-desktop-extension-ai-lab/packages/backend`
> fix: model format typo on import page

- .github/workflows/e2e-main.yaml
Adds a value for cache-dependency-path in order to fix this error on the workflow:
`Error: Dependencies lock file is not found in /home/runner/work/podman-desktop-extension-ai-lab/podman-desktop-extension-ai-lab. Supported file patterns: pnpm-lock.yaml`
#1692
> chore: add cache-dependency-path to e2e-main.yaml

- packages/frontend/src/lib/notification/ContainerConnectionWrapper.spec.ts
- packages/frontend/src/lib/notification/ContainerConnectionWrapper.svelte
- packages/frontend/src/lib/notification/GPUEnabledMachine.spec.ts
- packages/frontend/src/lib/notification/GPUEnabledMachine.svelte
- packages/frontend/src/pages/CreateService.spec.ts
Fixes #1582
Add a banner when creating an inference server or launching a recipe if GPU flag is on but podman machine is not GPU enabled (MacOS only)
https://github.com/user-attachments/assets/f7dca714-56b0-46d3-b117-581b3a5846b7
#1582 
1. Enable the GPU experimental flag
2. Create an inference server on an Applehv machine
> feat: add banner for promoting GPU enabled machine

- packages/frontend/src/pages/Models.svelte
It enables light mode for the download models tasks panel
before 
after 
N/A
1. download a model
> fix: fix light mode for download models panel

- packages/frontend/src/App.svelte
- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/StartRecipe.spec.ts
- packages/frontend/src/pages/StartRecipe.svelte
Instead of collecting the `trackingId` using `router.location.query.get` the `App.svelte` provide it as a component property.
https://github.com/user-attachments/assets/764ae3f1-3437-43bd-a2d9-23a09b35dff2
> :information_source:  Video is a combination of https://github.com/containers/podman-desktop-extension-ai-lab/pull/1745 and this PR
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1781
Required for https://github.com/containers/podman-desktop-extension-ai-lab/pull/1745
> feat(forms): improve reactivity on trackingId query

- packages/frontend/src/lib/select/Select.spec.ts
- packages/frontend/src/lib/select/Select.svelte
The `Select` component from `svelte-select` do not emit a change event when the clear is triggered. This PR add a clear listener to capture and propagate it.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1791
> fix(ui): svelte select clear event

- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
https://github.com/containers/podman-desktop-extension-ai-lab/pull/1782 introduced a regression (my bad) where the default model selection was ignoring the query parameter `model-id`.
https://github.com/user-attachments/assets/02471e82-6c78-45c9-a973-142a881063e7
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1790
> fix(CreateService): should use query `model-id` to select default model

- packages/backend/package.json
- packages/backend/src/managers/application/applicationManager.ts
- packages/backend/src/registries/NavigationRegistry.spec.ts
- packages/backend/src/registries/NavigationRegistry.ts
- packages/backend/src/studio-api-impl.spec.ts
- packages/backend/src/studio-api-impl.ts
- packages/backend/src/studio.spec.ts
- packages/backend/src/studio.ts
- packages/frontend/src/App.spec.ts
- packages/frontend/src/App.svelte
- packages/frontend/src/utils/client.ts
- packages/shared/Messages.ts
- packages/shared/src/StudioAPI.ts
- pnpm-lock.yaml
Adding the support of tasks action (navigation) in AI Lab
https://github.com/user-attachments/assets/19382b58-ddad-45c6-8e27-38bf5c449ad3
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1742
:warning: Creating an inference server do not create a task (need to create an issue)
1. start AI Lab
2. Go to recipe
3. Start a recipe
4. Leave AI Lab
5. Open Task Manager
6. Click on `View` for the recipe pulling task
> feat: support task redirection

- packages/frontend/src/lib/progress/TrackedTasks.spec.ts
- packages/frontend/src/lib/progress/TrackedTasks.svelte
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/StartRecipe.svelte
I was struggling with https://github.com/containers/podman-desktop-extension-ai-lab/issues/1811 and the only fix that I found was to rewrite and share the tasks management code between the recipe and service form.
Thus adding a `TrackedTasks` component, however to make it works nicely I was forced to either add a lot of svelte4 reactive ($) statement, or move it to runes. (I choose the runes)
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1811
Part of https://github.com/containers/podman-desktop-extension-ai-lab/issues/1789
You can manually check nothing change by starting some recipes, and some inference servers
> feat(UI): share tasks management logic between `CreateService` and `StartRecipe` 

- packages/backend/src/assets/ai.json
Fixes #1771
Add a new model to the catalog
N/A
#1771
Test with playground
> feat: add Mistral Instruct model to the catalog

- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
Fix the inference server not restarting on nvidia GPU
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1841
> fix(LlamaCppPython): nvidia inference server cannot restart

- packages/frontend/src/lib/button/CopyButton.spec.ts
- packages/frontend/src/lib/button/CopyButton.svelte
Following a comment by @gastoner in https://github.com/containers/podman-desktop-extension-ai-lab/pull/1840#pullrequestreview-2357412526 we should be able to decide when using the CopyButton where the tooltip will be visible.
As the `CopyButton` is a wrapper around the ToolTip, it makes sense it extends its props  
N/A
> feat: makes copy button extend tooltip

- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
Implement the @MariaLeonova mock-up for the Inference Server Details page from https://github.com/containers/podman-desktop-extension-ai-lab/issues/1691#issuecomment-2387868931.
- Adding `arrow-up-right-from-square`[^1] to the Model as the link is clickable and it was not clear
- Removing the `name` property bellow the model, as it would be repetitive with the model name above
- Removing the `quantisation` as cannot get this information easily.
[^1]: https://fontawesome.com/icons/arrow-up-right-from-square?f=classic&s=solid
**Server Running**
**Server Stopped**
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1592
> feat: refresh Inference Server Details page

- .github/workflows/ai-lab-e2e-nightly-windows.yaml
Prevent cleanup of the resources create by running pde2e-podman image.
#1917
> chore(ci): do not clean up after pde2e-podman image run in ci

- packages/frontend/src/lib/Navigation.spec.ts
- packages/frontend/src/lib/Navigation.svelte
Just adds the missing right border to the navigation to avoid it visually blending into the page and for consistency with Podman Desktop.
Before:
After:
Fixes #1946.
Quick visual check, unit test pass.
> chore: add missing nav border

- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
Fix the svelte check error 
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1897
Related to https://github.com/containers/podman-desktop-extension-ai-lab/issues/1993
> fix(ui): svelte check error create service

- packages/frontend/package.json
- packages/frontend/tailwind.config.cjs
- pnpm-lock.yaml
Bump @podman-desktop/ui-svelte to latest version 
This PR change the tailwindcss config as explained in https://github.com/containers/podman-desktop-extension-bootc/pull/911
Requires rebase after https://github.com/containers/podman-desktop-extension-ai-lab/pull/1994
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1993
Required for https://github.com/containers/podman-desktop-extension-ai-lab/pull/1866
- PR checks must be :heavy_check_mark:
> chore(deps): bump @podman-desktop/ui-svelte to next

- packages/frontend/src/lib/Navigation.svelte
chore: fix unaligned navigation bar
The icons are not aligned because the "faBookOpen" icon is actually
576x512 and not the usual 512x512, causing the icons to be misaligned.
Inspection of faBookOpen:
```html
<svg aria-hidden="true" role="img" xmlns="http://www.w3.org/2000/svg" class="svelte-fa svelte-fa-base mr-4 svelte-l34xo3" viewBox="0 0 576 512">
```
This PR modifies the icon size to actually be 512px width to avoid
misalignment
**Look at the "open book" icons and text vs the ones below**
Before:
After:
Closes https://github.com/containers/podman-desktop-extension-ai-lab/issues/989
See that it has been aligned
Signed-off-by: Charlie Drage <charlie@charliedrage.com>
> chore: fix unaligned navigation bar

- .github/workflows/pr-check.yaml
updating to macos-14 as this is the version podman-desktop is using.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2037
- PR-check should be ✅
> chore: bump macos version from 12 to 14

- packages/backend/src/studio.spec.ts
- packages/frontend/src/stores/rpcReadable.spec.ts
- packages/shared/src/messages/MessageProxy.spec.ts
- packages/shared/src/messages/MessageProxy.ts
- packages/shared/src/messages/NoTimeoutChannels.ts
Following https://github.com/containers/podman-desktop-extension-ai-lab/pull/1838, the `noTimeoutChannels` was not working anymore. It is an hardcoded list of channels that should not have a timeout. However we now prefix the channel for each api with the class `CHANNEL` property.
To avoid having `${StudioAPI.CHANNEL}-openDialog` I added a `getChannel` method, taking a class, a keyof this class, to ensure typescript prevent us from adding invalid channels.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1991
**Manually**
1. Go to models liste page
2. Click on `import` (top right corner)
3. Wait 10 seconds
4. assert no timeout
> fix(MessageProxy): timeout channels list

- .github/workflows/pr-check.yaml
backport https://github.com/containers/podman-desktop-extension-ai-lab/pull/2038 to 1.3.x
> chore: bump macos version from 12 to 14 (#2038)

- .github/workflows/ai-lab-e2e-nightly-windows.yaml
* Adds `ELECTRON_ENABLE_INSOECT` to default env vars in workflow_dispatch
* Fixes use of `PD_PODMAN_VERSION` for schedule runs
#2092 
N/A
> 2092 fix podman version env var not utilized

- packages/frontend/src/lib/Navigation.svelte
chore: rename recipes catalog to recipe catalog
Searching up the grammar, Recipes Catalog is grammatically incorrect
according to multiple sources and should be Recipe Catalog.
Courtesy of llama3 LLM as well as grammarly AI:
`"Recipe" acts as an attributive noun, describing the
type of catalog, and doesn't need to be plural. "Recipe Catalog" implies
a catalog that is specifically for recipes."`
N/A
N/A
Signed-off-by: Charlie Drage <charlie@charliedrage.com>
> chore: rename recipes catalog to recipe catalog

- packages/frontend/src/pages/InferenceServerDetails.svelte
- tests/playwright/src/ai-lab-extension.spec.ts
Adds one more validation to the service creation test and moves aria-label for endpoint url to upper level.
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2100
> chore(test): moving aria-label to upper level

- packages/backend/src/managers/GPUManager.spec.ts
- packages/backend/src/managers/GPUManager.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
If there are multiple GPUs use the first one that is of known type instead of first GPU. If no GPUs of are known type fall back to the first GPU as before.
Add another string for vendor that is accepted as an NVIDIA GPU when doing GPU detection based on what was seen on linux with an NVIDIA 4070 Ti Super
The VM in which I did testing for potential GPU support on linux (https://github.com/containers/podman-desktop-extension-ai-lab/pull/2180) had 2 CPUs, one of which is NVIDIA but it was not gpu[0]. This should have no effect in people only have 1 gpu. With this change I could use the second GPU.
N/A
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2214
Run unit tests as updated
> feat: improve GPU support when multiple GPUs

- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/backend/src/workers/provider/WhisperCpp.spec.ts
- packages/backend/src/workers/provider/WhisperCpp.ts
Currently we are mounting the parent directory of the model to `/model` and provide the env `MODEL_PATH=/model/${filename}`. This has some issue, has we mount all the content of the parent folder of the gguf files inside the container.
This is mostly not an issue expect for the imported models, let's say you import a model from your Download folder, and let's say you have 5000 files in the download folder: big problem coming.
The problem has been reported by @slemeur 
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/1992
**manually**
1. checkout and start podman studio with ai-lab 
2. start an inference server
3. assert model mounted is properly done
> fix: only mount model file to inference container

- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
Adds initial support for GPU acceleration for linux. It requires a version of Podman which
includes this PR - https://github.com/podman-desktop/podman-desktop/pull/10251
N/A
Refs: https://github.com/containers/podman-desktop-extension-ai-lab/issues/2162
1. Unit tests are added.
2. With a version of podman which has https://github.com/podman-desktop/podman-desktop/pull/10251 landed, build a version of podman-desktop-extension-ai-lab with this PR and run podman desktop with the updated extension on Fedora with an NVIDIA GPU and NVIDIA CDI configured. Create a service and see that is is GPU accelerated and after the first chat request response are fast.
> feat: initial support for GPU on linux

- packages/backend/src/utils/catalogUtils.spec.ts
- packages/backend/src/utils/catalogUtils.ts
- packages/shared/src/models/IRecipe.ts
Add optional language and frameworks fields to recipes. 
I don't know if we want to increase the catalog version number when adding optional fields. @axel7083 @jeffmaury WDYT?
Related to #1693
> feat: add optional language and frameworks fields to recipes

- packages/frontend/package.json
- pnpm-lock.yaml
Temporary (until 1.16.0 release) bump PD UI svelte lib to snapshot version due to changes that are not in 1.15 version
Required for https://github.com/containers/podman-desktop-extension-ai-lab/pull/2246 that needs those changes
> chore: bump up pd ui svelte library to snapshot version

- packages/frontend/src/pages/CreateService.spec.ts
- packages/frontend/src/pages/CreateService.svelte
- packages/frontend/src/pages/StartRecipe.spec.ts
- packages/frontend/src/pages/StartRecipe.svelte
Make the `no running container` not appear when it should not be there.
Today the error is displayed when we do not need it, and never cleared. This PR makes is reactive, only be displayed when the condition are met.
N/A
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2363
Requires
- https://github.com/containers/podman-desktop-extension-ai-lab/pull/2365
- https://github.com/containers/podman-desktop-extension-ai-lab/pull/2364
**Reproduce**
- assert have multiple container engines
- Open AI-Lab
- Open New Service
- assert no error
> fix: no running container never disappearing 

- packages/shared/src/messages/MessageProxy.spec.ts
- packages/shared/src/messages/MessageProxy.ts
- packages/shared/src/messages/utils.ts
vitest mocking system got crazy when circular dependencies are happening.
Here we had a function `getChannel` defined in `MessageProxy`. The `noTimeoutChannels` was importing it, but the `MessageProxy` were also importing the noTImeoutChannels, making mocking go crazy in specific cases.
N/A
Required for https://github.com/containers/podman-desktop-extension-ai-lab/pull/2345
- Pipeline should be green
> fix(vitest): remove circular dependencies

- .github/workflows/ai-lab-e2e-nightly-windows.yaml
* Updates versions of MAPT and pde2e image
* Adds push event trigger to e2e nightly windows workflow
N/A
#2134 
* can only be tested in fork
* change would have to be merged into main
* merging a change of `packages/backend/src/assets/ai.json` would trigger the workflow, run name should contain `[Recipe change]`
> Trigger nightly windows e2e test on recipe catalog change merge

- packages/frontend/src/stores/rpcReadable.spec.ts
- packages/shared/src/messages/MessageProxy.spec.ts
- packages/shared/src/messages/MessageProxy.ts
Resolving the following todo
https://github.com/containers/podman-desktop-extension-ai-lab/blob/4fa1055395388041e564be175e509abf7aa909e9/packages/shared/src/messages/MessageProxy.ts#L223
When creating a store we can provide a list of events
https://github.com/containers/podman-desktop-extension-ai-lab/blob/40d97c3043461a2773dedfcb500d16aad5d5992b/packages/frontend/src/stores/localRepositories.ts#L9
The `RPCReadable` implemention will subscribe to the MessageProxy using the provided channel.
What happen if two store try to subscribe to the same event ? Only the last one is kept.
https://github.com/containers/podman-desktop-extension-ai-lab/blob/40d97c3043461a2773dedfcb500d16aad5d5992b/packages/shared/src/messages/MessageProxy.ts#L213
This PR change it by having a `Set` instead to be able …
> fix: message proxy support multiple subscribers

- .github/workflows/recipe-catalog-change-template.yaml
- .github/workflows/recipe-catalog-change-trigger.yaml
- .github/workflows/recipe-catalog-change-trigger.yml
* Adds windows tests to be executed on catalog recipe change
N/A
#2134 
* create a branch with changes in `packages/backend/src/assets/ai.json` (e.g.: duplicate an entry)
* can only be tested after merge, or triggered in a local fork, though, azure instance won't be created from those and tests will fail
* pipeline `Run recipe tests on catalog change` should trigger
> AI Lab Recipe Catalog change test pipeline

- .github/workflows/ai-lab-e2e-nightly-windows.yaml
- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
* Fixes path of the model files (yet again)
* Adds run tests as admin parameter to the nightly windows pipeline
* Updates default variables and MAPT version to 0.7.4
* Adds excluded regions to Azure spot acquisition
* Splits artifacts into multiple separate uploads - results, traces, videos
N/A
#2442
> Unplanned feature update mapt and enable nightly tests as admin

- package.json
- packages/backend/package.json
I have errors when running the scripts telling me that pnpm is the package manager while it is trying to execute npm
errors on my end
workflows should work as before
> chore: fix scripts to use pnpm and not npm

- tests/playwright/src/ai-lab-extension.spec.ts
Attempts to fix failing e2e test due to timeout expiring during model download.
> chore(test): extend timeout for download and set test to be skipped on windows

- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/registries/ConversationRegistry.ts
- packages/frontend/src/pages/Playground.svelte
- packages/shared/src/models/IModelOptions.ts
- packages/shared/src/models/IPlaygroundMessage.ts
Shows metrics of a model in playground 
https://github.com/user-attachments/assets/4780fdcd-1c0a-43b6-bc3a-51e69fd5c7c7
Closes #438
> feat: alow to show model metrics in playground

- .github/workflows/recipe-catalog-change-template.yaml
- .github/workflows/recipe-catalog-change-trigger.yaml
* Fixes typo in parameter name on trigger job
* Parametrizes the template so it can be re-used from other jobs
* Switches to workflow_run logic for token access
N/A
Closes #2134 
* change packages/backend/src/assets/ai.json
* open a PR
> chore(ci): recipe catalog tests - fixing typo, parametrizing template, switching to workflow_run

- package.json
- packages/backend/package.json
- packages/frontend/package.json
- pnpm-lock.yaml
- tests/playwright/package.json
@sveltejs/vite-plugin-svelte v5 depends on vite 6
latest vitest v2 is not supporting vite6
so upgrading one library is making the requirement to update to vite6 and then all the other libraries
I can't really update one without the others...
outdated dependencies since one month
https://github.com/containers/podman-desktop-extension-ai-lab/security/dependabot/20
Check carefully and unit tests should be 💚
> chore: update vite dependencies

- .github/workflows/ai-lab-e2e-nightly-windows.yaml
* Changes Windows 10 to Pro instead of Enterprise
* Switches the jobs to the previously used older flavor of Azure Machine
#2553 
N/A
> chore(ci): switching to more powerful Azure node, switching win10 flavor to pro

- packages/frontend/package.json
- packages/frontend/src/App.spec.ts
- packages/frontend/src/lib/monaco-editor/MonacoEditor.svelte
- packages/frontend/src/lib/monaco-editor/monaco.ts
- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
- packages/frontend/tsconfig.json
- packages/frontend/vite.config.js
- pnpm-lock.yaml
Tentative to add the Monaco Editor to AI Lab. We cannot do dynamic import because it crashes (no idea why, probably related to the way we manage webview webserver.)
- Cannot use the Monaco editor in tests (vitest) got lots of errors (The Podman Destkop Monaco Editor seems to also have some similar issues, because it has no tests too.)
- Some languages (javascript) are not recognised (probably some naming issues, this should be in a follow-up PR)
Fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/858
1. Start an inference service
2. Go to inference details page
3. assert monaco editor in readonly.
> feat: adding monaco support

- .github/workflows/recipe-catalog-change-template.yaml
- .github/workflows/recipe-catalog-change-trigger.yaml
* Adds secret inherit
* updates Windows 11 version to 24h2
N/A
#2515 
N/A
> chore(ci): secrets: inherit, updating win11 to 24h2 in recipe catalog test

- packages/frontend/src/pages/InferenceServerDetails.svelte
To be able to turn on the `svelte/infinite-reactive-loop` (ref https://github.com/containers/podman-desktop-extension-ai-lab/issues/2643) we have to fix some reactive statement, and the easiest way to do that is to migrate to svelte5 the problematic statements/components.
This PR migrate `InferenceServerDetails.svelte` to svelte5.
You can check manually that the reactivity of the component is still working 
https://github.com/user-attachments/assets/24be865b-a7e3-4cc1-b576-1b07255be878
Required for https://github.com/containers/podman-desktop-extension-ai-lab/issues/2643
> refactor(frontend): migrate InferenceServerDetails to svelte5

- packages/backend/src/managers/modelsManager.spec.ts
the constructor is removed in Node.js v22 so avoid its usage
https://github.com/containers/podman-desktop-extension-ai-lab/pull/2681
> chore: remove usage of stats constructor

- package.json
- packages/backend/package.json
- packages/backend/src/assets/openai.json
- packages/backend/src/managers/apiServer.spec.ts
- packages/backend/src/managers/apiServer.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/backend/vite.config.js
- pnpm-lock.yaml
inference OCI images may not have Swagger UI, so start the swagger UI in Podman AI Lab and make calls from there to the inference server
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2695
start a new playground for example, then go to the services list, click on "swagger documentation"
you'll notice you're using Swagger UI and you can query the inference server URL from there
so swagger UI is served by AI Lab
unit test added
> feat: make AI lab providing swagger UI for the openAI docs

- packages/backend/src/managers/apiServer.spec.ts
- packages/backend/src/managers/apiServer.ts
Fixes #2736
Fixes /api/tags so as to return model name in the model field
N/A
#2736
> fix: return model name in /api/tags

- packages/frontend/src/stores/modelsInfo.spec.ts
- packages/frontend/src/stores/rpcReadable.spec.ts
- packages/shared/src/messages/MessageProxy.spec.ts
- packages/shared/src/messages/MessageProxy.ts
ensure we can't create twice a RPC Channel with the same name (else we got an error)
follow-up of https://github.com/containers/podman-desktop-extension-ai-lab/pull/2596#discussion_r2007611049
> chore: check that we can't create multiple time a RPCChannel with same name

- package.json
- packages/backend/package.json
- packages/backend/src/assets/openai.json
- packages/backend/src/managers/apiServer.spec.ts
- packages/backend/src/managers/apiServer.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/backend/vite.config.js
- pnpm-lock.yaml
introduce again the swagger-ui served by ApiServer.
This time, copy the swagger-ui-dist content to the vite dist folder so files will be found (so no need to exclude swagger-ui-express from vite)
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2695
try dev mode and production mode (create the image, push it to a OCI registry and install extension from there)
go to services/service and click on 'Swagger link' and try it
> feat: make AI lab providing swagger UI for the openAI docs (#2703)

- packages/backend/src/managers/modelsManager.ts
Fixes #2789
Update model info after download/upload is complete
N/A
#2789 
Start a recipe with model download included
> fix: model info was modified async causing issue in recipe start

- packages/backend/src/assets/inference-images.json
- tests/playwright/src/ai-lab-extension.spec.ts
Changes base image for whisper models to ramalama
USING latest
Closes #2631 
PR checks and try to create a service
> chore: changed whisper models base image to ramalama

- packages/backend/src/assets/ai.json
- packages/backend/src/assets/inference-images.json
- packages/backend/src/utils/inferenceUtils.ts
- packages/backend/src/workers/provider/LlamaCppPython.spec.ts
- packages/backend/src/workers/provider/LlamaCppPython.ts
- packages/shared/src/models/InferenceServerConfig.ts
switch to the RamaLama images
Use default images for macOS with gpuLayers=999 (as RamaLama does for libkrun/macOS) rather than using vulkan images
(vulkan images are failing with libKrun (unstable on my end))
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2630
try to start a playground/service for a model
> chore: switch images of llama.cpp to the RamaLama images

- packages/backend/src/registries/TaskRegistry.spec.ts
- packages/backend/src/registries/TaskRegistry.ts
- packages/backend/src/studio.ts
While reviewing https://github.com/containers/podman-desktop-extension-ai-lab/pull/2831 I noticed that the TaskManager was **not** disposable, and therefore might never cleanup the tasks, even if the user disable the extension.
> feat(backend): make TaskRegistry implement disposable

- packages/backend/src/managers/TaskRunner.spec.ts
- packages/backend/src/managers/TaskRunner.ts
- packages/backend/src/managers/application/applicationManager.ts
- packages/backend/src/models/TaskRunner.ts
Add a TaskRunner class to separate task logic and implementation
N/A
Related to #2628 
Start recipes and check everything works as before
> refactor: add a TaskRunner class

- packages/frontend/src/lib/select/ModelSelect.svelte
- packages/frontend/src/pages/StartRecipe.svelte
Migrates model select component to svelte5 syntax
Required for #2893 
Pr check
> refactor(svelte5): migrated model select component to svelte5

- .github/workflows/ramalama.yaml
Fixes #2855
Add a new workflow to test ramalama images
N/A
#2855 
N/A
> chore: add a workflow to test ramalama images

- .github/workflows/ai-lab-e2e-nightly-windows.yaml
- .github/workflows/e2e-main.yaml
- .github/workflows/pr-check.yaml
- .github/workflows/ramalama.yaml
Runs junit reporter always, especially when there are test failures to be details summary.
#2953 
PR check should show summary of test results even if there is a failure.
> chore(ci): run junit reporter always

- packages/backend/src/managers/playground/McpServerManager.spec.ts
- packages/backend/src/managers/playground/McpServerManager.ts
- packages/backend/src/managers/playground/aiSdk.spec.ts
- packages/backend/src/managers/playground/aiSdk.ts
- packages/backend/src/managers/playgroundV2Manager.spec.ts
- packages/backend/src/managers/playgroundV2Manager.ts
- packages/backend/src/models/mcpTypes.ts
- packages/backend/src/registries/ConversationRegistry.ts
- packages/backend/src/studio.ts
- packages/backend/src/utils/mcpUtils.ts
- packages/backend/tsconfig.json
- packages/frontend/src/lib/conversation/ChatMessage.svelte
- packages/frontend/src/lib/conversation/ElapsedTime.svelte
- packages/frontend/src/lib/conversation/SystemPromptBanner.spec.ts
- packages/frontend/src/lib/conversation/ToolCallMessage.spec.ts
- packages/frontend/src/lib/conversation/ToolCallMessage.svelte
- packages/frontend/src/pages/Playground.spec.ts
- packages/frontend/src/pages/Playground.svelte
- packages/shared/src/models/IPlaygroundMessage.ts
Adds Model Context Protocol (MCP) support to the playground.
- The presence of the `~/.local/share/containers/podman-desktop/extensions-storage/redhat.ai-lab/mcp-settings.json` file acts as a feature flag.
- Adding/removing the file or renaming it will enable or disable the feature.
- Streaming is not supported when using tool/function calling with the OpenAI compatible inference servers.
- I've added streaming emulation, but the UX is not great in the current state.
- I'd suggest to add some sort of animation in the chat that tells the user that the model is working.
(I can implement this as a subsequent PR so we can comment on it).
- This feature will only work with the **Granite 3.3 model**.
I can improve other models to support it too, but will require additional work.
- In the demos …
> MCP integration in the playground

- packages/frontend/src/lib/conversation/ChatMessage.svelte
- packages/frontend/src/pages/Playground.spec.ts
When a Chat message contains lines with the same content (or multiple empty lines), Svelte fails because it contains duplicate keys.
This fix adds an artificial key based on the index of the paragraph. Maybe completely replacing getMessageParagraphs with something else can be considered in the future.
n/a
Create a playground and ask the model to repeat something, for example `Repeat the following "Hello" 10 times, once per line`.
> fix(playground): duplicate chat messages can be displayed

- packages/frontend/src/pages/instructlab/AboutInstructLab.spec.ts
- packages/frontend/src/pages/instructlab/AboutInstructLab.svelte
This PR fixes the issue where clicking on the fine-tune button will lead to a blank page
Now I reworked the button so that it will enable the setting in experimental feature for fine tuning
fixes https://github.com/containers/podman-desktop-extension-ai-lab/issues/2665
(have both folders in the same directory)
pnpm watch (in podman ai lab)
pnpm watch --extension-folder ../podman-desktop-extension-ai-lab/packages/backend (in podman desktop)
> fix: reworked fine-tuning button in about section

- packages/frontend/src/pages/llama-stack/StartLlamaStackContainer.spec.ts
- packages/frontend/src/pages/llama-stack/StartLlamaStackContainer.svelte
Do not display instructions block when no info to display.
https://github.com/user-attachments/assets/faa3c2fc-386c-4210-b095-4f957e0cc151
Fixes #2997 
Start a llama stack
> fix: do not display instructions block when no info to display

- packages/frontend/src/lib/table/service/ServiceColumnRuntime.spec.ts
- packages/frontend/src/lib/table/service/ServiceColumnRuntime.svelte
- packages/frontend/src/pages/InferenceServers.svelte
- packages/shared/src/models/IInference.ts
Display runtime for running inference servers
Part of #2614 
Start inference servers with different backends (llama.cpp / whisper.cpp), and check that the runtime is correctly displayed in the list
> display runtime for running inference servers

- packages/frontend/src/pages/InferenceServerDetails.spec.ts
- packages/frontend/src/pages/InferenceServerDetails.svelte
Display runtime in service details
Fixes #2614
Start an inference server and check in the details page that the runtime is correct
> feat: display runtime in service details

- packages/frontend/src/App.svelte
- packages/frontend/src/lib/table/instructlab/InstructlabColumnModelName.svelte
- packages/frontend/src/lib/table/model/ModelColumnName.spec.ts
- packages/frontend/src/lib/table/model/ModelColumnName.svelte
- packages/frontend/src/pages/InferenceServerDetails.svelte
- packages/frontend/src/pages/Model.svelte
Fixes #3018
Update route to handle model ids with /
N/A
#3018 
Go to the models page, select the OpenVINO model and details page should be displayed
> fix: handle model id with /

- packages/backend/src/managers/application/applicationManager.ts
- packages/frontend/src/lib/table/application/ApplicationTable.svelte
- packages/frontend/src/lib/table/application/ColumnRuntime.spec.ts
- packages/frontend/src/lib/table/application/ColumnRuntime.svelte
Display application runtime
The models manager needs to be initialized synchronously, so the app manager has an already initialized models catalog (or depending on race condition, it is possible that the model's backend is not found)
Part of #2614 
Start a recipe and check that the runtime is correctly displayed
Restart (PD, extension, container runtime, etc) and check that the runtime is still correct
> feat: display application runtime

- .github/workflows/release.yaml
Updates ubuntu runner to 22.04. 
20.04 is now deprecated  `This is a scheduled Ubuntu 20.04 retirement. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101`
Required for Releasing AI Lab https://github.com/containers/podman-desktop-extension-ai-lab/actions/runs/15116717255
Tagging in this action should be :heavy_check_mark: 
https://github.com/gastoner/podman-desktop-extension-ai-lab/actions/runs/15129385374/job/42527314022
> ci(workflow): updated ubuntu runner

- tests/playwright/src/ai-lab-extension.spec.ts
Validates service details page for CPU or GPU inference server type.
https://github.com/containers/podman-desktop-extension-ai-lab/issues/2559
> chore(test): validate for inference server type

- packages/backend/src/managers/apiServer.ts
The `response` field is mandatory in a chat response, and llama stack enforces that the field exists in the response. 
Fixes https://github.com/containers/podman-ai-lab-stack/issues/3
See steps to reproduce in https://github.com/containers/podman-ai-lab-stack/issues/3
> fix: always send mandatory response field

- package.json
- pnpm-lock.yaml
- tests/playwright/package.json
Removes unused dependencies vitest and electron. Remove electron from `onlyBuiltDependencies` field.
#3130
> chore(deps): clean up unused dependencies vitest and electron

- Containerfile
Signed-off-by: Marcel Bertagnini <mbertagn@redhat.com>
Added the missing icon path when generating a build in Containerfile
fixes #3086 
1- Go to AI-lab extension
2- Go to recipe catalog
3- download and start, for example the object detection recipe
4- Go to images section and check the icons.
> fix: added missing icon brain.woff2 to container build

- tests/playwright/src/ai-lab-extension.spec.ts
Skips the API test suite as it blocks the object detection test due to the issue reported here: https://github.com/containers/podman-desktop-extension-ai-lab/issues/2925.
> chore(test): skip api tests blocking object detection app tests

- tests/playwright/src/ai-lab-extension.spec.ts
- tests/playwright/src/model/ai-lab-running-apps-page.ts
- Implements installation and custom interaction testing for the Object Detection AI App
- Skips the API test suite due to a known blocking issue: [#2925](https://github.com/containers/podman-desktop-extension-ai-lab/issues/2925).
[#2565](https://github.com/containers/podman-desktop-extension-ai-lab/issues/2565)
This test has been executed across all CI platforms. **Currently, it only passes on macOS.**
- Linux: Fails due to `no space left on device` (exit status 1)  
https://github.com/containers/podman-desktop-extension-ai-lab/actions/runs/15557040077
- Windows: Blocked by issue [#3197](https://github.com/containers/podman-desktop-extension-ai-lab/issues/3197)  
https://github.com/containers/podman-desktop-extension-ai-lab/actions/runs/15675807331
- macOS: …
> chore(test): object detection AI app test

- tests/playwright/src/ai-lab-extension.spec.ts
Cleanups podman machine on the VM before finishing.
> chore(test): cleanup machine on finish

- .github/workflows/ai-lab-e2e-nightly-windows.yaml
- .github/workflows/recipe-catalog-change-template.yaml
* Udates MAPT from 0.7.4 to 0.9.3
* Pre-creates `.pulumi` folder with RWX permissions - was causing failure with permission denied for folder creation from within `podman run`
#2891
> chore(ci): update MAPT version to 0.9.3

- tests/playwright/src/ai-lab-extension.spec.ts
* Removes logic that causes failure on extended test suite
Folow-up #3448 #3540 
* `ELECTRON_ENABLE_INSPECT=true pnpm compile:current` in `podman-desktop` directory
* `PODMAN_DESKTOP_BINARY=../podman-desktop/dist/linux-unpacked/podman-desktop EXTENSION_OCI_IMAGE=quay.io/tdancs/ai-lab-indev:latest pnpm test:e2e`
> chore(tests): follow-up removing unused instructlab/granite-7b-lab-GGUF from tests

- tests/playwright/src/ai-lab-extension.spec.ts
* Fixes test execution order
Follow-up #3599 #3506
> chore(tests): hotfix test order

- .github/workflows/pr-check.yaml
- tests/playwright/src/ai-lab-extension.spec.ts
- tests/playwright/src/model/ai-lab-catalog-page.ts
- tests/playwright/src/model/ai-lab-model-service-page.ts
- Add a new pipeline step to free up disk space on the agent before running the tests
- Improve the test teardown process for more effective cleanup
- Add more detailed logging for cleanup
Closes #3632
> chore(test): improve test cleanup
